### ISSUE TITLE
How to start a new discussion or post a question?

### ISSUE THREAD

**Issue by JLPangloss** [Open-Systems-Pharmacology/Forum#1]
How can I start a new discussion in this forum?

**Comment by RBurghaus** [comment]
If you intend to open a discussion in the Open Systems Pharmacology Forum, you need to visit the "issues" ([https://github.com/Open-Systems-Pharmacology/Forum/issues](url)). In the upper right, you find a green button "New issue", which you need to press in order to get to a window, that allows you to describe your discussion topic. You can mark it with certain labels to classify it and make it easier to find for others.

**Comment by Wenjing1018** [comment]
hi,
When I ran the individual model, the PK-Analyses appeared was particularly large, Warning：Absorption seems to be incomplete or absorption process is not finished.but when I changed the oral administration to intravenous injection, the rest remained the same, and the PK- parameters obtained were all normal. I wonder where the problem is? Thank you very much!
![image](https://user-images.githubusercontent.com/63133525/78416231-20f0af00-765a-11ea-8e89-c1692236c079.png)
![image](https://user-images.githubusercontent.com/63133525/78416244-2b12ad80-765a-11ea-81ec-80066415afe2.png)
![image](https://user-images.githubusercontent.com/63133525/78416252-32d25200-765a-11ea-804b-9f64e6780640.png)
![image](https://user-images.githubusercontent.com/63133525/78416260-3960c980-765a-11ea-8c28-acb8366e28ce.png)
