### ISSUE TITLE
OSP software validation - what and how?

### ISSUE THREAD

**Issue by DanielMoj** [Open-Systems-Pharmacology/Forum#106]
Dear all,

at the moment we are internally discussing the software installation/performance validation of the OSP suite. Does someone have experience in what exactly and how one has to validate the OSP software to comply with regulatory requirements? Additional question: Where can I find these regulatory requirements? (and do they give any instructions on how to comply with them?)
Is the Installation Validator Tool that is included in the OSP installation from 7.1 on enough?

Many thanks in advance!
Daniel

**Comment by StephanSchaller** [comment]
What do you mean by performance validation?

Stephan

**Comment by Yuri05** [comment]
@DanielMoj 

1. OSP Suite contains the library of standard test models 

2. For every new/changed modeling feature (e.g. new species; adjustment of anatomical/physiological parameters; new computational models; …) extensive testing is performed (e.g. comparison of simulated time-concentration profiles with published literature data, plausibility checks, etc.)

3. Once the testing is finished, the library of standard test models is extended to include newly implemented features for the future automated testing 

4. For every new OSP Suite version the following steps are performed:
   * All standard test models are simulated in different computational environments (different operating systems, different language settings, etc.)
   * All simulated results (e.g. time-concentration profiles in all model compartments) are (pointwise) compared with the results of the previous OSP Suite version. 

        Comparison deviations must be:

        a) either below predefined comparison threshold or

        b) a reasonable explanation of the deviations due to changed modeling features must exist (in this case the results are tested as described above (comparison with literature data etc.))

   * Simulated results are included into the OSP Suite Installation Package (_Reference results_)

5. The Installation Validator Tool performs the following steps:
   * Simulates all standard test models **_on the system of the end user_**
   * Compares (pointwise) all simulated results with the installed _Reference results_
   * Creates a „Single state” report (“_VALID_” / “_INVALID_”). Installation is considered valid if and only if all deviations in all models and all output curves are below predefined comparison threshold

This ensures that all tested features produce **_on the system of the end user_** the same results as in the OSP Suite (since the features were implemented and tested for the first time)

With this procedure e.g. the installation validation from the EMA guideline [“**Qualification and reporting of physiologically based pharmacokinetic (PBPK) modelling and simulation**”](
http://www.ema.europa.eu/ema/index.jsp?curl=pages/regulation/clinical_pharmacology_pharmacokinetics/general_content_001729.jsp) is fulfilled.

<img width="611" alt="ema_47" src="https://user-images.githubusercontent.com/25061876/34158163-a476a3b8-e4c4-11e7-848a-9c19518e802f.png">

**Comment by DanielMoj** [comment]
@StephanSchaller 
What I meant was what Yuri05 describes under point 4: 
All simulated results (e.g. time-concentration profiles in all model compartments) are (pointwise) compared with the results of the previous OSP Suite version

@Yuri05 
Perfect, thats all the info I needed - thank you very much!
