### ISSUE TITLE
Small Molecule: Perfusion Limited?

### ISSUE THREAD

**Issue by krinaj** [Open-Systems-Pharmacology/Forum#110]
Hello,

Is there a way to switch to blood flow limited/perfusion limited models for drug kinetics in PK-Sim for small molecules model? By default it uses permeability limited type of model when no large molecules model is selected. 

I understand that physiologically, each organ should have somewhat cell membrane barrier based on structure of the membrane, and it makes more sense to calculate permeability surface area product for all compartments for accuracy. But, just wondering if there is a way in PK-Sim to choose well stirred perfusion limited model or not? 

Also, am interested in knowing what does others think about choosing perfusion limited vs. permeabilty limited models when building PBPK models? Do you only use permeability limited models when necessary (may be makes more sense if you are coding all equations in Berkeley Madonna or R or Matlab) or all the times for small molecules?

Thanks,
Krina

**Comment by Aedginto** [comment]
Hi Krina,
There is no way to switch off the permeability component of the organs and reformulate the equations to a well-stirred organ. The organ will automatically be considered well stirred when PxSA is greater than Q. In this case, organ uptake is rate limited by blood flow and not permeation across the cell membrane. 

Cellular permeability is estimated in PK-Sim based on phys-chem properties. The SA of each organ is also included. As such PxSA is organ specific and there is no one value for all organs. You can test the sensitivity of cellular permeability to assess if your molecule is following blood or permeation limited organ uptake by simply changing the cellular permeability and seeing what happens to the plasma (or tissue) profile. If you increase Pcell and nothing happens, the organs are considered well stirred because PxSA >> Q. 

On your comment about coding on your own, try a well-stirred situation first and see if it describes distribution. You should already have an idea if you expect permeability limited uptake by the size/lipophliciity/charge of your molecule. If well-stirred conditions don't work, try the PxSA route but you will have to have enough data to parameterize the PxSA of each organ. 

Happy modelling!
Andrea

**Comment by krinaj** [comment]
thanks, Andrea.
