### ISSUE TITLE
Are PK-Sim metabolic clearance calculations for IVIVE perturbed by universially unrecognized assumptions from the well stirred liver model?

### ISSUE THREAD

**Issue by tobiasK2001** [Open-Systems-Pharmacology/Forum#125]
recently an interesting article from Benet et al (https://www.ncbi.nlm.nih.gov/pubmed/?term=PMID%3A+28762489 and also see the answer from Malcom Rowland and Pang: https://www.ncbi.nlm.nih.gov/pubmed/?term=PMID%3A+29134634) discussed that all liver clearance scaling concepts contain an implicit assumption from the well stirred liver model resulting in bastardized and incongruent models delivering inferior results compared to the well stirred model. Especially the value of IVIVE may be taken in question. 
Although the well stirred (WS) liver model is not explicitly named in the hepatic clearance part of the manual, the formula PK sim uses for hepatic clearance scaling looks very much like the well stirred liver model. Thus PK-sim also uses the implicit assumption from the fraction excreted concept of the well stirred liver model. 
Unfortunately, the WS model has it’s limitations and is known to perform poorly for highly protein bound drugs. For these the intrinsic CL is necessarily very high but this often cannot be measured in in vitro assays (due assay limitations). That’s why often the fraction unbound in the WS formula is replaced by 1 (as empirical factor) for IVIVE from microsomes or hepatocytes experiments.
But how about the clearance scaling via metabolizing enzyme in PK-Sim? Here the calculated free drug concentration in the cell (were the metabolizing process occurs) are used together with metabolic enzyme concentrations and catalytic activities. 
Are these calculations although perturbed by well stirred liver assumptions? 
Can the liver zonation concept overcome/ improve IVIVE limitations? 
Or should we forget about IVIVE and use only the middle out approach fitting intrinsic metabolic clearance values to experimentally measured plasma data?

Thanks for your ideas and advice!

Tobias

**Comment by Aedginto** [comment]
Hi Tobias,
An interesting read indeed. In my quick read of the papers, I think the main point of the Rowland and Pang rebuttal was essentially that if the assumptions of the WSM are violated, it no longer works all that well. It's a model; this is not surprising. In any situation of scaling a hepatic blood/plasma clearance to an intrinsic clearance, if the assumptions of the model used are violated (regardless of model), there is greater uncertainty in outcomes. As a result, I never use the types of models mentioned in the papers to get intrinsic clearance from a plasma clearance; essentially because if we have a plasma clearance, we can use the data from the study that derived it to optimize specific/intrinsic clearance (middle out approach - for the record, this is optimization and i don't know why people call it middle out, it's a silly term). 

PK-Sim allows for an input of hepatic plasma clearance which is then used to calculate the internal unit of clearance, which is specific clearance (clearance in the intracellular space of the eliminating organ). This has the assumptions of the WSM. I instruct the folks that I train to not use this method to go from plasma clearance to intrinsic clearance because in some cases, it produces spurious results (e.g. when the assumptions are violated). This is not a PK-Sim issue or a WSM issue, this is a user issue of using the wrong equation for the task at hand. 

I prefer optimization (although it has it's issues). If you have plasma clearance, you can optimize specific clearance. As you state, the specific clearance that would be generated from a enzymatic process, if using optimization, is dependent on the unbound fraction in intracellular space, enzyme concentration, but also on organ volume, cellular permeability, unbound fraction in plasma, Kp, zonation....everything that defines the elimination organ is of which clearance is sensitive.  Of course, the optimized value of specific clearance is then only valid within the model structure used to derive it. This has drawbacks however as its not possible to get a unique value for specific clearance when it is very high and the organ approaches blood flow limited clearance. This is OK for a specific data description...e.g. if the value is 10,000 or 100,000 it won't give a different PK profile in the blood flow limited clearance case. If however, you are extrapolating to kids for instance, this number needs to be known with much more certainty as it is multiplied by an ontogeny factor and a kid could go from high extraction to low extraction...depends on the numbers. The optimization process also won't give you a unique specific clearance value in the case of low to no cellular permeability. This optimization process has no well stirred model assumptions associated with it. 

In the case of using in vitro values only, the issue here is, as stated in the papers - what is the free concentration in the in vitro system and how does that compare to the in silico/in vivo system? There's been lots of research on that, which is referenced in the papers. In PK-Sim, in vitro metrics as used to populate the specific clearance value. This value is then used in the equations, with all of the structures involved, to generate a PK profile which then could be used to get plasma clearance. There are no well stirred model assumptions in this process. E.g. if cellular permeability is very very low, the drug won't move into the intracellular space and there won't be any elimination via that organ, regardless of the value of specific clearance. 

My conclusion. Know the question that is to be addressed by the model. Know the drug. Know the model structure and assumptions. Make justifiable decisions in light of this knowledge with appropriate PBPK model evaluations (e.g. sensitivity analysis). 

Take care!
Andrea

**Comment by tobiasK2001** [comment]
Dear Andrea, Thank you very much for your input. We are on the same page here. I wonder what the others might think, or are all agreeing?
Take care! Tobias

**Comment by sfrechen** [comment]
Tobias, thank you for bringing this up.
Andrea, thank you for your excellent comment and description.

I fully agree with Andrea. In a PBPK model we are interested in the "specific clearance" (hence, something like the catalytic activity of the respective involved enzyme(s)). 
Now, there are two ways:

(1) In vivo data (i.e. concentration time profiles) are available. Given your structural model, it is best now optimize the parameter. I actually like the term "middle-out approach" here as we explicitly make use of bottom-up and top-down approaches here. A initial value for your optimization might be obtained using the retrograde well-stirred model (directly possible in PK-Sim). As Andrea stated, having optimized this parameter, you still need to be careful when extrapolating as the identified value may only be valid given the assumptions of your structural model.

(2) Only in vitro data available, e.g. kinetic data from microsomal experiments. You could now make use of the well-stirred model to get a first estimate of hepatic plasma clearance.  But I don't see a reason to do so in the context of a PBPK model. Better try to obtain the desired values (e.g. catalytic activity etc.) and put it directly into your PBPK model. Now of course, if we assume perfectly valid in vitro results, the predictive performance of your PBPK model highly depends on your structural PBPK model and its assumptions including blood flows, permeabilities, potential transporters and finally the predicted unbound concentration at the site of metabolism. Currently, PK-Sim does an explicit well-stirred assumption within the intracellular compartment (or the two intracellular liver compartments in case of liver zonation selected). Further refinements including more complex spatial resolutions might be helpful in certain cases.

**Comment by StephanSchaller** [comment]
WHile this discussion is still hot, I want to adress the issue of generating an IVIVE/C workflow for PKSim (see #101).

Now, while we might start putting sth. toghether, I was wondering if zou have any documents or publications (of IVIVE/C work with PKSim) to get us started?
