### ISSUE TITLE
PK-Sim endosomal clearance - why is it not considered in arterial, venous, and portal vein blood?

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/Forum#132]
Endosomal clearance is modeled in all plasma compartments except for the above mentioned blood organs. Why?

**Comment by StephanSchaller** [comment]
You mean if this is physiologically correct.

Maybe the [publication](https://www.ncbi.nlm.nih.gov/pubmed/29234936) gives a hint. Otherwise I would guess, that pinocytosis/endocytosis does not occur in the endothelium of large vessels and/or their surface area is so small in contrast to the vascular surface area in an organ, such that the "mass" contribution of an endosomal clearance would be negligible.
I would bet on the latter...

**Comment by PavelBal** [comment]
> You mean if this is physiologically correct?

Yes, whether it was a descision based on available data, or...

**Comment by Christoph27** [comment]
I don’t have literature information if the large vessels behave really differently than the organ capillaries regarding endosomal clearance (and no such information was used in model development). However, as Stephan wrote, the contributions from the large vessels to endosomal clearance would be negligible due to the comparable small surface area and thus the small endosomal volume (which is the logic of the model). It was thus decided to neglect any possible contributions from the large vessels (would have been extra effort to include it).

**Comment by PavelBal** [comment]
Thank you, Christoph! I just wanted tro be sure that it was considered and not just forgotten.
