### ISSUE TITLE
2 questions re: PK-Analysis output after simulations

### ISSUE THREAD

**Issue by kitcheu** [Open-Systems-Pharmacology/Forum#138]
Hi, I am new to PK-Sim and have two questions:
- May I know whether there's an option to show renal clearance in the PK analysis output after the simulation? 
- After performing a population simulation for an IV drug, most PK parameters were reported in the output except for a few such as Vd and Vss, which showed <NaN>. Could you please advise me on what would be some possible causes for this?
Thank you!

**Comment by msevestre** [comment]
@kitcheu in PK-Sim, renal clearance is an **input** of your model and not an **output**. Renal clearance will be what you defined in your compound.

>most PK parameters were reported in the output except for a few such as Vd and Vss, which showed

I am not sure I understand your problem. Do you mean that Vd and Vss are NOT reported? Can you provide us with a screenshot maybe and explain what problem you are facing? Thanks

**Comment by Aedginto** [comment]
In order to calculate renal clearance, you can output fraction excreted unchanged in urine (fe). Go to Define Settings and Run from a simulation and select kidney-urine-fraction excreted unchanged. This will give you a line on the graph for this output and total CL x fe is renal clearance. 

Use this output also to optimize any renal clearance process you have by bringing in fraction data that contains a time vs. fe (even if its just one cumulative value) value. The numerical optimizer can then be  used or you can just play with your renal CL input until the line matches the known fe.  

For the output of CL or Vss or Tmax or whatever, you can export these values to a csv file for each individual in your population by right clicking on the simulation in the tree and selecting 'Export PK-Analyses'. In this file, you will see each patient and all of their PK parameters (if you open in Excel you will have to Import from text and delimit by semicolon to get the csv into columns).
Take care!
Andrea

**Comment by msevestre** [comment]
FYI:

I have added a feature request [Display Total Renal Clearance in PK Analysis window #570](https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/570) in PK-Sim
