### ISSUE TITLE
How can I register renal clearance to simulate clinical practice conditions?

### ISSUE THREAD

**Issue by jgonlop3** [Open-Systems-Pharmacology/Forum#14]
I have a question about how renal clearance is calculated. In clinical practice, the creatinine value, which is used to estimate the glomerular filtration rate, is known. How can I enter this data (CLcreatinine) or GFR in PK-Sim? I have read the ADME chapter of the manual and I do not understand how to do it. Can anybody help me?

**Comment by JanSchlender** [comment]
Maybe you need to be a bit more precise. Do you want to include an unspecific renal elimination, a tubular secretion (unspecific or mediated by certain transporter(s)) or just filtration? Is reabsorption considered?
Since you mentioned creatinine clearance, I believe that you are only interested in the GFR. In case you trust the creatinine clearance and its validity for the filtration capacity, you can adjust the specific GFR (Individual->Anatomy&Physiology Tab->Physiology->GFR(specific). This is the filtration capability of the kidney. In order to change it in the desired magnitude, you need to relate it to the kidney size of this individual. 

Example: GFR (specific)=26,54ml/min/100g organ - kidney size 440g -> 117ml/min; 
desired absolute GFR=90ml/min ->GFR(specific)= 90ml/min * 26,54ml/min/100g organ /117ml/min  = 20,42ml/min/100g organ.

This will be easier with the upcoming version. 

Now you need to assign the GFR as an elimination process in the compound building block. Choose the ADME tab ->Transporter&Excretion -> Renal Clearance -->right click to add the GFR. The parametrization is then explained in the manual (Chapter 15.1.2.4.2. Renal Clearances, page 109)

**Comment by jgonlop3** [comment]
Then, Do I assume that renal volumen is equal to renal weigh (0.44 L = 440 g)?

**Comment by jgonlop3** [comment]
I think I understood the calculation. But I need more help to enter the data in the ADME section. Could you explain how I should do it, please? I have already read the manual but I do not know how to introduce the GFR

**Comment by JanSchlender** [comment]
Create a compound -> Fill out the basic requirements indicated with the red circle -> Click "Next" or on the "ADME" tab -> Transporter&Excretion -> Renal Clearance -->right click to "Add renal Clearance Process"-> Select "Process type" "Glomerular filtration"  and define the value as described in the manual Chapter 15.1.2.4.2. Renal Clearances

**Comment by msevestre** [comment]
and here a screenshot

![image](https://cloud.githubusercontent.com/assets/1041237/26455365/fc968f4e-4137-11e7-940c-6360002ee598.png)
