### ISSUE TITLE
Large Mol. Endosomal Uptake and Recycling

### ISSUE THREAD

**Issue by prvmalik** [Open-Systems-Pharmacology/Forum#143]
Hi all,

I've been working through the large molecule PBPK model on PK-SIM published by Niederalt et al. a few months back.  I appreciate the endeavour to make the fraction recycled to plasma =1 (frec_vas) and the fraction of endosomal uptake from plasma =1 (fup_vas) to allow clarity and identifiability for the extravasation rate.  

However, endosomal uptake from the interstitial space may be important for assessing bioavailability in the context of subcutaneous absorption.

My question is:  What are the implications of changing the default parameters to those used by Shah, Garg, the Balthasar group, myself etc. -> fup_vas = 0.5 and frec_vas = 0.715?  What other default parameter estimates may be compromised by using this parameterization of endosomal uptake and recycling?

**Comment by Christoph27** [comment]
Since interstitial concentrations are smaller than plasma concentrations (assuming e.g. antibodies) the total endosomal uptake rate will be smaller when choosing the fraction fup_vas = 0.5. To compensate for this, the rate constant for endosomal uptake (k_up) can be increased slightly in order to get the same clearance as before.  As you mentioned, fup_vas = 0.5 and frec_vas = 0.715 will open an additional net extravasation route and theoretically one could think of re-parameterizing all parameters including lymph and fluid flow recirculation flow rates.  However, I think the rate constant for endosomal uptake (k_up) should be the most relevant parameter to re-adjust and I would first try to re-adjust only this one if you don’t want to touch everything.  
Just to give an idea: k_up had a value of 0.36 min-1 in the previous PK-Sim version until 7.0 when assuming fup_vas  =  0.5 (and  frec_vas = 0.5 ). However, since more things changed in the new parameterization, 0.36 min-1 will most probably be not the perfect choice. So I would say k_up  should be larger than 0.294 min-1 (current value) and not very far away from of 0.36 min-1. 
The distribution behaviour of the model will be slightly different compared to the original model, since you have an additional extravasation route. However,  fup_vas = 0.5 and frec_vas = 0.715 should be better in this regard compared to fup_vas = 0.5 and frec_vas = 0.5 (previous PK-Sim parameterization).
I agree, that endosomal uptake from interstitial space could be interesting for SC applications. In my – though rather limited and unsystematic - experience with the previous parameterization of the PK-Sim model, the bioavailability reduction due to the endosomal uptake from interstitial space was rather limited. It would be interesting to hear from your experience regarding that.
All the best, Christoph

**Comment by prvmalik** [comment]
Thanks for your thorough reply Christoph.  

For my model the optimal Kup value was 0.38 min-1 as you suggest.  The initial distribution is a bit steeper but within the realm of plausibility.

My previous models in MATLAB for SC administration agree with your experience - about 96% uptake occurs through the lymphatic system rather than upwards through the vascular endothelium.  I am implementing a SC absorption compartment in Mobi this week for a mAb (similar to that designed by Zhao 2013) and will let you know how it goes.

**Comment by msevestre** [comment]
@prvmalik Please do not hesitate to let us know how the experience went. Closing for now

**Comment by Salih-Benamara** [comment]
Hi all :) 

@prvmalik, Did the parametrization Kup value = 0.38 works without any other changes for you ? (using  fup_vas = 0.5 and frec_vas = 0.715)  regarding the re-parameterizing of the model. Thank you very much !

**Comment by prvmalik** [comment]
Hi Salih,

In general I do not do this since it disrupts the model too greatly, including the endogenous IgG network that is built in. Hard to comment more because it has been a very long time. 

Paul
