### ISSUE TITLE
Adding metaboli enzyme process

### ISSUE THREAD

**Issue by moulirc** [Open-Systems-Pharmacology/Forum#144]
![image](https://user-images.githubusercontent.com/27323536/36704106-91e7f18a-1baa-11e8-9c44-73153972cb32.png)

How can I select which is the best process for a drug - this has to be done based on the literature?

**Comment by tobiasK2001** [comment]
Dear moulirc,
it should be based on what you know from literature or own experiments. E.g. if you know the clearance is dose linear i.e. not saturable you may chose a first order clearance. Otherwise chose a michaelis menton type. If you got intrinsic CL from in vitro experimenst using microsomal preperations and you would like to scale your experiment accordingly chose "in vitro metabolic rate in presence of liver microsomes and adjust the content of your CYP in question. All other scaling factors (e.g. content of microsomes /per gram liver) you can leave to PK-Sim the content of CYP3A4 is given as default value in PK-Sim. You can chose one of the other processes as well and can give PK-sim teh calculation paremeters e.g. enzym concentration for scaling. Or if you don't know them you can fit them. There are many ways leading to similar results in PK-sim. So the best way maybe to take as much as you can from literature and fit the missing piece.

Hope this might help.

Best Tobias

**Comment by moulirc** [comment]
Thanks, for your help
