### ISSUE TITLE
Large Molecules - Parameters influencing Cmax?

### ISSUE THREAD

**Issue by DanielMoj** [Open-Systems-Pharmacology/Forum#146]
Dear all,

I am working on a large molecule model (no specific binding) with iv bolus administration in mice. With the model simulations I cannot reach the observed maximum molecule concentrations. Additionally, the half-life is simulated a bit too short. Reducing the rate constant for endosomal uptake easily gets the half-life right. But still the Cmax (and overall exposure) is much lower than observed.

Which are eligible/typical parameters for parameter identification to increase the plasma concentrations??

Thank you very much in advance!!

best
Daniel

**Comment by PavelBal** [comment]
Do you have some enzymatic degradation? In that case, distribution of the enzyme in tissues might play a role - and the PK-Sim database in not always a reliable source...

Otherwise - the parameter "Radius (solute)" determines the diffusion rate from plasma into interstitial space. You could try to "tweak" it a bit, PK-Sim calculates the value based on the molweight. You can also take this publication

http://onlinelibrary.wiley.com/doi/10.1002/mrc.1132/abstract

to have some reference point for the correlation between molweight and the Stokes radius.

**Comment by tobiasK2001** [comment]
sorry for touching the obvious but are you sure that the applied dose is in the mouse is identical to the nominal (or labbeled) dose? Even with some unspecific degradation in plasma the Cmax after iv bolus should be nearly reached as there is no time for metabolism. 
other wild guesses: 
Thought about stability in the syringe? 
Missing some convertion factor? e.g. AB is pegylated but analyte in assay is not
data units imported to PK-sim are wrong...
You might have checked is this of course...
good luck, Tobias

**Comment by Christoph27** [comment]
Since Cmax after an IV bolus is just dose/plasma volume I agree with Tobias to double check dose and units (also of experimental data) if not already done. Parameters like the "Radius (solute)" would only help if your first measured data point is considerably later than time of administration. An additional comment (and question) to clearance: I assume your compound does not bind to FcRn? Then reducing the endosomal uptake rate constant could be justified by steric considerations if you have a very large molecule (larger than IgG antibodies). I have observed a similar clearance behaviour for very large molecules. Thus it would be interesting to know if you have also a molecule which is larger than an IgG antibody.  
All the best, Christoph

**Comment by Christoph27** [comment]
Another thing coming to my mind maybe to be checked: Plasma vs. blood concertation

**Comment by DanielMoj** [comment]
Thanks all for your ideas!

@PavelBal 
enzymatic degradation should play no role, but i will keep the enzyme dstribution in mind for another molecule ;) - Thanks for the publication link! I will check it this evening!

@tobiasK2001 
Sometimes one misses the most obvious things :) ... As I did in this case! :D...
Due to the nature of the assay I indeed have to take a correction factor for the observed data into account. So, with this correction factor the model works fine!! 

@Christoph27 
The molecule is way larger than IgG and does not bind to FcRn (observed and simulated in plasma)... Do you may be have some reference to underpin the steric justification to reduce the endosomal uptake rate constant? Or, what yould be the idea behind it? Interesting!! :)

best
Daniel
