### ISSUE TITLE
Midazolam full PBPK model

### ISSUE THREAD

**Issue by farzanehmaleki** [Open-Systems-Pharmacology/Forum#171]
Does anybody has PK-Sim Midazolam full model to share?

**Comment by tobiasK2001** [comment]
Hi, did you consider loading it from the PK-sim in-build templates?

Kind regrads, Tobias

**Comment by msevestre** [comment]
@farzanehmaleki FYI: Attachement are removed when responding to email. If you wish to upload your project (and it will be available to everyone!), you will need to zip it and use the Attach file method directly in github

**Comment by krinaj** [comment]
I had encountered the same issue last year. It seemed like the template model for Midazolam in PK-Sim did not match with midazolam model published by the PK-Sim team (can't remember exactly which parameters) (https://www.ncbi.nlm.nih.gov/pubmed/27822600). I assumed that since template might be developed earlier and paper was published recently, I updated the model to match what is published in Moj et al 2017. The evaluations looked good then. I will try digging through my old work and send it over.

**Comment by TWendl** [comment]
The Midazolam model version published by Moj et al. was the first published model with PK-Sim (apart from a very old version, see https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1853074/)
The PK-Sim Midazolam template model is an updated version of Moj et al.. This updated version will be reported soon in a paper that was just submitted for publication. I will let you know as soon as it is accepted.

**Comment by krinaj** [comment]
Thanks, Thomas for clarification. 

I am thinking that since PK-Sim model library will keep evolving, it will be very helpful for the users if some more details or reference to papers (where model development/evaluations is discussed) be added in. If no reference published, brief description of model development and evaluation would be helpful as well. 

Just a thought, would it be helpful to add a box dedicated to model notes/references?

Kind regards,
Krina

**Comment by farzanehmaleki** [comment]
It is most appreciated Thomas.

Thank you,
Farzan

**Comment by msevestre** [comment]
@krinaj Agreed. Some work needs to be done.
Possibly a centralized compound database as discussed in #10 would be a great addition.
With the upcoming 7.3 release, all technical requirements will be implemented to support such a database

**Comment by farzanehmaleki** [comment]
Hi,

When I simulate Midazolam profile for different dose, the PK-Sim template and my model are showing dose proportionality, while the NCA results of my data say the opposite (in both Pk-Sim template and my model, the clearance is Michaelis Menten). Any thought of how to impose this into the model?

Best,
Farzan

**Comment by StephanSchaller** [comment]
@farzanehmaleki - A first thought:

What are the concentrations you reach in your model? When / in what direction do you observe dose-nonlinearity? 
The Km for MM of CYP3A4 metab is almost 3 µM. Maybe you are yet in the linear range (<< 3µmol/l)?

**Comment by farzanehmaleki** [comment]
Hi Stephan,

Good point!

I have IV bolus data with 1, 2, 3, 5 and 21mg doses and the corresponding Cmax varies from 9 to 1100 ng/ml (20<AUClast<800). For 2,3,5 mg Cmax is dose proportional, for 2,3,5,21 mg, AUC is dose proportional. 1mg dose does not follow other doses. In my PBPK model, I optimized Km and Vmax for MM of CYP3A4 1-OH metabolite. For 1mg, Km~4.5 and Vmax~10 while for the other doses Km~2.1 and Vmax~2.5. 

Having said that, should I consider 1mg dose and conclude dose nonlinearity or neglect 1mg and consider the dose proportionality? If I disregard 1mg data, the PBPK model matches the data with 3,5,21 mg dose by optimizing the Km and Vmax.

Thank you,
Farzan

**Comment by StephanSchaller** [comment]
Hm, this looks more like either a data problem or an early distribution / protein-binding problem and less like a clearance problem. Some things to consider:
1. Cmax for IV bolus should be more or less dose proportional: How do the Cmax for 1 and 2 mg compare? Cmax for 1 mg << half of Cmax for 2 mg? If yes, maybe it is because of the high protein-binding interfering with the assay for low doses. So the data may not be telling the whole truth.
2. The obvious (thus unlikely): I guess the data is from the same individual / cohort? Otherwise inter-patient variability could be a reason.

Hope this helps,
Stephan

**Comment by farzanehmaleki** [comment]
Thanks a lot Stephan. The problem seems to be more due to data. The data for each dose is mean of a population reported in different studies but more or less with the same individuals properties (BMI and age). I have only one dataset for 1mg which may miss the variability. I will try to find more data for low doses before making any conclusion.

 Best,
Farzan

**Comment by tobiasK2001** [comment]
Dear Farzan,

regarding low dose midazolam data and dose linearity youm might find this paper usefull (if not already known) 
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4309633/
Best, Tobias

**Comment by farzanehmaleki** [comment]
Hi Tobias,

Thank you for sharing the link.

Best,
Farzan
