### ISSUE TITLE
Changing Gastric pH doesn't affect the plasma profile of weak base drugs with pH-dep. solubility

### ISSUE THREAD

**Issue by RamyAmmar** [Open-Systems-Pharmacology/Forum#174]
Dear All,
I am just wondering why changing the gastric pH in the Itraconazole model -PK-Sim template model- doesn't show any changes in the plasma profile curve or the PK parameters, although this drug shows pH-dependent solubility. Now I am working on another weak base drug with pH-dependent solubility and it also doesn't show any change with changing the gastric pH. So I think it is a program related issue not model related. Could anyone help me please?

**Comment by StephanSchaller** [comment]
Hi Ramy,

pH should be sensitive. It depends of course on the concentrations you reach in the GI-Tract. If you dose too low, you may not reach concentrations above solubility. Here, you can see a plot, where you can see how dissolved concentrations of IC in the GI are limited due to solubility:

![image](https://user-images.githubusercontent.com/25477643/39783956-1354059e-5317-11e8-8d3a-1fc7b11a4765.png)

An here you can see the sensitivity of the different pH levels in the GI segments with regards to plasma IC PK (AUC_inf):

![image](https://user-images.githubusercontent.com/25477643/39783992-367ed88c-5317-11e8-994c-ed7997916215.png)

Hope this helps,
Stephan

**Comment by msevestre** [comment]
@StephanSchaller Kudos for showing sensitivity graph as well.

**Comment by RamyAmmar** [comment]
@StephanSchaller First of all thank you very much. you are totally right but I specified the **GASTRIC pH** not other segments.
Actually, I had similar results with my model as shown in the figure below. But it's related to all GIT segments **EXCEPT** the stomach where my question is concerned about. when it comes to the gastric pH you will see no impact as shown below. 

![image](https://user-images.githubusercontent.com/34481321/39837196-06d5f24a-53d6-11e8-8ed8-c66565d8eb64.png)


![image](https://user-images.githubusercontent.com/34481321/39836903-30d76bce-53d5-11e8-8e0b-71aa1191bccb.png)


By the way, if you check the sensitivity analysis of the IC model for gastric pH you will see no effect similar to my case. 

I just would like to clarify why I am asking this question, the observed results confirmed that increasing the gastric pH by PPIs decreases the exposure of our drug. So I want to simulate this by increasing the gastric pH BUT by increasing the gastric pH I coudn't see any change. The only possible way to see a difference in the plasma curve is to increase the pH of all GIT segments!!!!!! So what do you think, What should I do to simulate the using of acid reducing agents without building model for PPI drug.

**Comment by PavelBal** [comment]
This is how I see it: the absorption is not limited by the solubility of the compound in the stomach, but in other segments. If you take a look at the figure @StephanSchaller posted, you can see that the concentration in the stomach is much higher than that in the GI segments. At the same time, the concentration in the GI segments is saturated, probably due the the solubility limitations.

So if you change the gastric pH you will see higher concentration in the stomach, but the concentration in the GI segments remains limited.

So, in order to observe the effects of gastric pH on plasma profile, the administered dose must be not too low to see any solubility effects in the stomach, but also not too high such that drug transfer from stomach into GI is the absorption limiting factor, and not the solubility in GI segments.

**Comment by StephanSchaller** [comment]
@RamyAmmar , were you able to progress in your work?

Maybe you can evaluate handling of PPIs in PBPK with existing work:
https://pubs.acs.org/doi/10.1021/mp4003249

We would be very interested in your conclusions.

Hope this helps!
Stephan

**Comment by RamyAmmar** [comment]
@StephanSchaller Thank you very much for passing this paper to me. In my simulation for PPI i did change the pH to 5 and also prolonged the gastric emptying time as suggested by other references. Regarding the dissolution time, since I don't have experimental data I optimized it with the observed data for the clinical trial with the PPI. This actually helps. 

According to my understanding, the problem  is that the dissolution time-Weibull parameter- unlike the solubility is not linked with the pH. This means that if I want to simulate at different pHs, the solubility will be changed automatically depending on the chosen pH while the dissolution time won't be changed since it's not interlinked with the pH. In turn, I have to change the dissolution time manually according to the literature showing the dissolution at the choosen pH or by optimizing the dissolution value based on observed plasma profile data at this pH. This means that I have to have either in-vitro or in-vivo date for the disolution at the choosen pH and if I don't have any of them, the predicton won't be accurate.

So my questions are: 
1. Is there any way to make the dissolution, like the solubility,linked to pH to be changed automatically  just by changing the pH, in case of drug with pH-dependent solubility.
2. I couldn't find the values of the gastric and intestinal fluid volumes, could you show me how can I find them.

Again thanks for help.

**Comment by StephanSchaller** [comment]
@RamyAmmar 

1. First guess: you could edit your dissolution function in MoBi and make dissolution time a formula instead of a parameter. Then include pH as a parameter in the formula (I would have to look at a project in MoBi to tell for sure).
2. In MoBi, the Liquid Volume can be found in: "Organism|Lumen|*GISegment*|Liquid". *GISegment* could be and part of the GI like "Stomach" or "Duodenum"...

NOTE: "Liquid" volume is defined as a differential equation (the property "Parameter is state variable" is activated) depending on inflow and outflow from / to other GI segments. So be careful when editing.

**Comment by msevestre** [comment]
@RamyAmmar 

Agreed with @StephanSchaller.  MoBi will be the way to go if you want to make your dissolution profile a function of pH (using a so called `ExplicitFormula` instead of a constant value)

Starting with 7.3, it will be possible to also create a table (pH vs Dissolution) for example that could then be used to retrieve the dissolution value for a given pH. This will have to be done in MoBi as well but will be slightly easier to define than an actual formula.

**Comment by msevestre** [comment]
@RamyAmmar Closing. Let us know if you need more info
