### ISSUE TITLE
Clearance problem

### ISSUE THREAD

**Issue by calixto16** [Open-Systems-Pharmacology/Forum#198]
I'm using PK -Sim version 7.2 and I'm having some troubles. I'm working with warfarin modeling and when I set up the characteristics of the compound I include ''total hepatic clearance'' parameter with a value of 0,065 ml/min/kg, so I expect that the arimethic average of total hepatic clearance in the population I used in my simulation would be arround that number.

However, when I export all the data to Excel and calculate the average Clearance of the entire population it is much bigger. I'm getting a 0,094 ml/min/kg and the bioavailability is complete (I alredy checked using AUC in my disolution/AUC intravenous)

How can I solve this?

**Comment by JanSchlender** [comment]
Hi,
PK-Sim relies on a building block concept. This encounters three pillars: The i) individual/population, ii) the compound and iii) an administration scheme. Theses three pillars are independent and are plugged together to set up a simulation. 
In this context, Clearance as an input parameter (which you refer to with a "total hepatic clearance) is a compound property and is independent of the individual. It will not be varied when creating a population. This means, that the input parameter total hepatic clearance is the same for each individual in a population simulation in case you do not add a user defined population variability when setting up the simulation. 
Since you also refer to bioavailability (which has nothing to do with your clearance), I assume you calculated the average output clearance of your simulation. This is computed by an NCA and may of course differ from your input. 
Furthermore, you may have recognized, that you entered a plasma clearance which is converted to a specific clearance based on your individual/population characteristics.
Best, Jan

**Comment by sfrechen** [comment]
In particular the conversion from total hepatic plasma clearance to specific clearance makes the assumption of a well-stirred liver model. The converted specific clearance is explicitly used as simulation input. However, the full PBPK model does not make the assumption of a well-stirred liver, thus you won't get the "desired" clearance output after simulating from the full PBPK model. You may revise your input value or (recommended) fit your specific clearance value to observed concentration-time profiles.

**Comment by calixto16** [comment]
Thank you for your answers. 

I think that it's probably what Sebastian said, that the issue in the different clearances is due to the assumption between the disered clearance and the one that the program uses for the simulation.

Pilar

**Comment by calixto16** [comment]
And could you please explain to me how can I fit my specific clearance to my observed concentration-time profiles? 

Thank you again, Pilar.

**Comment by msevestre** [comment]
@calixto16 
Check out the Parameter Identification chapter in the documentation (29.2. Parameter Identification).
