### ISSUE TITLE
Slight difference in simulation results between PK-Sim Metronidazole model and published plots

### ISSUE THREAD

**Issue by tobiasK2001** [Open-Systems-Pharmacology/Forum#201]
I opened the Metronidazole model from the Pregnany model files as descrined by Dallmann et al 2018. 
I am not sure when the model was created but in the readme for the pregnancy model it was stated the structure was implemented in PK-sim 6.3. https://github.com/Open-Systems-Pharmacology/Pregnancy-Models.
In the adjunct Paper it is stated that the model can be opened in PK-sim 7.2.0.
However, when I open the Metronidazole IV simulation in PK-sim 7.2.1 there seems to be a slight different: higher metabolism in Liver and higher fraction excreted to urine. (Fig 5a Paper vs attached screenshot)
In this case the variation is very slight and I would say the measured data is described equally good if not even better. However, in other cases it seems to look worse. Plus there is a constant fear for the user that he might not reproduce his simulation with a new version. So I wonder where the difference might come from here? Anyone having similar issues?
![grafik](https://user-images.githubusercontent.com/25585248/43066572-4dc0d976-8e65-11e8-9b8f-53a21a827a24.png)
![grafik](https://user-images.githubusercontent.com/25585248/43066592-5b9c426a-8e65-11e8-9299-595a83e7e30b.png)

**Comment by msevestre** [comment]
Hi @tobiasK2001 ,

Fear no more! the OSP Suite undergoes a very extensive validation process before being released out. 
On top of **over 10000 automatic tests being run every night**, we also compare a set of new simulation outputs (over 100 simulations in fact,  covering all possible use cases implemented in PK-Sim) with outputs calculated from the previous version and ensure that the results are the same. If differences are observed, we ensure that those differences are due to model updates.


What we aim at providing is the following:
1. Each simulation created with an old version of PK-Sim should output the same outputs when run in a newer version
1. Each new simulation added to a project created with an old version of PK-Sim will receive the latest and greatest model features that were added to the software. This is true also for a simulation that will be updated with new building blocks. All of those features and model improvements are described in detailed in each release notes published along the release. It is the user responsibility to read and understand the changes. In this case, the simulation output may differ slightly depending on changes incorporated in the model. For example, new ontogeny function, new large molecule model implementation etc..

Last but not least, the InstallationValidator provide a way to ensure that your computer is behaving as expected and outputs the same results as our test computers.

Coming back to your issue:

- I downloaded the file `https://github.com/Open-Systems-Pharmacology/Pregnancy-Models/blob/master/Models/Metronidazole/Metronidazole_Pregnancy.pksim5` and opened it with version 7.3
- I then proceeded and opened simulation `Non-pregnant_Houghton1979`
- I took a screenshot of the plot BEFORE simulating 
- I took a screenshot of the plot AFTER simulating 

The outputs are identical. e..g there is absolutely no difference in the simulation results before and after simulating.

> However, in other cases it seems to look worse. 

Hard to help here. You will have to provide us with more details

Since it seems that you are comparing PK-Sim plots with published plots not created with PK-Sim, the deviation you are seeing could very likely not be due to PK-Sim.

If you have concrete examples of deviation between old and new projects, please do not hesitate to let us know. I would suggest however to use the PK-Sim issue tracker as it is more suited to discuss those kind of topics than the forum.

Hope that helps,

Michael

**Comment by tobiasK2001** [comment]
Dear Micheal,

thnaks for the confirmation. Indeed the simulation does not change, if opend and rerun in 7.2.2. And now we know with 7.3 it is the same. Regarding the difference between the published figure I guess only Andrè knows the reason.  ;-)
Rgerading the other case I will post something on the PK-sim issue tracker hopefully soon .

Cheers, Tobias

**Comment by AndreDlm** [comment]
Dear Tobias, 

first of all thank you for your interest in our work! 

In fact, there seem to be multiple reasons for the difference between the published figure and the simulation in PK-Sim and it took me some time to trace it down to the root. 
Basically, the simulated plasma concentration you are showing is from an individual woman, whereas the figure in the publication shows the median of the population simulation. As you can see in the plot below, this explains the slight difference between the plasma concentrations:

![metronidazole_pop-vs-ind](https://user-images.githubusercontent.com/26541603/43192570-2372e1ce-8ffe-11e8-80c9-66157ec09493.png)
Yet, with respect to the dose fractions eliminated, there seems to be a slight mistake in the publication, indeed. It seems I have mistakenly used an older simulation to export and plot the fractions eliminated (while the plasma concentration is correct) – my bad. However, the model has been built and scaled to pregnancy based on the simulation and the therein shown fractions eliminated. Anyway, good catch from your side!

That being said, the models in the pregnancy repository were built with an older PK-Sim version and contain the previous PK-Sim function for the hepatic clearance. Building these models from scratch with the published values will therefore result in slightly different predictions for those models where hepatic plasma clearance was used as clearance process. This applies to the models for metronidazole, ondansetron, granisetron and diazepam. The remaining seven models are not affected and building them from scratch using the published clearance values should produce the same results as those given in the uploaded PK-Sim files.

Cheers, André

**Comment by tobiasK2001** [comment]
Dear André,

thanks a lot for clearing that up also it was just a slight difference. This is very valuable indeed and now I am really fearless;-)
Cheers, Tobias

**Comment by msevestre** [comment]
Thanks @AndreDlm for investigating the issue.
Because this is not related to PK-Sim whatsoever, I am going to rename the title of this post that would be otherwise misleading :)
