### ISSUE TITLE
Irreversibel Inhibition: How to define an additional metabolization/excretion processes for the inhibitor

### ISSUE THREAD

**Issue by tobiasK2001** [Open-Systems-Pharmacology/Forum#226]
PK sim is showing this warning when a irreversible inhibition is defined:
"Please note that for the mechanism-based inactivator no clearance process is defined via the inactivation process by default. In theory, for every inactivated enzyme molecule, also one inactivator molecule is cleared; this must be separately defined by the user in form of additional metabolization/excretion processes for the inhibitor." 
I thought that the my inhibitor compound is in higher conc present than the enzyme, so that clearance by inactivated enzyme molecule would not account and ignored this. However looking and concentration in PK-sim tells me that I may be wrong... concentration of enzyme is higher in liver Intracellular than the inhibitor compound. So I gues this additioniol clrearance might play a role. Or Am I totally wrong? In any case what would be the best way to implement this additional clearance process for teh inhibitor? 
Please advise!

Thanks for your help! Tobias

**Comment by msevestre** [comment]
>In any case what would be the best way to implement this additional clearance process for teh inhibitor?

Simply define a clearance process as you would normally do in the compound screen (but for the inhibitor). Or are you asking something else?

**Comment by tobiasK2001** [comment]
OK, and the clrearance will have the same value as as the kinact for the enzyme? In this case we actually have autoinhibition. So what would we do here. Is this "additional clearance" already included if I have fitted the clearance? Or is the fitted clearance not really identifiable from the autoinhibition by irreversible inhibition?

**Comment by tobiasK2001** [comment]
Just to illustrate my question above a bit: the kinact for the enzyme affected by TDI is 4 1/h or 0.0667 1/min. If understand you right, I would take this as additional clearance for the inhibitor (or substare in this case) and I would have to add it to the fitted specficic CL of the inhibitor,  which is 11.9 1/min to give 12.05 1/min which is actually more or less the same. So can I conclude that it does not play a role here? Thanks for your suggestion!

**Comment by sfrechen** [comment]
Hi Tobias,

just to give some theoretical background.
making typical Michaelis-menten kinetic assumption, the whole process of mechanism-based inactivation is characterized by 6 parameters:
- kinact: rate constant describing maximum inactive enzyme formation rate
- K_I: concentration at which inactivation is half maximum
- k_cat: rate constant describing maximum metabolite formation rate (to a released metabolite and a still fully operating enzyme)
- K_m: Michaelis constant describing half maximum metabolic rate
- partition ratio: the ratio of the metabolite formation rate to the inactive enzyme formation rate (could be interpreted as an index of the efficacy of an inactivator)
- K_i: competitive inhibition constant (dissociation constant).
Let's assume a single binding site at the enzyme. In that case, we have K_I = K_m = K_i.

Regarding your question, I think the "partition partio" may help you. If your inactivaor hits the enzyme, two things are possible: (1) "normal" metabolization to an (circulating) oxidative metabolite keeping the enzyme alive or (2) formation of a quasi-irreversible complex with the enzyme. The smaller the partition ratio, the higher the probability of the second option.

Since it really depends which kind of in vitro parameters for your inactivator you want to use, you as user are responsible to take of correct parameterization. As you noticed, PK-Sim per default does not account for any loss of inactivator when implementing the MBI process. One reason is that you may want to use HLM kinetics from a depletion experiment to parameterize the clearance of your inactivator. If PK-Sim automatically included the MBI as a clearance process, you would need to substract that rate from the depletion rate (which is somewhat not really elegant). Therefore, the other solution of giving a warning is implemented. In case you want to include the clearance part resulting from MBI, just use k_inact as k_cat and K_I as K_m.
Hope that helps.

**Comment by tobiasK2001** [comment]
Hi Sebastian,

thanks for jumping in. However, I didn't use the typical Michaelis-menten kinetic assumption for the whole process of mechanism-based inactivation. Indeed I tried a rather simplified approach... mabye oversimplified, but I am not sure if the data is rich enough to inform 6 parameters. To give a bit more background to the approach used. I tried to fit a linear clearance (enzyme specific clearance) process to single dose iv data (no clear dose dependency visible here) and uses the mechanism based inhibition as TDI to explain the not dose linear accumulation after multiple IV and po doses  as autoinhibition. IVIVE from in vitro was not possible.  For the TDI  we have some data for K_I, and kinact from literature. So I wounder if it is possible to just use them and either:
add the k_cat as "additional clearance" to the fitted CL/spec
just ignore it as the fitted clearnance takes already the "additional clearance" into account as we have autoinhibition here. In any case the the k_cat as "additional clearance" seems to be rather small compared to the overall clearance of the inactivator and substrate. So maybe it does not play a role and may question was rather trivial.
Maybe it is a bit hard to discuss this without haveing the discrete example, however I cannot disclose here more. Did I make my problem clear enough?

Best, Tobias

**Comment by StephanSchaller** [comment]
Technically, the "additional clearance" by TDI (autoinhibition) changes over time, but if it (kinact used as k_cat) is rather small compared to your overall clearance, then you can indeed ignore it as a separate process and just go with the fitted clearance. This is also what @sfrechen meant by

> One reason is that you may want to use HLM kinetics from a depletion experiment to parameterize the clearance of your inactivator. If PK-Sim automatically included the MBI as a clearance process, you would need to substract that rate from the depletion rate (which is somewhat not really elegant).

**Comment by tobiasK2001** [comment]
Hi Stephan,

thanks for clearing that up. I was indeed a bit unsure if I got Sebsatian right here :-)

**Comment by tobiasK2001** [comment]
I think everything is clear now. Probably the explanition in the Manaul might be a bit expanded. I will create a feature request for this
