### ISSUE TITLE
PBPK - Aldehyde Oxydase / CYP3A4 - model predicts trough very poorly...

### ISSUE THREAD

**Issue by MTHuisman** [Open-Systems-Pharmacology/Forum#228]
Dear PK-Simmers,

For an oral small molecule compound with very high solubility at pH < 2-3 and very poor solubility at pH >3, I’m building a PBPK model. Naturally, the ideal workflow would have been to start with modeling IV, but I don’t have these data. 

Its permeability is high. Metabolism is mainly through Aldehyde Oxidase (AO) and a minor CYP(3A4?) component. There’s no in vitro clearance data available, neither human IV data. Metabolism is expected to be extensive, leading to 3 major metabolites (1 through AO, 2 through CYP)
When running the model ‘bottom-up’ (thus based on all available PhysChem properties etc), the prediction versus observed data is pretty good for the absorption phase and Cmax/Tmax are accurately predicted. However, the model predicts ‘a plateau’ with a certain plasma concentration (even at 24h), whereas the observed data clearly shows less than a few ng/mL at 24h. Does this suggest that the model expects a slow uptake throughout the GI-tract?

Next, I started with a parameter identification, and selected the following parameters: Lipophilicity, Specific intestinal permeability, Intestinal Permeability (transcellular), Solubility in Duodenum, Solubility in Upper Jejunum, specific clearance by CYP3A4 and AO, reference concentration of CYP3A4 and AO. I also tried subsets of these parameters to attempt a better prediction. I also added ‘weight’ to the T=24h timepoints, to force the clearance component. That leads to a model in which Cmax is underpredicted... 
When I tried to optimize the parameters with physiologically non-relevant ranges, the model becomes a bit more accurate, but that’s not the purpose of PBPK-modelling...

Would you agree that I’m missing a critical component here? If so, what could it be? What else could I try?

Any suggestions or help, would be greatly appreciated!

Kind regards,
Maarten

**Comment by Aedginto** [comment]
Hi Maarten,
Certainly much more difficult in the absence of IV data. Since you have no in vitro CL information, CL will require optimization. AO is found in many tissues. Did you find it in the gene database and use that information for relative concentrations in the different tissues? Do you have a good pH dependent solubility profile? For a drug like this, getting the solubility profile right is going to be very important. 

When you do optimization, make sure that the parameters that you are optimizing are uniquely identifiable. As such, specific CL and ref conc are multiplied in the equation to get CL and therefore there is no unique solution to this problem. Only optimize one CL parameter (either AO spec CL or AO ref conc) and not at the same time as another CL parameter (e.g. CYP3A4 CL). Clearances are additive. With respect to distribution, do you have any IV data in preclinical species? If so, build a model and test lipophilicity in that model and then, once reasonable, move to humans. While this isn't perfect, it gives you a good indication of how reasonable your lipo value (and Kp algorithm) performs. Lipo, intestinal perm and solubility are not uniquely identifiable (in many cases) and optimizing all of them together will give you nothing very useful. Also, if you are going to optimize permeability, choose only one...either specific or the other....one is based on the other so they are essentially the same. 

Do you have dose escalation data? Is it non-linear (I suspect it might be)? Optimization of solubility in the presence of non-linear oral kinetics can sometimes work out...again, make sure everything you are optimizing at the same time is unique. 

Good luck!
Andrea

**Comment by Aedginto** [comment]
Once you have lipo figured out, you can optimize a CL process and the solubility (probably by using the fold change in solubility per unit pH change) profile. I would not change solubility per intestinal segment as this is less justifiable than altering an in vitro pH - sol profile for all segments. Optimize all doses at the same time...that's the only way you are going to know if you got the mechanism right. 
Andrea:-)
