### ISSUE TITLE
Fraction unbound in interstitial space larger than 1 for large molecule model.

### ISSUE THREAD

**Issue by prvmalik** [Open-Systems-Pharmacology/Forum#242]
[Calculation of the partition coefficient between interstitial space and plasma in PK.docx](https://github.com/Open-Systems-Pharmacology/Forum/files/2511697/Calculation.of.the.partition.coefficient.between.interstitial.space.and.plasma.in.PK.docx)

See document attached.

Can anyone explain why the fraction unbound in interstitial space is calculated as 1.04?  Does this make physiologic sense?  Should we rather use 1.0?

**Comment by tobiasK2001** [comment]
Dear Paul,

it appears to me that you maybe are using the wrong model. The approach you refer in your Word doc is the Schmitt distribution model, which is for "organic chemicals" (as Walter writes so nice and clear in his first sentence of the abstract). For large molecule were you assume a fu plasma = 1 other processe are relevant for distribution compared to the SMOLs  and thus a different Submodel has to be used in the OSP. Please read here for more infos:
https://link.springer.com/article/10.1007/s10928-017-9559-4
Best, Tobias

**Comment by Christoph27** [comment]
Dear Tobias,
yes, for large molecules fu in plasma is usually assumed to be 1. But since the model for large molecules is an extension of the small molecule model the same equation is used to calculate the partition coefficient between interstitial space and plasma of the organs (K_iv). Thus, with fu in plasma = 1, a partition coefficient of K_iv = 0.96 results (for the small molecule model as well as the large molecule model) which is Paul referring to. 

Dear Paul,
For an interpretation I would see it as partition coefficient (and not as fraction unbound >1). Then such a value indicates, that the effective (not physical) volume fraction accessible for distribution is slightly smaller in the interstitial space than in plasma due components into which the drug does not partition into. Note, that only water and protein is considered in the derivation of the equation, cf. the paper by Walter Schmitt cited in the documentation. I think with the values used for the fractions of water and the protein ratio plasma/interstitial space, the sum of the fraction of water and the fraction of protein is implicitly smaller than 1. Thus there is a third (unspecified) component into which the drug cannot distribute. With that it should be possible to have a K_iv = 0.96. 
I would stick to this value since the lymph and recirculation flows of the protein model were fitted using this partition coefficient.

**Comment by prvmalik** [comment]
Thanks for the explanation guys
