### ISSUE TITLE
Sensitivity analysis on CL or V

### ISSUE THREAD

**Issue by flyhighyj** [Open-Systems-Pharmacology/Forum#283]
Hi folks,

I performed the sensitivity analysis on CL/F and V for a pediatric PBPK model (for a small molecule) to find important input parameters that affect CL prediction. 
As a result, fat and muscle volumes were high in infants. This doesn't make sense as fat and muscle volumes do not affect the clearance. 
When I doubled the fat volume, the total body weight increased. Therefore, CL/F (mL/min/kg) decreased. 

Wouldn't it be more accurate to use absolute clearance (e.g. mL/min) in the sensitivity analysis to remove the effect of weight?

**Comment by vbalbas** [comment]
Hi, 

It happened to me in the past. And I have been advised to look at the dose. Was the dose weight normalized (mg/kg) and did you look at total plasma CL? If so, increasing the fat volume will decrease the dose, and therefore the AUC and as consequence, you will see an increase in CL (but it is a dose effect and not a CL effect because total plasma CL is derived from AUC). 

Violeta

**Comment by msevestre** [comment]
Closing. Please reopen if you need more help
