### ISSUE TITLE
Subcutaneous dosing in PK-Sim

### ISSUE THREAD

**Issue by Keyur-UTHSC** [Open-Systems-Pharmacology/Forum#296]
Hi,
I am working on preclinical iv and subcutaneous PK data of a small molecule and am trying to do PBPK modeling of the same but I am unable to find subcutaneous dosing in PK-Sim. My only question is how to do subcutaneous dosing in PK-Sim. I would really appreciate the help.

Thanks,
Keyur

**Comment by StephanSchaller** [comment]
Hi Keyur,

When creating an Application, you can select "User Defined":
![image](https://user-images.githubusercontent.com/25477643/54934432-cab54000-4f1e-11e9-8815-77937a628e7d.png)

Once Selected, choose either Fat, Skin or maybe Muscle as "Target Organ" and then "Interstitial" as "Target Compartment":
![image](https://user-images.githubusercontent.com/25477643/54934543-fa644800-4f1e-11e9-9aa2-70ced93afe4e.png)

You need then define a "Release Function" as a formulation for the Application. Use Dissolved.

If you want a special release function, select "Plasma" instead of "Interstitial" as  "Target Compartment" and define e.g. a first order absorption or a Weibull function for your formulation.

Hope this helps,
Stephan

**Comment by LkKov** [comment]
@StephanSchaller 
Thank you for your comment since I had a similar issue. However, I tried, as you stated, to combine a User Defined administration protocoll (selected skin as target compartment and plasma) with a Weibull function and the combination of the administration with neither a Weibull nor Lint80 or Particle Dissolution formulation was possible (only Zero Order, First Order, Dissolved worked). Is there a possibility to use a Weibull somehow with user defined application and skin as the target compartment?

Thank you very much in advance!

Best regards,
Lukas

**Comment by msevestre** [comment]
see https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/1169. 
IF this gets enough interest, we'll implement it. Please upvote the request :)

**Comment by StephanSchaller** [comment]
Even though closed, a note: the "Table" can be used to mimick customized (e.g. delayed) absorption.

Particle Dissolution is another story and not easily adaptable, here.

**Comment by Keyur-UTHSC** [comment]
Thanks @StephanSchaller for the help!
@msevestre It would be great to see subcutaneous dosing in the simple protocol. Also, I am unable to define in the advance protocol while using a user defined administration. I am trying to do thrice a week and twice a week dosing. Thanks again!

Regards,
Keyur

**Comment by StephanSchaller** [comment]
> I am unable to define in the advance protocol while using a user defined administration

Sth. we might be working on. See [here](https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/1170).
