### ISSUE TITLE
Define partition coefficient (int/water) when adding a new compartment

### ISSUE THREAD

**Issue by thanghodn** [Open-Systems-Pharmacology/Forum#302]
Hi,
 I am working on the workflow to create a tumor compartment using this workflow:
https://github.com/Open-Systems-Pharmacology/MoBi/issues/1
I got stuck at step 9. I tried to follow this thread but could not find the partition coefficients  in the molecular properties:
https://github.com/Open-Systems-Pharmacology/Forum/issues/46

Could you please let me know what I am missing?
[CD_072_adding_tumorApril_1_2019.zip](https://github.com/Open-Systems-Pharmacology/Forum/files/3045625/CD_072_adding_tumorApril_1_2019.zip)

**Comment by StephanSchaller** [comment]
Are you working with a small molecule or protein model?

**Comment by StephanSchaller** [comment]
This is from a ADC/Tumor Example:


The partition coefficient (interstitial/water) cannot be generated automatically for the new organ since the neighborhood plasma – interstitial space has changed (re-named) when loading the PKML file. It has thus to be defined explicitly in the neighborhood of Tumor|Interstitial and Tumor|Intracellular.  

1. Define the parameter: Remain in the Spatial Structure Building Block, change to “Tree”-view, scroll down to Neighborhoods and navigate (again scroll down to almost the end) to Tumor_int_Tumor_cell  MoleculeProperties  Parameters and click button: “Add parameter”	
![image](https://user-images.githubusercontent.com/25477643/55592216-198d8180-5738-11e9-897f-430493180ec5.png)

2. Define the new parameter exactly as shown below:	
![image](https://user-images.githubusercontent.com/25477643/55592237-2ad68e00-5738-11e9-9d7c-1050fbd729a5.png)
a.	Name the parameter “Partition coefficient (interstitial/water)”
b.	Select Formula type: “Formula (an explicit formula)”
c.	To define a new formula, click the button “+ Add Formula” to the very right of the window and name the new formula: “PARAM_K_Water_INT_Tumor”
d.	Where you can see the error mark (red “x”), enter the formula string “fu/K_int_pls”
e.	From the “Possible Referenced Objects” tree, drag & drop the two required parameters into the alias list. The fist parameter, “Fraction unbound”, can be found under “Mouse ADC i.v. 0.3 mg/kg with Tox|ADC|Fraction unbound (plasma)”. Re-name the generated alias “Fraction_unbound__plasma_” to “fu”.
f.	The parameter “Partition coefficient (interstitial/water)” should be generated for each molecule in the simulation, and the variables within the formula should reference the values of the parameters in the respective molecule. For this, the generated path “ADC|Fraction unbound (plasma)” must be changed to a generic form “MOLECULE|Fraction unbound (plasma)” (see screenshot above).
g.	 Add the second parameter “Mouse ADC i.v. 0.3 mg/kg with Tox| Neighborhoods|Tumor_pls_Tumor_int|ADC|Partition coefficient (interstitial/plasma)” to the “Alias”-list and re-name the alias to  “K_int_pls”. Replace “ADC” in the “Path” to the generic “MOLECULE”.
h.	Click “OK” to create the parameter.

I hope this helps,
Stephan

**Comment by msevestre** [comment]
@thanghodn Yeah this is a quite confusion step in the workflow that we **have to** improve.

Why is this required? This parameter is generated automatically for all int-cell neighborhoods
![image](https://user-images.githubusercontent.com/1041237/55592156-9eab7300-5705-11e9-9ef6-d18efa8f6ed4.png)

However your new neighborhoods tumor_int_tumor_cell is unknown from the system. Therefor the par meter is not added automatically  and you need to add it by hand

1. in the spatial structure, go to the neighborhood `Tumor_int_Tumor_cell` and select the MoleculeProperties
2. Add a new parameter called Partition coefficient (interstitial/water) with the formula fu/K_int_pls 

- fu is a reference to the MOLECULE fraction unbound with path `MOLECULE|Fraction unbound (plasma)`
- K_int_pls is a reference to the `Partition coefficient (intracellular/plasma)`  with path `..|Partition coefficient (intracellular/plasma)`
Check the definition of the `Partition coefficient (intracellular/water)` parameter formula to see what I mean

After that, you should be able to create your simulation


Hope that helps,

Michael

**Comment by msevestre** [comment]
@StephanSchaller  Are those documents available somewhere online?

**Comment by StephanSchaller** [comment]
> @StephanSchaller Are those documents available somewhere online?

There have been repositories from Workshops pre-2018. Not sure if this topic was covered.
But it would make sense to have a repository of a collection of these.

--> OSP MT Discussion

**Comment by thanghodn** [comment]
Thank you both, 
I will try to follow these steps.
Thang

**Comment by thanghodn** [comment]
Hi,
 I was able to make the simulation run. However, look like I am still missing something basing on the simulation results. The drug is clearing a lot faster than before adding the tumor compartment. And there are warnings.  Look like I am still missing something.

Is there another step I should account for?

One more  question: in term of relative expression and relative expression (normalized), if the expression in the tumor is higher than reference concentration. I would define relative expression to be >1 (i.e 2)  and relative expression (normalized)>1. Is this correct?

I attached the model up to date. Please let me know if I should create another thread instead.
Thang
[CD_072_adding_tumorApril_1_2019.zip](https://github.com/Open-Systems-Pharmacology/Forum/files/3052317/CD_072_adding_tumorApril_1_2019.zip)

**Comment by AndreDlm** [comment]
@msevestre we have published a detailed guidance for small molecules as supplement to [this article](https://ascpt.onlinelibrary.wiley.com/doi/abs/10.1002/psp4.12300%4010.1002/%28ISSN%292163-8306.PBPKModeling). Maybe the pdf file could be re-used; I still have the ppt file in case adjustments are necessary.

**Comment by msevestre** [comment]
@msevestre Yes! A dedicated place to put the latest training material would be good. That way we could always refer to it
Maybe even better: having such workflow such as adding a tumor etc.. as FAQ so that users can also contribute. To discuss
