### ISSUE TITLE
IVIVE total hepatic clearance definitions

### ISSUE THREAD

**Issue by PriKalra** [Open-Systems-Pharmacology/Forum#306]
Dear All, 

I have read through the OSPSuite definitions and the stimulating discussions in the threads #125, #176 and #177.  However, I would like to have insights on the situation I have w.r.t. the available data and a reconfirmation as to my implementation is correct or needs reconsideration. 

In my case, for the compounds, we do not have the knowledge on the metabolizing enzymes.  The only data that I have w.r.t. metabolism is total clearance (one of the either, depending on the compound) via:
 S9 : intrinsic clearance in S9 subfraction (µl/min/mg protein)
Microsomes: intrinsic clearance microsome subcellular fraction (µl/min/mg protein)
 Hepatocytes:  µl/min/10^6 cells

Moreover, in any of the cases, I do not have information on the t1/2 of the assay or measuring time.  

1. Therefore, in such a situation, how do I differentiate as to which process type should I use among the highlighted? 
So far, I have used `residual fraction` to define the clearances
( In vitro hepatocyte residual fraction for Hepatocytes 
and In vitro liver microsomes residual fraction for Microsomes and S9 subfractions) where I have calculated the value of `Specific clearance` from the data.  Am I taking the correct approach? Should I be vary of anything else?

 
![image](https://user-images.githubusercontent.com/13007976/55788143-112aa300-5ab8-11e9-8a3a-d759704e3ff2.png)

Example for hepatocytes where i converted the clearance to compute specific clearance (`µl/min/10^6 cells*hepatocellularity number * liver density= 1/min` ): 
![image](https://user-images.githubusercontent.com/13007976/55788627-f147af00-5ab8-11e9-8a68-a13c70a441ba.png)

Thanks and best, 
Priyata

**Comment by HenrikCordes** [comment]
Dear @PriKalra,

sorry for the late response.  Upfront my understanding of the different origins of your hepatic clearance:

> S9 : intrinsic clearance in S9 subfraction (µl/min/mg protein)

S9 fraction contains microsomes & cytosol and therefore give access to both phase I and phase II enzymes.

> Microsomes: intrinsic clearance microsome subcellular fraction (µl/min/mg protein)

Microsomes are mostly used to investigate phase I enzymes activity.

> Hepatocytes: µl/min/10^6 cells

Hepatocytes profile all processes by both phase I and phase II enzymes as well as potential transporter activity
For all of the above experimental settings it is important to consider which co-factors have been supplied, since they determine phase I and II enzyme activity. 

Also be aware that depending on the experiment, different serum concentrations (0-50%) can be used which can have an impact on the the Fraction unbound (assay) parameter. Same goes for the used number of cells.

> Moreover, in any of the cases, I do not have information on the t1/2 of the assay or measuring time.
> 
> 1. Therefore, in such a situation, how do I differentiate as to which process type should I use among the highlighted?
>  So far, I have used residual fraction to define the clearances ( In vitro hepatocyte residual fraction for Hepatocytes and In vitro liver microsomes residual fraction for Microsomes and S9 subfractions) where I have calculated the value of Specific clearance from the data. Am I taking the correct approach? Should I be vary of anything else?

Why would you use the residual fraction instead of half-life?
If I understood you correctly, you would have in addition to the unknown measurement time the unknown residual fraction. 

If you have information which cell concentration was used, you could re-estimate the half-life of the experiments:
The formula for estimating the Cl would be as follows:
CL [ml/min/kg BW] = 0.693 * Hepatocellularity [cells / g liver] * 
                          Liver scaling factor [g liver / kg BW] * 
                          incubation volume [mL]  / t(1/2) [min] * Number of cells in assay [cells]

where the  incubation volume [ ml] /  Number of cells in assay [N] = Cell density ^-1 [cells/ml]
Therefore the half-live can be estimated as: 

t(1/2) [min] = 0.693 * Hepatocellularity [cells / g liver] * Liver scaling factor [g liver / kg BW] *  / CL [ml/min/kg BW]   * cell denisty^-1  [cells/ml]

,respectively:
t(1/2) [min] = 0.693 *  / CL [µl/min/cells]   * cell denisty^-1  [cells/µl]

Does this make sense? 

Kind regards,
Henrik

**Comment by PriKalra** [comment]
Dear Henrik, 

Thank you for the response. In the end I used the t1/2 equation, however, I am rather new to the IVIVE approach and hence just used the default values of PKSim for the same. I will now try to do a calculation of the t1/2 and implement it in my model. Thank you. 

In continuation to this, I have an observation that I am not clearly able to explain due to my limited background in oral absorption processes. I have an IVIVE dose (50 mg/kg oral dose) as explained in [Fabian et al. ](https://link.springer.com/article/10.1007/s00204-018-2372-z) and I am modelling all the compounds mentioned in this publication in PKsim.  In most of my compounds I observe an oscillatory (damped or persistent) behaviour in the starting 10 hours of the simulation. I do not have much idea where these might stem from! So I am a little lost with the analysis.
![image](https://user-images.githubusercontent.com/13007976/58239737-edf74280-7d49-11e9-9af3-8104b35ccc26.png)

Any comments on the same, and what other aspects I could observe would be highly appreciated

**Comment by tobiasK2001** [comment]
Dear Priyata,
additional to the excellent comments of Henrik please let me point out that default value for "fraction unbound assay = 0.1" used in PK-sim is totally arbitrary. By the sam time it has a major impact on your calculated specific clearance. So unless you have measured data for it, I would use the calculated fraction unbound you get for the microsomes t1/2 in PK-sim and just copy paste that to your hepatocyte t1/2 input. This one is based on your compounds lipophilicity and the fraction unbound in plasma measured. Although it is optimized for the microsomal assay it might approximativ reflect the value in your hepatocyte assay.
![image](https://user-images.githubusercontent.com/25585248/58240837-141de200-7d4c-11e9-8719-3da4a3ff3fa8.png)

Regarding you other problem, it looks on the first glance that you have a permeability limitation for fraction absorbed. However, as you have quite a high dose you might also take a look at the fraction dissolved to lumen. Sure it would help to have a look in your PK-sim file. And maybe it could be beneficial to open a special request for this in order to deconvolute the issues ;-)

Best, Tobias

**Comment by HenrikCordes** [comment]
Daer @PriKalra, 

As @tobiasK2001 pointed out the fraction unbound strongly impacts the specific clearance and is especially important if the experimental buffer contains serum and therefore plasma protein that binds the drug. For hepatocyte assays, common serum portions are 50, 10, 5 and 0 % serum. That applies to your data is probably hidden in the M&M sections for your given hepatocyte CL values. 

For the fraction unbound, one could think of a scaling step with the serum fraction used in the hepatocyte assay (fu* fraction serum in media) to account for a somewhat "diluted" serum in the assay. 

Does this make sense? 

Kind regards,
Henrik

PS: As for your second question I agree with @tobiasK2001 that you probably have a permeability limitation. If you take a look at you PK & absorption profile you will see an "event" @ about 8h which correlates with the intestinal transit time in the rat model in PK-Sim. I just struggled with the same issue in one of my projects ;-)

**Comment by PriKalra** [comment]
Thank you so much for the comments @HenrikCordes and @tobiasK2001. I will look up  more into the details of the values and reimplement them correctly. I will also initiate a new thread for the second question because this is a very new topic for me and sometimes I get stuck with what parameter I should look at and how to proceed in general. :)

**Comment by PriKalra** [comment]
Hello both, 

I have opened a new issue #333 . Your comments and guidance would be much appreciated. :)
