### ISSUE TITLE
BCS 2 weak base - precipitation kinetics in the lumen

### ISSUE THREAD

**Issue by RodrigoCristofoletti** [Open-Systems-Pharmacology/Forum#309]
Dear all,

Is it possible to handle precipitation kinetics in case of BCS 2 weak bases using PK-Sim, e.g. at least as a first order process? I am aware that by treating precipitated drug as "soluble", the precipitated drug amount is added to the solid drug mass, increasing Xsolid available to dissolution. But I was wondering whether it is possible to set/handle precipitation rate constant and supersaturation directly.

Thanks in advance

All the best

Rodrigo

**Comment by msevestre** [comment]
@RodrigoCristofoletti There is a new feature "supersaturation" that will be implemented as part of the upcoming release. I am not sure if this is what you need. Please check it out here: https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/1100

Cheers,
Michael

**Comment by Yuri05** [comment]
>But I was wondering whether it is possible to set/handle precipitation rate constant

In PK-Sim the only way of modification of dissolution/precipitation kinetics is via it's parameters.
Which (for a particles dissolution) can be found in the _advanced_ compound parameters:
![grafik](https://user-images.githubusercontent.com/25061876/56282501-a7417780-610f-11e9-9f28-420da1206e7d.png)

If you would like to change the kinetics itself (to first order or whatever), you can do it only via MoBi:
* export simulation to MoBi
* in MoBi, open Events-building block and navigate to your particles dissolution application
* select one of the dissolution processes `ParticlesDrugReleaseXXX `(e.g. `ParticlesDrugReleaseCaecum`)
* navigate to the parameters tab and select `Release rate of the tablet `parameter. This parameter describes dissolution kinetics in the given GI segment
* change the formula according to you wish (first order or whatever)
  * this must be done **only once** (only for one GI segment), because the formula is shared between all segments
  * :exclamation: in case `Treat precipitated drug as` was set to `Insoluble`: adjustment of `Precipitation rate of the tablet` parameter is required as well :exclamation:
![grafik](https://user-images.githubusercontent.com/25061876/56283002-d1476980-6110-11e9-8a4e-fe4b085bf773.png)

**Comment by msevestre** [comment]
Closing. Please reopen if you need more help
