### ISSUE TITLE
Setting up the clearance values

### ISSUE THREAD

**Issue by vaimun** [Open-Systems-Pharmacology/Forum#31]
I am trying to set up the clearance for a drug.  I am using literature results mentioning liver and intestinal S9 clearance values in microliter/min/mg along with additional systemic clearance values.   As this clearance values are not enzyme specific, how can include this clearance values in PK SIM or do I need to set up the reaction in MoBi. 

My second question is metabolite of this compound has 10 fold higher concentration in liver but no transporter kinetics is reported for this compound.  I am not sure how to approach this using PK Sim.

Thanks in advance for your suggestions and help !

**Comment by JanSchlender** [comment]
In order to implement an unspecific clearance, you need to define the clearance process in the ADME tab of the Compound. Please also have a look at the ADME section of the manual (15.1.2).
I would split your setting in three different implementations:

1.	Unspecific liver clearance
Add a “Total Hepatic Clearance” and define it as “Liver Plasma Clearance”. Define the clearance rate in the “Plasma Clearance” field and NOT in the “Specific Clearance”. Is the clearance value normalized to a cell culture? Then you need to select another hepatocytes or microsomes as the process type.

2.	Unspecific intestinal clearance
There are two options for this. You may use the biliary clearance since this elimination route ends in the intestine. In case you can clearly rule out a biliary process and you assume something like a transcellular elimination into the intestinal lumen, you need to define this as a transport process. Therefore you need to add a Clearance rate (“Transporter Proteins” in the aforementioned ADME tab) and you need to define a Transporter in the Individual. Here, use a dummy process. (Create Individual ->Expression tab ->Transporter Proteins -> Add Transporter Protein…(Default)). Then localize this process by adding the expression. Please have in mind, that this process should be well-conceived since it simultaneously decreases your bioavailability. 

3.	Additional systemic clearance
Since this is a physiological model, a simple systemic clearance is not adequate for such an approach. At least you need to know the route of this clearance. Most common would be a renal or hepatic elimination which is implemented as shown above

Could you please add another issue for the question regarding hepatic concentrations. Then it will be easier for other users to find similar issues.
