### ISSUE TITLE
Permeability Calculation & Peff

### ISSUE THREAD

**Issue by RobinPharma** [Open-Systems-Pharmacology/Forum#319]
Hello OSP Forum !

I have been wondering how the permeability is calculated in PK-SIM. 
The paper mentionned in the source of intestincal permeability in PK-SIM is displaying a calculation called Pint
![relate to peff](https://user-images.githubusercontent.com/47522217/57296330-0cfca000-70cd-11e9-99fc-f73aba82746c.PNG)

I have some questions concerning this calculation.
First, how does it relate to Peff in gastroPLUS, if it relates. I have never seen such a calculation therefore I'd be interested to know if there is a link between the two.

Second, it seems like to calculate this Pint value, it has to take into account the LogMA of the molecule. My problem is I've never used MA values before, I'm usually limited to logP&Ds.  
How precise is a logMA value, what usual difference will we get from MA and LogD ( will the values be similar, or start to shift for non neutral compounds ? )

I'm getting out of my field therefore if I'm missing obvious notions don't hesitate to bring the basics on the table !

Thank you very much

**Comment by AndreDlm** [comment]
Hi @RobinPharma ,

as far as I know, *P<sub>eff</sub>* in GastroPlus is roughly equivalent to *P<sub>int</sub>* although  the former is typically estimated from Caco-2 permeability data using the permeability converter utility in GastroPlus. 

In PK-Sim, the logMA value is the lipophilicity value defined in the molecule building block. Most often, log P is used here, but if membrane affinity has been measured in vitro, it is preferable to use this value for lipophilicity instead of log P. 

The lipophilicity value is constant over the pH (i.e. it is independent of the charge of a molecule), but many parameters that are calculated based on lipophilicity account for different charge states of the molecule. 
For example, the parameter `drug absorption rate (lumen to mucosa)` is, amongst others, a product of the intestinal permeability and a factor accounting for the charge of the molecule as shown in the equation below:

![Untitled](https://user-images.githubusercontent.com/26541603/57299900-fa3a9900-70d5-11e9-9003-600bdbf8e0e8.jpg)

You can find this equation after exporting your PK-Sim model to MoBi and navigating in the spatial structure to the Neighborhoods --> Lumen_{intestinal segment}_cell --> Molecule properties --> Parameters --> `drug absorption rate (lumen to mucosa)`

I hope this helps!
André

**Comment by Aedginto** [comment]
Hi there,
Pint is indeed a fun topic! I had a lengthy discussion about Pint in the following post from last year (#23). Pint/Papp/Peff are not directly transferable between mechanistic models of absorption. Calibration of in vitro measures of Pint to a unique model structure is required (as Andre has stated that the use of the permeability converter for GastroPlus allows for calibration between in vitro measures of permeability and the model parameter that will give a good 'fit'). This is an optimization and the outcome of an optimization is dependent on model structure, parameterization of all other relevant inputs, and the data used for fitting. 
Take care,
Andrea

**Comment by tobiasK2001** [comment]
Dear all, 
thanks for this interesting posts. Indeed the use of Pint in mechanistic models seems to be a constant fun topic. 
Would be nice to see what formula GastroPlus is using. Is it somewhere visible like in the OSPS?

@RobinPharma: additional to the very good comments from Andre regarding LoMA:
It is a charming but not so well known concept.  It seems to very useful not just only for estimating permeability but also for fu and distribution of highly lipophilic compounds:
https://www.ncbi.nlm.nih.gov/pubmed/11785701

https://www.ncbi.nlm.nih.gov/pubmed/14999720

Hope you might find this usefull.

Best Tobias

**Comment by AndreDlm** [comment]
Hi @RobinPharma ,

in addition to the excellent comments by Andrea and Tobias, please note that per default the *P<sub>int</sub> scalefactor* is inactivated. In PK-Sim, you can activate it in the simulation by setting the value to 1: 
![Untitled](https://user-images.githubusercontent.com/26541603/57439855-304b5a80-7247-11e9-8b1f-1c39a5b4d5b4.jpg)

You may also have a look at the related discussion on this topic here: [#607](https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/607)

All the best,
André

**Comment by RobinPharma** [comment]
Dear @AndreDlm @tobiasK2001 @Aedginto ,

Thank you very much for your help, I will report here later if I can add any usefull information for someone reading this thread.

Kind regards

Robin

**Comment by msevestre** [comment]
Closing. Please reopen if you need more help
