### ISSUE TITLE
Transfering data from pk-sim into excel

### ISSUE THREAD

**Issue by moulirc** [Open-Systems-Pharmacology/Forum#32]
Also one final question - when I am exporting the con - time profile to Excel, the values are expressed in [µmol/l], in spite of changing the values.
Thanks in advance

**Comment by msevestre** [comment]
@moulirc 
I suspect that you export the data using a right click on the simulation tree => Export To Excel? This will export all available data in the preferred units (Utility=> Managed User/Project Display Units)

In order to export the data displayed on a plot, you can simply right click on the plot and select `Export To Excel`. This will export all visible data to Excel using the units selected in the plot. 

![image](https://user-images.githubusercontent.com/1041237/27440168-f0bf7670-5737-11e7-891c-444eaeb93114.png)


Does this help?

Cheers

**Comment by PavelBal** [comment]
First, these two features (Export to excel from the chart and from simulation) should be called differently, as it is confusing having the same name for different behaviours.

Second, 

> This will export all visible data to Excel using the units selected in the plot.

is not always true. Example:
1) Open the "Aciclovir"-project from the PK-Sim example folder.
2) Open the first simulation (IV -> Laskin_1982_GroupA). Use see a chart with µmol/l as y-axis dimension.
3) Right click on chart and select "Export to excel". Exported units are µg/ml!!!

From my point of view, it is a bug.

**Comment by moulirc** [comment]
![image](https://user-images.githubusercontent.com/27323536/27473767-a13328ec-5843-11e7-930e-f65298cbc5e5.png)
[sim-Results.xlsx](https://github.com/Open-Systems-Pharmacology/Forum/files/1097223/sim-Results.xlsx)


Hi,
Please find attached the file and the image. 
On exporting to excel the values are in µmol/l (simulated parameters).

I agree to the Pavel's comment on this.

Thanks 
mouli

**Comment by msevestre** [comment]
@all: Agreed. If the unit is not what is set in the chart, this is a bug. I am surprised that it was not reported before. oh well

Regarding rename of feature: I think the context is clear (It's like Copy, Paste, Print etc.. The context where the action is triggered dictates what is being copied, printed etc..).

**Comment by msevestre** [comment]
I have created https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/230

**Comment by msevestre** [comment]
@PavelBal Actually I think you are looking at the wrong excel sheet. This example has curves for Observed Data AND Calculated curves and one sheet is created per repository.

**Comment by msevestre** [comment]
issue is fixed via https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/230
