### ISSUE TITLE
How to change the units

### ISSUE THREAD

**Issue by fredsevmartins** [Open-Systems-Pharmacology/Forum#323]
Hi
Please could you help me ?

I am want to output my results  in .csv of all my subjects (see figure 1)   and access all subjects pk profile. But always I get my concentration in umol/L . How could I change that to mg/L or ng/mL.
Many thanks.
Fred

![image](https://user-images.githubusercontent.com/45317633/57845806-02c85900-77d3-11e9-85ce-25b3aa5837c7.png)

**Comment by msevestre** [comment]
@fredsevmartins 

In order to export in other units than the default units, you need first to ensure that the graph is using the units you would like to export

Then right click => export to excel

![image](https://user-images.githubusercontent.com/1041237/57872452-b7fe0f80-77d9-11e9-9338-7d5bc29277c0.png)


CSV Export is used for interprocess communication (for example export of results for further processing in Matlab or R, or import from cluster calculations etc..). By conventions, CSV files should always be in our internal unit (umol/l) 

Hope that helps,

Michael

**Comment by fredsevmartins** [comment]
Dear @msevestre many thanks. Extract data on this way only gives me  median ,5th and 95th. I would like to have PK profile of all subjects simulatates. Is it possible ?
Thanks again
Fred

**Comment by msevestre** [comment]
Oh I see. In that case no it's not possible at the moment. May I suggest to open an issue in the PKSim Repo so that we can track it there and implement it in a future release?

**Comment by fredsevmartins** [comment]
@msevestre  how could I do that?
Many thanks for your help.
Fred

**Comment by msevestre** [comment]
@fredsevmartins Create an issue [here](https://github.com/Open-Systems-Pharmacology/PK-Sim/issues) and explain that this is a feature request
