### ISSUE TITLE
absorption

### ISSUE THREAD

**Issue by RKasp** [Open-Systems-Pharmacology/Forum#325]
Dear all,
I got a question from a customer, and I am not sure if it makes sense. He asked if it is possible to reduce the compartmental absorption model implemented in PKSim to a first order absorption process or a different empirical equation. I believe he tries to compare it with simcyp, which gives you different absorption models as choice or any other NONMEM model for comparison.. Except a more cumbersome approach by reducing the absorption process or parameter settings or a dose + formula into the portal vein, I am wondering if you can suggest any quicker solution to this (a bit defeating/reducing the PBPK approach).
I am happy for any comment. Thank you.
Best regards,
Rüdiger

**Comment by Aedginto** [comment]
Administering into the portal vein with a first order process set as the ka from the popPK model will work. You could also take it to Mobi and add some equation to describe absorption as well. My question when this comes up (because it does), is what is the purpose of the PBPK model. If it's just data description, do popPK. If there is any extrapolation in the models' future, I would not minimize.

**Comment by RKasp** [comment]
Thank you, I very much agree. I just wanted to hear other thoughts and experiences.
