### ISSUE TITLE
weighting schemes in pksim

### ISSUE THREAD

**Issue by harishkaushikbugworks** [Open-Systems-Pharmacology/Forum#332]
Hello,
can we introduce weighting schemes as we do in PK modelling

Regards
Harish

**Comment by msevestre** [comment]
@harishkaushikbugworks Can you explain what you mean ?

**Comment by harishkaushikbugworks** [comment]
Naive question about introduction of weighting the concentration values with 1/Y2 pred

**Comment by msevestre** [comment]
@harishkaushikbugworks Since this is a feature request, please create an issue in the PKSim issue tracker with a `clear` description of what you would like to see.
An example, and maybe also an explanation as to why this feature would be a good addition to the suite is suggested if you want this feature to be implemented
