### ISSUE TITLE
Understanding the role of permeability and absorption processes in PKSim simulations

### ISSUE THREAD

**Issue by PriKalra** [Open-Systems-Pharmacology/Forum#333]
I have an observation that I am not clearly able to explain due to my limited background in oral absorption processes. I have an IVIVE dose (50 mg/kg oral dose) as explained in [Fabian et al.](https://link.springer.com/article/10.1007/s00204-018-2372-z) and I am modelling all the compounds mentioned in this publication in PKsim. In most of my compounds I observe an oscillatory (damped or persistent) behaviour in the starting 10 hours of the simulation.  Overall, its interesting to observe because in the 8 compartment PBTK model (as published) this is not the case (due to simplifications and linearity of the dose). Hence, it would be of interest to me to understand if certain processes drive this observation. 
![image](https://user-images.githubusercontent.com/13007976/58251797-d37e9280-7d64-11e9-94d1-287cd3d8fdac.png)

I would therefore like to have an idea of what parameters I should analyse in order to gain more understanding in this direction. Attached are the PKSim file with the presentation where I have clear differences plotted and some questions w.r.t. absorption and Papp values for the same. 
[PKSimfileandppt.zip](https://github.com/Open-Systems-Pharmacology/Forum/files/3212028/PKSimfileandppt.zip)

Thank you for your time and I am looking forward to comments. 

Best, 
Priyata

**Comment by HenrikCordes** [comment]
Dear @PriKalra,

I was just wondering if you have any experimental data on the PK side to inform if and how far off your simulations are? 

Lets take the Colchicin example. I just plotted the fraction absorbed within the PK plot. 
![image](https://user-images.githubusercontent.com/4817133/58255335-0b89d380-7d6d-11e9-8cff-901f7e6341d1.png)
As you can see the absorption ends after about 7.5h. From the total fraction (blue) we see that less than 20 % are absorbed.  So where did the rest go? 
![image](https://user-images.githubusercontent.com/4817133/58255489-691e2000-7d6d-11e9-8da3-820346c00488.png)
Apparently it went down the intestine into the feces without being absorbed. 

So the model imposes a  limited absorption, which can be driven by solubility and/or permeability of the compound (intestinal metabolism or uptake is also possible). 

Do you have experimental data to inform the permeability, solubility or intestinal metabolites (stability) ? 

Kind regards,
Henrik

**Comment by PriKalra** [comment]
Dear Henrik, 

Thank you very much for a guided reply! Its of great help to me. 

The answers to your questions:

_I was just wondering if you have any experimental data on the PK side to inform if and how far off your simulations are?_
Not for this dose, but I am now looking for in vivo dose data  to have an insight into the difference between the Cmax of the compounds and the simulation to see how far off my simulations are. (This is another question, that in such a workflow what is better to live with: Cmax/AUC or both?). However, in this work, we focus on in vivo LOELs and for Colchicine its difficult to find the LOELs. But, my next step is to have a reference model against any in vivo data and try to see how far is the model. Do you think I go in the correct direction?

_Do you have experimental data to inform the permeability, solubility or intestinal metabolites (stability) ?_

Tough luck on this aspect too, we have Papp values (experimental OR literature based for the compounds) and they were the ones used for the simulations (defined in the specific intestinal permeability).  In case if I use PKSim calculated values for permeability vs the one I have, I see huge differences in the profile of the compounds. See below:
[IVIVEDose_50mgperkg_CaCoPKSIMcalculated.pdf](https://github.com/Open-Systems-Pharmacology/Forum/files/3216177/IVIVEDose_50mgperkg_CaCoPKSIMcalculated.pdf)

With respect to this, I have followed the excellent discussion in issue #23 and I am still in the process of understanding this and I am not a 100% clear with the clearance values scaling and understanding its impact on my work. So, I am trying to approach it with the concept of uncertainity and see the fold difference when there is variability on such an input. I would be glad to know your comments on this and if this makes sense at all to go through such an approach. 

As for solubility or intestinal metabolites, we do not have that. What we want to try to achieve is a purely IVIVE approach as in the case of chemicals, unlike pharmaceuticals, data is not readily available. 


 I have a question to the second graph that you showed to me. Since I am not totally clear on the various absorption processes, I wonder, if there is a way we can analyse bilary excretion? So what I do not understand is, that there is no excretion contribution by bile? 

Thanks and regards, 
Priyata

**Comment by HenrikCordes** [comment]
Dear @PriKalra,

> what is better to live with: Cmax/AUC or both?

Well I'd say both and & the Cthrough (Cmin before next administration) is important as well ;-) 
Which of these key figures is most important is highly drug dependent and based on its mechanism of action / of toxicity. So I do not dare to choose which key figure it is, therefore I would go with all of them meaning that it is important that the "shape" of your simulations overlay with the experimental data.

> However, in this work, we focus on in vivo LOELs and for Colchicine its difficult to find the LOELs. But, my next step is to have a reference model against any in vivo data and try to see how far is the model. Do you think I go in the correct direction?

If I understand you correctly you want to establish a model for known doses, where you have experimental PK data first? 
In my opinion this is exactly the way to go here and you are on the right track! With respect to a recommended workflow (https://www.ncbi.nlm.nih.gov/pubmed/27653238) 
I would start with: i) establishing an IV model, ii) than a PO model. Why would I do this?

1.  Establishing a IV PBPK model for the different drugs, ideally for different doses helps you to identify potential non-linearities in the clearance and excretion fractions. The advantage in IV models is that you can ignore the absorption and solubility (although there can be precipitation, but lets assume this does not apply here) and can focus on the DME processes for the respective compounds
2. The IV model is than used to establish an PO model by only altering the route of administration and allowing the relevant absorption parameters (usually intestinal permeability) to change. Ideally you have PK data from different dose magnitudes (e.g. 1 & 10 mg/kg or even higher). One should be able do describe the different doses with the same permeability, if not, this is an indication that other processes such as intestinal solubility or (first pass or intestinal) metabolism become relevant with increasing dose. 


> Tough luck on this aspect too, we have Papp values (experimental OR literature based for the compounds) and they were the ones used for the simulations (defined in the specific intestinal permeability). In case if I use PKSim calculated values for permeability vs the one I have, I see huge differences in the profile of the compounds. See below:
> IVIVEDose_50mgperkg_CaCoPKSIMcalculated.pdf
> 
> With respect to this, I have followed the excellent discussion in issue #23 and I am still in the process of understanding this and I am not a 100% clear with the clearance values scaling and understanding its impact on my work. So, I am trying to approach it with the concept of uncertainity and see the fold difference when there is variability on such an input. I would be glad to know your comments on this and if this makes sense at all to go through such an approach.

As you showed in the PDF the intestinal permeability parameter can have a drastic impact on the simulated PK for PO administration, as your wrote further and was excellently discussed in #23 the experimental permeability can't be translated 1:1 in a PBPK model. Therefore again I would recommend to start with the IV model to ensure the reasonable assumptions and parameters for distribution and clearance. Than, for the PO models you can use the experimental permeabilities as starting point. 

> As for solubility or intestinal metabolites, we do not have that. What we want to try to achieve is a purely IVIVE approach as in the case of chemicals, unlike pharmaceuticals, data is not readily available.

Okay, than I would start with an assumption that intestinal metabolism does not play a major role here and for the solubility I would use the experimental values (usually in water) and go with the PK-Sim derived solubility changes depending on the compounds pKa's.

> I have a question to the second graph that you showed to me. Since I am not totally clear on the various absorption processes, I wonder, if there is a way we can analyse bilary excretion? So what I do not understand is, that there is no excretion contribution by bile?

To clearly identify excretion to the bile on should have excretion data from an IV experiment. If the compound (or one of its metabolites) appears in the feces, than it is very likely that there is a biliary excretion process involved. 
Excretion to the bile can be implemented in PK-Sim by either adding a "biliary clearance" to the compound building block:
![image](https://user-images.githubusercontent.com/4817133/58456646-01792380-8125-11e9-940e-a8755dc8fda9.png)

or by adding an apical P-gp / Efflux transport process into the liver:
![image](https://user-images.githubusercontent.com/4817133/58456714-2d94a480-8125-11e9-8c4d-5b094ade82f0.png)

However, in your case I would not recommend to include biliary excretion if you do not have the experimental support. The second graph I showed you of your simulation indicates that a large proportion (~ 75 %) of the administered drug, since it was an oral administration, is not absorbed at all and passes through the intestine into feces. Parameters that can drastically influence the absorption ware the permeability, solubility, transition time and for molecules with charged functional groups the intestinal pH. Also, as in your case unknowns such as export transporters in the intestinal epithelial layer, metabolism and compound stability (degradation by low pH in the stomach, or higher pH in the intestine) can play a role. 

However, I do recommend to keep it simple and only include additional processes if 1) you have the experimental support and/or 2) you can't describe your data with the most simple assumptions. 

I hope this helps!

Kind regards,
Henrik

**Comment by tobiasK2001** [comment]
Dear Priyata,
of course Henrik is totally right: experimental PK data are the key here to go on. Additional to his excellent comments let me illustrate this a bit further at the example for Caffeine. 
As you know, PK-sim has an inbuilt Coffeine template, which was trained with human iv and po data from different doses. CYP1A2 metabolism and intestinal permeability was fitted during model development. 
Comparing the PK-sim template to you CAF BB reveals some slight differences for logP, pKA additional to the Clearance and specific intestinal permeability inputs. As metabolism is surely species dependent it makes no sense to translated the fitted value for CYP1A2 in humans to rat here. But what about the fitted intestinal permeability? Can this be translated between species? I created a PK-sim Caffeine with your rat hepatocyte Clearance input and Caco_ExpCAF input to investigate the impact of intestinal permeability vs other changed parameters. As shown in the figure below, if the same intestinal permeability is used, the slight differences in logP and pKA do not play a role (solid and dotted line for Sim_CAF and Sim_CAF-PK-Sim_CacoExpCAF are almost identical). Whereas the fitted intestinal permeability in the PK-Sim template (dashed lines for Sim_CAF_PK-sim) shows a remarkable lower Cmax and fraction absorbed through mucosa. 
![image](https://user-images.githubusercontent.com/25585248/58490364-4cb72480-816d-11e9-94a0-3885464b8a7d.png)

[PBPK_All_Substances_BM_original_edit_tk.zip](https://github.com/Open-Systems-Pharmacology/Forum/files/3228432/PBPK_All_Substances_BM_original_edit_tk.zip)


To decide, which input for intestinal permeability would be better to use, only measured plasma concentrations in rat after po dosing can tell. 
Interestingly the fitted intestinal permeability is orders of magnitude higher than the PK-sim calculated value and the latter would lead to complete under prediction of the human data.
So for caffeine both the Caco_ExPCaf and the Human_fitted value are a great improvemnet for prediction. However, fine tuning with experimental data would be the next step.

Hope this might help you.

Best Tobias

**Comment by PriKalra** [comment]
Thank you both for the valuable comments and the help. This clarifies a lot of things for me and at the same time stems out a bit more for the IVIVE approach. I will need some time to think and then I will get back to you with my further questions. 

Best, 
Priyata

**Comment by msevestre** [comment]
Closing. Please reopen if you need more help
