### ISSUE TITLE
Compound    Plasma fraction unbound

### ISSUE THREAD

**Issue by ilanzalit** [Open-Systems-Pharmacology/Forum#348]
An opposite relation between fraction unbound   to simulated plasma level   is   observed !!   reducing the plasma  unbound increased the simulated plasma level .   Wouldn't  it  be expected to be to opposite ? !  : reducing the  plasma unbound    reduces the  simulated  plasma  level ?

**Comment by msevestre** [comment]
@ilanzalit I would strongly suggest that you look at the documentation in order to understand some of the core concepts of PK-Sim.

It is online and searchable: https://docs.open-systems-pharmacology.org/

More particularly, the section on how to select outputs can be found here
https://docs.open-systems-pharmacology.org/working-with-pk-sim/pk-sim-documentation/pk-sim-simulations#running-a-simulation-in-an-individual

Hope that helps,

**Comment by Aedginto** [comment]
Reducing the unbound fraction in plasma reduces the volume of distribution (Vss is almost directly proportional to fu_plasma). Reducing the unbound fraction also reduces the clearance of a low to moderately extract drug. Reducing the V will lead to a higher total concentration peak. Reducing CL will lead to higher concentrations throughout the curve. You are seeing what is expected.

**Comment by msevestre** [comment]
@ilanzalit Closing. Please reopen if you have more questions or concerns
