### ISSUE TITLE
Working with an existing complex model using pkml only

### ISSUE THREAD

**Issue by rexjohnrx** [Open-Systems-Pharmacology/Forum#350]
Hello,

Great piece of software. I believe I have a simple problem that is answerable by pointing me to a tutorial, but I have not found anything that would answer my question in this forum or elsewhere.

I am trying to work with a published model which was distributed on this forum here: [https://github.com/Open-Systems-Pharmacology/Forum/issues/102](url) @DanielMoj. I was happy to see it here because I was attempting to rebuild it from the associated reference, which is always a mess of troubleshooting. However, I am still unable to use the model for simple applications.

Only the pkml was given, not the PK-Sim or MoBi project files, so I am forced to work with it in MoBi (right?). **My problem is, I don't see how to simulate a simple, custom dose**. I understand this is done through the Events, but based on how I see the author's dosing Events in the building blocks, it seems that adding just a single administration is incredibly complex.

It is quite slow to even run the built in simulation on an average PC since the pkml includes >100 separate applications and I do not know how to limit those without manually deleting them 1 by 1.

Every tutorial I have seen working with existing models has been focused on adding additional compartments and other relatively complex usecases like that. I have yet to find something that walks through: "given a model, starting with a blank Event Building Block, here is how to simulate dosing."

If someone could please walk through the steps of taking the referenced pkml and adding in an oral or IV infusion application in a new Event building block, that would be incredibly valuable to me and any others trying to use (rather than modify) existing models.

**Comment by msevestre** [comment]
@rexjohnrx 

You are absolutely right. Creating an application in MoBi is a very complex task. That's why we suggest to always build it in PK-Sim, export the model and load the corresponding building block into MoBi (Event building block in that case)

## Here are the step by step instructions: 

- Go to PK-Sim and create a dummy simulation with an IV Infusion (attached here as well). Name your compound using the name in the MoBi Model (in our case `Vorinostat`)
- Save the simulation to Mobi pkml format
- Load the Event building block in MoBi (going to events=> Load Event Group Building Block). Select the simulation file. MoBi is clever enough to load the event building block used in the simulation
![image](https://user-images.githubusercontent.com/1041237/59882987-ae8c3800-9381-11e9-857f-e3a54010e93d.png)

- Create a new simulation using the newly loaded building block instead of the old, complex one
- Run the simulation. 
- Enjoy 
[User defined protocol.zip](https://github.com/Open-Systems-Pharmacology/Forum/files/3312199/User.defined.protocol.zip)

Let me know if you have any questions,

Michael

**Comment by rexjohnrx** [comment]
Michael

Awesome, that perfectly solved my issue*! I tried with an oral dose and it seemed to work well, too.

\* One problem, though. If I try to limit the plotted output to plasma concentration, and restrict my axes to 3 hours on the x-axis and 0.1-10 uM on the y-axis, I don't see any drug concentration before 1 hour (using either your IV simulation or my oral). This seems to be an error because it should theoretically be there instantly given IV bolus. For comparison, I turned on one of the PD markers and it **is** changed starting from time 0. I have tried to attach an image for reference.
![image](https://user-images.githubusercontent.com/45149006/59884445-59065a00-9386-11e9-84aa-eea99c72664f.png)

**Comment by rexjohnrx** [comment]
> Is this a problem with the model, the application addition, or simply a graphing issue? How can I see the simulated concentrations/PK data (e.g., AUC) in MoBi to determine if it is the latter?

Sorry, this seems to the Observer block, which seems to be checking every hour and a half for 6000 hours. Could this be changed easily in MoBi or does it require another dummy simulation? Thanks again!

**Comment by StephanSchaller** [comment]
This is due to the resolution of the plotted curve.

At t = 0h, concentration of Verinostat is zero. On a log scale, this is not defined, thus you do not see it. The next point the line goes through is at 1 = 1.x h and every 1.x hours thereafter.


Just change the scaling of the y-axis (double-click on the axis), or change the output resolution:

![image](https://user-images.githubusercontent.com/25477643/59887227-cc2dc180-93c2-11e9-966c-4912c2528e7f.png)

**Comment by rexjohnrx** [comment]
Thanks @StephanSchaller, luckily I did figure that out probably while you were creating your response.

My only remaining question is how to output the PK-Analysis in a MoBi simulation, like you can do in PK-Sim with this button:
![image](https://user-images.githubusercontent.com/45149006/59924364-9957ed80-9403-11e9-8eb2-0b041477cd69.png)

I know I can output to excel and perform the calculations myself, but if there is a built-in way to do it in MoBi that would be great.

**Comment by msevestre** [comment]
@rexjohnrx Nothing built it in MoBi.
However, you can export that simulation back to PKSim if you need the values (Save as pkml and load simulation in PKSim)
![image](https://user-images.githubusercontent.com/1041237/59924865-b80ab400-9404-11e9-8686-e69c68952c76.png)

**Comment by rexjohnrx** [comment]
@msevestre That's perfectly acceptable, thanks!
