### ISSUE TITLE
Application of multiple tablets

### ISSUE THREAD

**Issue by Fatima-Marok** [Open-Systems-Pharmacology/Forum#357]
Dear all,
The drug I'm working on is only available as a 150 and 500 mg tablet. Patients normally receive doses in a range of 1800-2500 mg, which means that they at least take 3 or more tablets at a time. For now I used a Weibull for the formulation, which works quite well for higher doses. We differentiated between fasted and fed.  Smaller doses of 150 -500 mg can not be well simulated with a Weibull (it works as a Solution). For now we assume a dose dependent absorption, which is also influenced by food. Would you recommend a different approach? Is there a better way to describe the intake of multiple tablets at a time?

Thank you very much,
Fatima

**Comment by HenrikCordes** [comment]
Dear @Fatima-Marok,

thank you for posting this real-life example! 

If I understand you correctly, if the compound is given in a small dose (150-500 mg), the PK can be adequately described by the "dissolution" formulation and for higher doses you need a "Weibull" formulation resulting in a delayed  absorption in order to adequately describe the absorption phase. 

I assume that you have confidence in the chosen distribution and clearance of you model. 
Thus, to my understanding the situation boils down to the question, if the formulation of the tablet(s) is the origin of the different absorption, or if it there is a non-linearity for the high dose.

You could consider the following:
The solubility of the compound: Is your compound completely soluble at the highest dose?
The permeability could be limiting, do you have information regarding the permeability of the compound? (Caco2 or MDCK)
Is the compound a substrate for an efflux transporter? (P-gb, BRCP, MRP2/4) 

It would be great if you could provide the community with your model, either the resulting PK plots or the model file? This would allow a more detailed analysis of your problem. 

Kind regards,
Henrik

**Comment by Fatima-Marok** [comment]
Dear @HenrikCordes,

thank you very much for your helpfull response.

The compound itself is very soluble and permeable, also it's no substrate of any known transportation mechanism. Differences regarding intake of food are assumed to be based on delayed gastric emptying and/or instability in acidic pH. 
Patients generally get doses of 2000 mg (atleast 4 tablets), which is well described with a Weibull formulation. Doses of 150 mg (only 1 tablet) are rarely applicated, but we're able to give an adequate description by using a dissolution formulation. 
As of now we will keep this approach. I was just curious, if there is a better way to solve this situation.

Unfortunately I can not upload the file yet, since the project is still not finished. 
Again thank you very much for your response. 

Best regards,
Fatima
