### ISSUE TITLE
intracelluar unbound concentration

### ISSUE THREAD

**Issue by utopianwy** [Open-Systems-Pharmacology/Forum#358]
Hi,

I don't quite understand the calculation of the intracellular unbound drug concentration when considering the dissociation of acidic or basic drug at different pH in extracellular fluid and plasma (pH 7.4) and intracellular fluid (pH 7.0). Since the pH in all the cell types are the same, assuming the un-ionized drug reach equilibrium instantly, the unbound drug concentration in intracellular space should be the same in all tissue types. I simulated a drug with low logP and basic pKa had very different intracellular unbound concentration in different tissues. I wonder what other parameters have been using when calculating intracellular unbound concentration.

This result is very different from the understanding that the unbound drug concentration is the same in the tissue as the unbound drug concentration in plasma unless active transport involved. I'm not sure how to interpret the simulated data.

Thanks!

**Comment by HenrikCordes** [comment]
Dear @utopianwy,

thank you for posting your question!
 
The equivalence of unbound drug concentrations holds true and can be simulated with any PBPK model. But, you only reach a steady-state in you model if the input (drug intake) and out put (excretion, metabolism etc.) are equal & the system had enough time to equilibrate such that there are no more concentration differences between tissues. 
I simulated the SS for an arbitrary drug in the attached simulation file.
![image](https://user-images.githubusercontent.com/4817133/61217743-a9b46d00-a710-11e9-8c09-7f2a2c4b105e.png)

Note the log scale of the x (time) axis and that no metabolic processes are included in the first two simulations. Therefore, we know that input and out put are equal after administration (== 0). From the simulation you can see that it takes time until the drug is equally distributed between the tissues such that we reach SS where input and output are equal (==0) and the unbound drug concentration is equal in all tissues. 

So what will happen if we introduce a clearance process? Lets say in the liver:
This effect gets more prominent when we implement a higher Cl:
![image](https://user-images.githubusercontent.com/4817133/61218640-c487e100-a712-11e9-9b7f-5964a6263810.png)

Now we see that the unbound concentrations in the various tissues need more time to reach equlibrium (in fact they never reach eq until all drug is completely cleared form the model). This is due to the fact that now input and output are off balance (input = 0 & output = continuous hepatic Cl).

Note that the deviation from SS is highest for the liver (where the Cl was implemented) and the deviation between tissues gets smaller over time. Here the SS is reached when input and output of the system are equal again. 

Kind regards,
Henrik
