### ISSUE TITLE
Creating a re-qualification plan

### ISSUE THREAD

**Issue by StephanSchaller** [Open-Systems-Pharmacology/Forum#359]
Is there any guide or simplified workflow (supporting scripts) to create a re-qualification plan conveniently?

**Comment by Yuri05** [comment]
### 1. Install VSCode (Visual Studio Code)
download UserInstaller or SystemInstaller from https://code.visualstudio.com/Download

### 2. If you are behind a firewall: configure firewall proxy
* Start VSCode
* Go to File►Preferences►Settings
* Then go to User Settings►Application►Proxy
* Enter your Firewall-Proxy:

### 3. Install the snippets file
* Download the file from https://raw.githubusercontent.com/Open-Systems-Pharmacology/QualificationPlan/master/snippets/qualification.code-snippets
* Copy this file to `C:\Users\<USERID>\AppData\Roaming\Code\User\snippets `
* Restart VSCode

### 4. Create/Edit a qualification plan 
* Create a new empty file and **save it as .json** (unless the file was saved as json, snippets will not work) 
* For every element of a qualification plan (project, plot, section, input) there is a **predefined code snippet**, which will create a skeleton of this element. 
* To use a snippet, type its **shortcut** and press ENTER 
* The full list of qualification plan snippets is given in the table below. **Parent node** column describes at which places of a qualification plan a snippet can be used. 
* The first snippet to be used is always `bs `(_bootstrap_) - this will create a skeleton of a qualification plan 
* All other snippets are defined as abbreviations of "Add XYZ".  
* Full snippets list 

Shortcut | Name | Description | Parent node | Comment
-- | -- | -- | -- | --
bs | bootstrap | Creates the skeleton for a qualification plan | ROOT |  
ap | addProject | Add a project reference | Projects |  
abb | addBuildingBlockRef | Adds a building block reference. Useful to replace a building block in a project | Projects{i}/BuildingBlocks |  
asp | addSimulationParameterRef | Adds a building block reference. Useful to replace a building block in a project | Projects{i}/SimulationParameters |  
aod | addObservedDataRef | Adds an observed data reference. Only for external observed data sources | ObservedDataSets |  
ai | addInput | Adds an input (reference to a building block or simulation in a given project) | Inputs |  
as | addSection | Adds a section | Sections Sections/Sections … | Top Level section Subsections (recursively)
aps | addPlotSettings | Adds the default plot settings configuration (global or local) | Plots GOFMergedPlots{i} ComparisonTimeProfilePlots{i} DDIRatioPlots{i} PKRatioPlots{i} | Global Local Local Local Local
aas | addAxesSettings | Adds the global axes settings skeleton | Plots/AxesSettings |  
axy | addAxisSettings | Adds axes X and Y settings content | Plots/AxesSettings/GOFMergedPlotsPredictedVsObserved Plots/AxesSettings/GOFMergedPlotsResidualsOverTime Plots/AxesSettings/ComparisonTimeProfile Plots/AxesSettings/DDIRatioPlotsPredictedVsObserved Plots/AxesSettings/DDIRatioPlotsResidualsVsObserved Plots/AxesSettings/PKRatioPlots  Plots/GOFMergedPlots{i}/AxesPredictedVsObserved Plots/GOFMergedPlots{i}/AxesResidualsOverTime Plots/ComparisonTimeProfilePlots{i}/Axes Plots/DDIRatioPlots{i}/AxesPredictedVsObserved Plots/DDIRatioPlots{i}/AxesResidualsVsObserved Plots/PKRatioPlots{i}/Axes | Global Global Global Global Global Global  Local Local Local Local Local Local
aap | addAllPlot | Adds an all plot entry for a simulation | Plots/AllPlots |  
agof | addGOFMergedPlot | Adds a GOFMergedPlot entry | Plots/GOFMergedPlots |  
agofg | addGOFMergedPlotGroup | Adds a GOFMergedPlot group entry | Plots/GOFMergedPlots{i}/Groups |  
agofo | addGOGMergedPlotGroupOutputMapping | Adds a GOFMergedPlot OutputMapping entry (to be used within a group) | Plots/GOFMergedPlots{i}/Groups{j}/OutputMappings |  
actp | addComparisonTimeProfilePlot | Adds a ComparisonTimeProfile entry | Plots/ComparisonTimeProfilePlots |  
actpo | addComparisonTimeProfilePlotOutputMapping | Adds a ComparisonTimeProfile OutputMapping entry | Plots/ComparisonTimeProfilePlots{i}/OutputMappings |  
addir | addDDIRatioPlot | Adds a DDIRatioPlot entry | Plots/DDIRatioPlots |  
addirg | addDDIRatioPlotGroup | Adds a DDIRatioPlot group entry | Plots/DDIRatioPlots/Groups |  
addirr | addDDIRatioPlotGroupRatio | Adds a DDIRatioPlot ratio entry (to be used within a group) | Plots/DDIRatioPlots/Groups{i} |  
apkr | addPKRatioPlot | Adds a PKRatioPlot entry | Plots/PKRatioPlots |  
apkrr | addPKRatio | Adds a PKRatioPlot ratio entry (to be used within a PKRatioPlot) | Plots/PKRatioPlots{i} |  

* If you don't remember the shortcut of a snippet:
  * either start typing: the list of all snippets starting with this shortcut will be shown via Intellisense
  * or press CTRL+SPACE: the list of ALL snippets will be shown. Then just navigate to the right snippet and select it
![grafik](https://user-images.githubusercontent.com/25061876/61128797-3104a500-a4b3-11e9-8a99-88407e005334.png)
* After you inserted a skeleton via snippet: fill all the placeholders with correct information. Just start typing (don't click with the mouse!) into the first entry; once finished - press TAB to switch to the next input 
![GetImage](https://user-images.githubusercontent.com/25061876/61128873-614c4380-a4b3-11e9-8273-112b1e60ac72.png)
* If a value to be entered is an enumeration: click between double quotes and press CTRL+SPACE, then select from the list 
![GetImage2](https://user-images.githubusercontent.com/25061876/61128909-7d4fe500-a4b3-11e9-85f1-12bc0f774686.png)
* If a Dimension/Unit pair has to be defined: select the dimension first (CTRL+SPACE), AFTER that select the unit 
![GetImage3](https://user-images.githubusercontent.com/25061876/61128950-9789c300-a4b3-11e9-9598-6fefa3e73c3d.png)
* Every time when a new elment of a qualification plan was entered via snippet (or manually) and filled out: immediately check errors and warnings and correct them asap. 
![GetImage4](https://user-images.githubusercontent.com/25061876/61129000-bf792680-a4b3-11e9-94cb-d1ea60a47f11.png)
* When adding a new element of NON-EMPTY array, don't forget a comma before or after inserted element. (Before when inserted as last element, after otherwise). 

### Some remarks regarding qualification plans 
* Plot-settings: can be defined globally (for ALL plots) and locally (per plot). Local settings always override global settings 
* Axes-settings: can be defined globally (per plot-type) and locally (per plot). Local settings always override global settings 
* Colors: are defined in the format #RRGGBB. There are several tools for color generation, e.g. https://www.w3schools.com/colors/colors_picker.asp 
* Getting started with VSCode: https://code.visualstudio.com/docs/getstarted/introvideos 
* Editing JSON with VSCode: https://code.visualstudio.com/docs/languages/json 
* Extending/Modifying Snippets: https://code.visualstudio.com/docs/editor/userdefinedsnippets

**Comment by msevestre** [comment]
Great answer @Yuri05 .  
@StephanSchaller Please reopen if you have more questions

**Comment by StephanSchaller** [comment]
Yes, thanks @Yuri05 , sorry for not closing earlier myself
