### ISSUE TITLE
How to load database for initial morphine project help needed

### ISSUE THREAD

**Issue by jfranco119** [Open-Systems-Pharmacology/Forum#369]
I am new to PK sim how is a database loaded ,for the initial morphine project
![Screenshot (168)](https://user-images.githubusercontent.com/52639217/62645306-c94e4800-b900-11e9-8b27-6b60e967b766.png)

**Comment by PavelBal** [comment]
In order to use the gene expression database, you need to
1. Download the database from [here](https://github.com/Open-Systems-Pharmacology/Gene-Expression-Databases/releases/download/v2.0.0/GENEDB_human.expressionDb) 
2. Link the dabatase to PK-Sim as described [here ](https://docs.open-systems-pharmacology.org/working-with-pk-sim/pk-sim-documentation/pk-sim-options) (bottom of the page).

**Comment by jfranco119** [comment]
Thank you for the help it worked
