### ISSUE TITLE
Difference between "venous blood" and "peripheral venous blood" PK-Sim

### ISSUE THREAD

**Issue by AndiWeb323** [Open-Systems-Pharmacology/Forum#428]
Hi everyone, 

I have a question with reference to the differences between “venous blood” and “peripheral venous blood” in PK-Sim.

My compound has rapid distribution kinetics probably due to vanishing into the tissue and therefore has a streep drop in plasma concentrations during the first couple of minutes. As I implemented the simulations for my compound it appeared that the predicted plasma concentration curves for “venous blood” and “peripheral venous blood” differed considerably, especially in the beginning. The predicted curves for “peripheral venous blood” do not show the rapid decrease right after injection of the compound, whereas the "venous blood" does.

Does anybody have experiences with differences between “venous blood” and “peripheral venous blood”? How do you use them and could "venous blood" be more suitable in this case due to calculation methods of peripheral venous blood?

I thank you in anticipation for any help or advise.

**Comment by PriKalra** [comment]
Hi, 

Is your compound a small molecule? The way I understand it is that  venous blood represents the large veins in the animal and hence is more realistic to follow for concentration time profiles. However, for situations, where there is only blood samples taken, it is more sensible to simulate the peripheral blood to allow for more accurate description of the blood sample. 

In my data, I have seen slight differences in the venous blood and peripheral blood and I simulate the respective compartment depending on the question asked. 

I hope this helps.

Best, 
Pri

**Comment by AndiWeb323** [comment]
Hi Pri,

My compound is a small molecule and I am working with human data.

Thank you for your information :)

**Comment by tobiasK2001** [comment]
Hi AndiWeb323,

depending on the sampling side in your study individuals you have to chose between venous and peripheral venous blood.  In your case you should go with peripheral Venous Blood as humans blood samples are taken from the arm vein.
For preclinical animal samples it is different. E.g. mice are often sampled by taking retro bulbular blood which is probably more like arterial blood. Rats are sampled by the tail vein, which is more central. Here venous blood plasma should be selected. Choosing the wrong sampling side might interfere your ability to extrapolate your model results to other species. Problems are described here: PMID: 31604807
Of note, in the above paper a slightly different method is used to describe arm vein blood than PK-sim uses the for peripheral venous blood. However, the results should be very similar.

Here is from the manual how PK-sim does it: 
Two venous blood outputs can be selected: “Venous Blood” and “Peripheral Venous Blood”. “Venous Blood” refers to the compartment “Venous Blood” representing the large veins. In clinical practice it is common to sample blood at patients superficial veins, e.g. the antecubital vein. Therefore, PK-Sim® offers the opportunity to also display the pharmacokinetics of the drug in the peripheral venous plasma in order to allow a more accurate description of clinical data. Per default “Peripheral Venous Blood” is a weighted mean of skin and muscle tissue blood (about 70% contribution from skin and about 30% contribution from muscle for all species). You can change the default contribution to “Peripheral Venous Blood” by adjusting the parameters “Fraction of peripheral blood flow in organ” at “Physiology” -> “Flow Rates” -> “Peripheral Blood Flow Fraction” (select “Advanced” view for parameters). The contributions can be defined for arterial blood, bone, fat, muscle, and skin, i.e. all compartments which could possibly contribute to “Peripheral Venous Blood”. The arterial plasma is also considered because of the arteriovenous anastomoses in e.g. the skin of the hand (shunts between arteries and veins involved in the regulation of body temperature).
