### ISSUE TITLE
Intestinal CYP Inhibition

### ISSUE THREAD

**Issue by HTQ05** [Open-Systems-Pharmacology/Forum#460]
I am developing a model of drug that is CYP3A4 substrate and its interaction with other drug on PK-Sim which only inhibits Intestinal CYP3A4, not hepatic CYP3A4.. how to control or inhibit just Intestinal enzyme in PK-Sim??

**Comment by msevestre** [comment]
Couldn't you create two enzymes (CYP3A4_1 and CYP3A4_2) with one only expressed in liver and the other one in the guts? your inhibition would only target one enzyme?

**Comment by tobiasK2001** [comment]
Hi,
 Just a quick thought: of course the way Micheal describes is a good option, but why do you think your drug only inhibits intestinal CYP3A4 and not hepatic CYP3A4? Because the drug concentration at the intestinal CYP3A4 side is higher compared to the hepatic CYP3A4? If your answer is yes, this should be automatically accounted for by your model and there should be no need to introduce two CYP3A4 enzymes.

Best, Tobias

**Comment by HTQ05** [comment]
ok thank you. 
but in reference of the given statement, what whould you suggest
"Bergamottin pre-treatment had no impact on the pharmacokinetic parameters of
buspirone compared to the control group, indicating that **bergamottin did not inhibit the
hepatic CYP3A activity**; hence, the inhibition of **buspirone metabolism observed after oral
administration occurred in the intestine and not in the liver**.

**Comment by StephanSchaller** [comment]
Hi, do you have the experimental data to support this (can you provide a link to the source)?
I agree with Tobias that it is unlikely that the same CYP is inhibited in intestine but not in liver (given the same exposure). 
Likely the IC50 is (much) higher than the exposure in liver.

**Comment by tobiasK2001** [comment]
Hi,

that depends  on what you are aiming to to do. Are you trying to reproduce the Bergamottin-buspirone DDI? Or do you just want to simulate "your drug" without intestinal CYP-metabolism and mimic what Bergamottin does in general? Due to high intra luminal concentrations of Bergamottin after oral dsing and it's low bioavialability it is impacting CYPs only in GIT and not in liver. 
To mimic this general behavior with "your drug" you can just set intestinal CYP3A4 expression to zero, which would result in a Bergamottin-effect.

Hope this might help you.

Best, Tobias

**Comment by HTQ05** [comment]
I am working on Drug Interaction of Bergamottin with "my drug" that is metaboilzed by CYP3A4. Much clinical data is not available specifically for my drug, but what i have read in other papers is that "Bergamottin" inhibits only intestinal CYP3A4 and not hepatic one, like in attached paper. My aim is to check the effect of oral dosing of "MY DRUG" with concommitant administration of Bergamottin. the change in pharmacokinetics of my drug,  is what i need. 
[Bergamottin and Felodipine.pdf](https://github.com/Open-Systems-Pharmacology/Forum/files/4197616/Bergamottin.and.Felodipine.pdf)

**Comment by StephanSchaller** [comment]
Well, as Bergamottin has low bioavailability and thus likely does not affect liver CYP metabolism (IC50 likely >> concentration of "your drug" in liver), you only have to worry about potential intestinal interacation. Is "your drug" given orally? Is it highly permeable (then, even if given IV, intestinal metabolism might have an effect)?

**Comment by HTQ05** [comment]
Yes, it is given orally in sub-lingual and/ or transmucosal dosage form.

**Comment by tobiasK2001** [comment]
Sounds like an interesting project. You might think about coupling "your drug" to a "Bergamottin-PBPK" model, if available. Or you can try the "quick fix" with just setting intestinal CYP3A4 expression to zero. Depending on your compound properties and the cases you want to investigate this might already give you a good hint. In case you would like to discuss more details, which might be not appropriate to share in the forum you can reach me under: tobias.kanacher@pharmetheus.com.

Good luck! Tobias

**Comment by StephanSchaller** [comment]
> you can try the "quick fix" with just setting intestinal CYP3A4 expression to zero

I don't see a reason to do this, and it still does not solve the DDI in mucosa.
Coupling a Bergamottin PBPK model with your drug for mucosal DDI and that can account for the low bioavailability of Bergamottin (resulting in no or negligible DDI in liver) should do the job.

**Comment by HTQ05** [comment]
Okay. Thank you everyone for you help. Higly appreciated.
Regards.
