### ISSUE TITLE
Bug report: the unit problem in formula

### ISSUE THREAD

**Issue by jzq90** [Open-Systems-Pharmacology/Forum#491]
When I use Weibull function in my simulation, I found the calculated alpha doesn't match the  beta and disstime50, as shown in the picture below:

![图片](https://user-images.githubusercontent.com/58142266/77399395-538de280-6de4-11ea-978e-0f2a3aec9902.png)

I've tried some values and also a small test (parameter test3 in the picture below), test3 = test1^test2, while the answer is 60 when test=1 h and test=2 (dimensionless). It makes no sense for this. Considering this is a simple formula, I wonder if I did somewhere wrong or this is a bug.

![图片](https://user-images.githubusercontent.com/58142266/77399572-ae273e80-6de4-11ea-9f1a-6105b9082c63.png)

**Comment by jzq90** [comment]
When test1 = 1 h, the real formula for test3 is test3 = 1×60^(test2-1)
When test1 = 2 h, the real formula for test3 is test3 = 2 × 120^(test2-1)
When test1 = 3 h, the real formula for test3 is test3 = 3 × 180^(test2-1)

**Comment by jzq90** [comment]
Now I want to know if the parameter alpha in Weibull function has an influence on the simulation.
Could anyone help me？

**Comment by Yuri05** [comment]
MoBi and PK-Sim **store all parameters in the base unit of their corresponding dimension.**
All **calculations are carried out using the base units**.
Calculated values are then **displayed in the desired display unit**.

Thus e.g. if you define the parameters as following:
parameter|unit, dimension
-|-
p1 = 2 |           Dimension: Time, Unit: [h]
p2 = p1+30|   Dimension: Time, Unit: [h]
p3 =  p1+30|   Dimension: Dimensionless

Then the calculation is as following: 
* **internal** value of p1 is 120 (base unit of dimension Time is [min])
* **internal** value of p2 is 120+30 = 150
* **display** value of p2 is 2.5[h] (unit conversion [min] ==> [h])
* **internal** value of p3 is 120+30 = 150
* **display** value of p3 is 120+30 = 150 (no unit conversion because p3 was declared as dimensionless)
![grafik](https://user-images.githubusercontent.com/25061876/77418810-b9b83c80-6dc7-11ea-8eb0-919b0eec658a.png)

Now if you would use either p2 or p3 in further calculations: **both parameters would be used in their internal value of 150**.

This mini model is inconsistent, because the dimension of p3 is obviously wrong (it should be Time and not Dimensionless). If the dimension check is activated, you will get a warning when using it in a simulation:
![grafik](https://user-images.githubusercontent.com/25061876/77419758-37c91300-6dc9-11ea-8757-1c7329053744.png)

Now for e.g. Weibull_alpha it's the same situation.
`ln(2)/t50^shape` will be internally calculated as `ln(2)/t50_in_minutes^shape`.
**The value of Weibull_alpha used for all calculation will be** `ln(2)/t50_in_minutes^shape` (the internal value).

The **displayed** value depends on the dimension definition of Weibull_alpha. Because the dimension of Weibull_alpha is defined as _InversedTime_, this value as interpreted as [1/min] and is converted then to [1/h], which in this case is inconsistent as well (it corresponds to shape=1). However having arbitrary Dissolution shape as time exponent makes definition of the fixed dimension impossible.

**Comment by jzq90** [comment]
Thanks very much. I got the internal calculation method. However, I'm still confused about the unit.
For one thing, the` alpha` in software is different from the equation in the instruction.
![图片](https://user-images.githubusercontent.com/58142266/77433765-c619b500-6e1a-11ea-88e9-8858076a8f65.png)

According to the instruction book of the software, the `alpha` should be `DissTime50^DissShape/ln(2)`, but not `ln(2)/DissTime50^DissShape`. The dimension of  `alpha` should be 'Time' so it can be divided by `t`
I'm confused about this.

For another thing, the `alpha` will change if calculated by different units of the same data, while `shape` and `t50` will keep the same.

For example, if fit the dissolution with hour, `alpha1` will be `(t50)^shape/ln(2)` and the unit is hour. If change the unit to min, `alpha2` will change to `(t50*60)^shape/ln(2)`, and the unit is min. Apparently `alpha1` does not equal `alpha2`. I've validated this in DDsolver, with the same data but the different units, `alpha` will change.

Will the dissolution profile be the same when I input the `t50` with the unit of hour or min ?

**Comment by Yuri05** [comment]
>According to the instruction book of the software, the alpha should be DissTime50^DissShape/ln(2), but not ln(2)/DissTime50^DissShape. The dimension of alpha should be 'Time' so it can be divided by t
I'm confused about this.

If you check the Weibull formula in PK-Sim you will see that it is written in the form
`...exp(-alpha*(Time-LagTime)^beta)`, thus "PK-Sim Weibull alpha" = 1/Weibull_alpha

>Will the dissolution profile be the same when I input the t50 with the unit of hour or min ?

If you input the same value for t50, the outcome will be the same.
E.g. if you enter `t50 = 1[h]` it will be the same as for `t50 = 60[min]`. 
Of course if you enter `t50 = 1[min]` instead of `t50 = 1[h]` the outcome will be different, but that's obvious - isn't it?

**Comment by jzq90** [comment]
Yes, you're right. Now I get it.
Again, thanks for your kind and patient replying. Also thanks for the great software. It's amazing.
