### ISSUE TITLE
What's the meaning of FIRST_NEIGHBOR and SECOND_NEIGHBOR?

### ISSUE THREAD

**Issue by jzq90** [Open-Systems-Pharmacology/Forum#499]
What's the meaning of FIRST_NEIGHBOR and SECOND_NEIGHBOR?
![图片](https://user-images.githubusercontent.com/58142266/77884751-436c7c00-7298-11ea-9568-4b8b658b9165.png)

**Comment by PavelBal** [comment]
It is the way of dynamically adress parameters/entities located in the `source` and `target` of the transport.

In general, everything written in `CAPITAL LETTERS` means something generic. E.g., `MOLECULE` will be substituted with the name of the molecule for which the transport is created. `FISRST_NEIGHBOR` is the compartment defined in the `SOURCE` properties of this transport.

**Comment by jzq90** [comment]
> `FISRST_NEIGHBOR` is the compartment defined in the `SOURCE` properties of this transport.

So `FIRST_NEIGHBOR` = `SOURCE`?  `SECOND_NEIGHBOR` = `TARGET`?
I think I've seen the phrase `SOURCE` and `TARGET` are also used in several places.

**Comment by PavelBal** [comment]
> So FIRST_NEIGHBOR = SOURCE? SECOND_NEIGHBOR = TARGET?

> I think I've seen the phrase SOURCE and TARGET are also used in several places.
@Yuri05 Are there any differences between SOURCE and FIRST_NEIGHBOR?

**Comment by Yuri05** [comment]
**SOURCE**/**TARGET** keywords can be only used in transports (passive or active).
**FIRST_NEIGHBOR**/**SECOND_NEIGHBOR** can be used in objects located underneath a neighborhood.

Due to the fact the the most (but not all) transports are located underneath a neighborhood as well, theoretically **SOURCE**/**TARGET** in their transport rate definition could be replaced with **FIRST_NEIGHBOR**/**SECOND_NEIGHBOR**

E.g. replacing
![grafik](https://user-images.githubusercontent.com/25061876/77923531-dc07f980-72a2-11ea-8648-16f1630a864e.png)
with
![grafik](https://user-images.githubusercontent.com/25061876/77923663-0b1e6b00-72a3-11ea-9ab5-9ee668be17c2.png)
would produce the same result.

However I would not do this, because **FIRST_NEIGHBOR**/**SECOND_NEIGHBOR** rely on the **definition order** of the neighbors.

**Comment by jzq90** [comment]
Thanks for your help.
