### ISSUE TITLE
 How to solve these problems?

### ISSUE THREAD

**Issue by Wenjing1018** [Open-Systems-Pharmacology/Forum#500]
Hi，
When I ran the individual model, the PK-Analyses appeared was particularly large, Warning：Absorption seems to be incomplete or absorption process is not finished.but when I changed the oral administration to intravenous injection, the rest remained the same, and the PK- parameters obtained were all normal. I wonder where the problem is?
![image](https://user-images.githubusercontent.com/63133525/78416400-17b41200-765b-11ea-88b3-f3b4ce2f9eb6.png)
![image](https://user-images.githubusercontent.com/63133525/78416406-200c4d00-765b-11ea-8c9b-825300361986.png)
![image](https://user-images.githubusercontent.com/63133525/78416411-24386a80-765b-11ea-967f-65068d5df131.png)
![image](https://user-images.githubusercontent.com/63133525/78416415-28fd1e80-765b-11ea-987d-94965e9e5f35.png)

**Comment by jzq90** [comment]
I have encountered this warning before. I think it just reminds you that the absorption is incomplete. It happens when the drug's solubility or permeability is low, there isn't enough time for the drug to be absorbed before it leaves GIT. 
Maybe you can check the drug amount/fraction in feces in the PO simulation.

**Comment by Wenjing1018** [comment]
> I have encountered this warning before. I think it just reminds you that the absorption is incomplete. It happens when the drug's solubility or permeability is low, there isn't enough time for the drug to be absorbed before it leaves GIT.
> Maybe you can check the drug amount/fraction in feces in the PO simulation.
hello jzq90,
I tried to enlarge permeability, the warning disappeared. But the corresponding bioavailability also becomes very large, how should I weigh the permeability and bioavailability to keep it within normal limits
Thank you for your reply!

**Comment by jzq90** [comment]
> 
> 
> > I have encountered this warning before. I think it just reminds you that the absorption is incomplete. It happens when the drug's solubility or permeability is low, there isn't enough time for the drug to be absorbed before it leaves GIT.
> > Maybe you can check the drug amount/fraction in feces in the PO simulation.
> > hello jzq90,
> > I tried to enlarge permeability, the warning disappeared. But the corresponding bioavailability also becomes very large, how should I weigh the permeability and bioavailability to keep it within normal limits
> > Thank you for your reply!

It is reasonable the bioavailability increased when you increase permeability.
I don't think it's a good idea to change permeability just because of the warning. If the drug is a low permeable drug and this leads to the incomplete absorption, then the simulation shows a low bioavailability is reasonale and no need to adjust the model for this.

**Comment by Wenjing1018** [comment]
I understand what is your meaning, thank you very much!
