### ISSUE TITLE
How to add different genotypes 

### ISSUE THREAD

**Issue by shapoo1** [Open-Systems-Pharmacology/Forum#512]
I have to add different genotype combinations of two genes in PKsim. How to add it?

**Comment by Fatima-Marok** [comment]
Hi @shapoo1 

one possible way could be to build in the enzyme twice into your indivual (for example with half its respective reference concentration) in order to describe two different alleles (picture 1) and adding several metabolic pathways into your compound to describe the different genotypes (picture 2).

![github1](https://user-images.githubusercontent.com/45940242/80357651-9592c400-887b-11ea-9118-a9fd733f87c2.JPG)
![github2](https://user-images.githubusercontent.com/45940242/80357664-988db480-887b-11ea-99f8-1bfb210d7851.JPG)

Kind regards,
Fatima

**Comment by shapoo1** [comment]
Hi, Fatima-Marok 
Thanks a lot for your help. 
I have Km and Vmax values of the gene allelic variants instead of reference concentration.
e.g ADH1B*1 , Km =0.016mM ; ADH1B*2, Km= 1.9mM.  is it possible to use the Km and Vmax values rather than reference concentration?
Thanks in advance

**Comment by Fatima-Marok** [comment]
Of course. You implemend the values that you have in the reactions described in your molecule. You can add several different processes for one enzyme in your simulation, but you can only select one process at a time. So if you want to simulate a homozygous patient, for example ADH1B1 homozygous, you have to add two processes into your compound which describe the two alleles. 

![gh3](https://user-images.githubusercontent.com/45940242/80474552-e07a0d80-8947-11ea-8029-d47029b77ea3.JPG)

Afterwards you should be able to select the processes to match the genotype you want to simulate.   

![gh4](https://user-images.githubusercontent.com/45940242/80474585-ea037580-8947-11ea-89bb-2526bc2c9c6d.JPG)

I hope this helps

**Comment by shapoo1** [comment]
Dear @Fatima-Marok 
Thanks a lot for your help
