### ISSUE TITLE
allow aging - how does it work?

### ISSUE THREAD

**Issue by a2mahara** [Open-Systems-Pharmacology/Forum#514]
Hello Everyone,

I was looking to find information about how the 'allow aging' module works for simulations. Specifically, what is the time-dependence of how a subject's anatomy and physiology changes with aging (in PK-Sim)?

1. If the subject is the an 'average individual' (i.e at the 50th percentile of body weight and height for age), does the subject's anatomy of physiology represent an 'average subject' as they age?

2. If the subject is NOT an 'average subject' (i.e., body weight and height NOT at the 50th percentile for age), how does anatomy and physiology change with aging?  

3. Does each subject's anatomy and physiology change based on their own growth curve for population simulations?

4. How often is anatomy and physiology updated in the simulations (every 24 hours?)

If anyone can point me in right direction to answer these questions, that would be much appreciated.

Thanks!

**Comment by prvmalik** [comment]
Hi Anil,

For #4, the intervals on which the anatomy and physiology are updated can be seen if you export the simulation to Mobi with 'allow aging' checked and then go to the parameter path in the Spatial Structure (e.g. Organism|Kidney|Volume)

Paul

**Comment by a2mahara** [comment]
Thanks, Paul.

I noted these tables, which define changes in parameters by simulation time, are accessible in PK-Sim as well.  I was wondering how often are these parameters updated during the actual simulation run....i.e., does the kidney volume (which is interpolated using the table) update every 24 hours? OR is the kidney volume being continuously being updated during the simulation?

**Comment by prvmalik** [comment]
Thanks, I didn't realize that interpolation was applied.

I ran an observer for kidney volume in a male european default subject from 1 day old to 2 years and it looks like kidney volume updates at every simulation step. Here is the output of the observer
[KVupdate.xlsx](https://github.com/Open-Systems-Pharmacology/Forum/files/4568363/KVupdate.xlsx)
:

**Comment by Yuri05** [comment]
@a2mahara 
PK-Sim stores information about all model parameters (particularly about anatomical and physiological parameters) in one of 3 ways. Each parameter is described by one of the following alternatives:

I. Analytical formula (equation depending on other model quantities)
II. Constant (age independent) non-formula
III. Age-dependent non-formula

Parameters of the first two kinds are handled in the same way both in simulations _with_ and _without_ aging. 
Where it comes to differences are parameters of the type III (and the explanation below is for these parameters).

An individual in PK-Sim is given in the first place by the combination of covariates `{Population, Gender, [Gestational Age], Age, Weight, Height}` (_Gestational Age_ applies only for the _Preterms_ population).
For every parameter of the type III and every combination of the covariates `{Population, Gender, [Gestational Age]}` the information is stored in PK-Sim on the _predefined grid of ages_ (**supporting points**) based on literature data. For each supporting point information is stored in form of probability distribution `{Distribution type; Mean; STD}`. 

<details><summary>E.g. the information for the <b>heart volume</b> for <i>{"European_ICRP"; "MALE"}</i> looks like this:</summary>

Population | Gender | Organ | Parameter | "Age   (years)" | Distribution | Mean (l) | Std (l)
-- | -- | -- | -- | -- | -- | -- | --
European   (ICRP, 2002) | MALE | Heart | Volume | 0 | Normal | 0,03 | 0,01
European (ICRP, 2002) | MALE | Heart | Volume | 1 | Normal | 0,07 | 0,01
European (ICRP, 2002) | MALE | Heart | Volume | 5 | Normal | 0,11 | 0,02
European (ICRP, 2002) | MALE | Heart | Volume | 10 | Normal | 0,18 | 0,03
European (ICRP, 2002) | MALE | Heart | Volume | 15 | Normal | 0,29 | 0,06
European (ICRP, 2002) | MALE | Heart | Volume | 30 | Normal | 0,42 | 0,08
European (ICRP, 2002) | MALE | Heart | Volume | 40 | Normal | 0,43 | 0,11
European (ICRP, 2002) | MALE | Heart | Volume | 50 | Normal | 0,44 | 0,11
European (ICRP, 2002) | MALE | Heart | Volume | 60 | Normal | 0,45 | 0,11
European (ICRP, 2002) | MALE | Heart | Volume | 70 | Normal | 0,46 | 0,10
European (ICRP, 2002) | MALE | Heart | Volume | 80 | Normal | 0,44 | 0,09
European (ICRP, 2002) | MALE | Heart | Volume | 90 | Normal | 0,44 | 0,08
European (ICRP, 2002) | MALE | Heart | Volume | 100 | Normal | 0,43 | 0,08
</details>

When creating an individual of age which is not on the predefined age grid, the probability distribution for a given parameter is linearly interpolated based on the information in the supporting points.

Further, the probability distributions like in example above, are stored for the _**Mean** body weight_ and _**Mean** Height_ of a combination `{Population, Gender, [Gestational Age]}`. If the required weight and/or height differs from the mean value: probability distributions of _some_ parameters are _scaled_ as described in detail in the [Create Individual Algorithm](https://github.com/Open-Systems-Pharmacology/OSPSuite.Documentation/wiki/Create-Individual-Algorithm).

Finally, after an individual was created, user can optionally modify some of the individual parameters. 
Based on the probability distribution of a parameter and its current value, a **percentile** for this parameter can be calculated (which is also shown in PK-Sim).

Now the short answer to your questions 1. and 2.: **the percentile of each distributed parameter is kept constant during the whole simulation duration**. 

In more detail: when a simulation with the aging option is created, for each _distributed_ parameter the following is done:
* The table with the supporting points information for this parameter corresponding to `{Population, Gender, [Gestational Age]}` of the individual is taken from the PK-Sim database 
* Each distribution in the table is scaled based on weight/height of the original individual in the same way as for the original individual (s. [Create Individual Algorithm](https://github.com/Open-Systems-Pharmacology/OSPSuite.Documentation/wiki/Create-Individual-Algorithm))
* For each supporting point in this modified distributions table a value **corresponding to the percentile of the original individual within the probability distribution for this supporting point** is calculated
* The table is shifted in the X direction so that the 0 point on the X-Axis corresponds to the age of the individual (e.g. if your table containes supporting points 0, 10, 20, 30 years and the individual is 12 years old, the shifted table will contain supporting points 0, 8, 18 years). Thus if we would like to know the value of a distributed parameter at any time T during the simulation - we just have to get the table value corresponding to this time T.
* **Distributed parameter in the simulation is replaced by the table build in the steps above**

In an individual simulation with aging you can view such a table if you <details><summary>click on "Show Table"</summary>![grafik](https://user-images.githubusercontent.com/25061876/80915276-887d4580-8d51-11ea-9d72-b60dbca6daa9.png)</details>

For example, if you create a 80 years old European_ICRP MALE individual with **mean body weight** and **mean height** and then create a simulation with aging based on this individual, then the table for the heart volume would look like this:
![grafik](https://user-images.githubusercontent.com/25061876/80915616-c67b6900-8d53-11ea-9b6e-3e6437f3670b.png)
Which is the original table shifted by 80 years.
(and if you change body weight/height when creating the individual or change the heart volume manually, the values in the table will change according to the new percentile of the heart volume)

Now during the simulation with aging, table values are used **all the time** to retrieve the values of anatomical and physiological parameters. So the answer to your question 4: parameters are updated **continuously**.

Regarding the last question:
>3. Does each subject's anatomy and physiology change based on their own growth curve for population simulations?

For a population it's exactly the same principle. Each individual in a population has corresponding probability distributions for age-dependent (non-formula) parameters and corresponding percentiles. So **for each individual** of a population lookup-tables for distributed parameters are created as described above and used during the simulation for **continuous** updating of parameter values.

P.S. Age grids of the supporting points differ between populations and are not equidistant.
<details><summary> Population dependent grid of age supporting points</summary>

Population | Age (years)
-- | --
Asian (Tanaka, 1996) | 0
Asian (Tanaka, 1996) | 0,008219
Asian (Tanaka, 1996) | 0,0192
Asian (Tanaka, 1996) | 0,0383
Asian (Tanaka, 1996) | 0,0416667
Asian (Tanaka, 1996) | 0,0833
Asian (Tanaka, 1996) | 0,1667
Asian (Tanaka, 1996) | 0,2083333
Asian (Tanaka, 1996) | 0,375
Asian (Tanaka, 1996) | 0,5
Asian (Tanaka, 1996) | 0,7083333
Asian (Tanaka, 1996) | 1
Asian (Tanaka, 1996) | 2
Asian (Tanaka, 1996) | 2,1
Asian (Tanaka, 1996) | 3
Asian (Tanaka, 1996) | 4
Asian (Tanaka, 1996) | 5
Asian (Tanaka, 1996) | 6
Asian (Tanaka, 1996) | 6,1
Asian (Tanaka, 1996) | 6,9
Asian (Tanaka, 1996) | 7
Asian (Tanaka, 1996) | 8
Asian (Tanaka, 1996) | 9
Asian (Tanaka, 1996) | 10
Asian (Tanaka, 1996) | 11
Asian (Tanaka, 1996) | 12
Asian (Tanaka, 1996) | 12,1
Asian (Tanaka, 1996) | 13
Asian (Tanaka, 1996) | 14
Asian (Tanaka, 1996) | 15
Asian (Tanaka, 1996) | 16
Asian (Tanaka, 1996) | 17
Asian (Tanaka, 1996) | 18
Asian (Tanaka, 1996) | 19
Asian (Tanaka, 1996) | 20
Asian (Tanaka, 1996) | 21
Asian (Tanaka, 1996) | 22
Asian (Tanaka, 1996) | 23
Asian (Tanaka, 1996) | 24
Asian (Tanaka, 1996) | 27
Asian (Tanaka, 1996) | 30
Asian (Tanaka, 1996) | 34,5
Asian (Tanaka, 1996) | 44,5
Asian (Tanaka, 1996) | 45
Asian (Tanaka, 1996) | 54,5
Asian (Tanaka, 1996) | 60
Asian (Tanaka, 1996) | 74,5
Asian (Tanaka, 1996) | 81
Black American (NHANES, 1997) | 0
Black American (NHANES, 1997) | 1
Black American (NHANES, 1997) | 2
Black American (NHANES, 1997) | 3
Black American (NHANES, 1997) | 4
Black American (NHANES, 1997) | 5
Black American (NHANES, 1997) | 6,9
Black American (NHANES, 1997) | 7
Black American (NHANES, 1997) | 10
Black American (NHANES, 1997) | 13
Black American (NHANES, 1997) | 15
Black American (NHANES, 1997) | 18
Black American (NHANES, 1997) | 20
Black American (NHANES, 1997) | 30
Black American (NHANES, 1997) | 40
Black American (NHANES, 1997) | 50
Black American (NHANES, 1997) | 60
Black American (NHANES, 1997) | 70
Black American (NHANES, 1997) | 81
European (ICRP, 2002) | 0
European (ICRP, 2002) | 0,008219
European (ICRP, 2002) | 0,0192
European (ICRP, 2002) | 0,0383
European (ICRP, 2002) | 0,0833
European (ICRP, 2002) | 0,1667
European (ICRP, 2002) | 0,5
European (ICRP, 2002) | 1
European (ICRP, 2002) | 2
European (ICRP, 2002) | 2,1
European (ICRP, 2002) | 3
European (ICRP, 2002) | 4
European (ICRP, 2002) | 5
European (ICRP, 2002) | 6
European (ICRP, 2002) | 6,1
European (ICRP, 2002) | 6,9
European (ICRP, 2002) | 7
European (ICRP, 2002) | 10
European (ICRP, 2002) | 12
European (ICRP, 2002) | 12,1
European (ICRP, 2002) | 13
European (ICRP, 2002) | 15
European (ICRP, 2002) | 18
European (ICRP, 2002) | 30
European (ICRP, 2002) | 40
European (ICRP, 2002) | 50
European (ICRP, 2002) | 60
European (ICRP, 2002) | 70
European (ICRP, 2002) | 80
European (ICRP, 2002) | 81
European (ICRP, 2002) | 90
European (ICRP, 2002) | 100
Japanese (2015) | 0
Japanese (2015) | 0,008219
Japanese (2015) | 0,0192
Japanese (2015) | 0,0383
Japanese (2015) | 0,0833
Japanese (2015) | 0,1667
Japanese (2015) | 0,25
Japanese (2015) | 0,5
Japanese (2015) | 0,75
Japanese (2015) | 1
Japanese (2015) | 2
Japanese (2015) | 2,1
Japanese (2015) | 3
Japanese (2015) | 4
Japanese (2015) | 5
Japanese (2015) | 6
Japanese (2015) | 6,1
Japanese (2015) | 6,9
Japanese (2015) | 7
Japanese (2015) | 8
Japanese (2015) | 9
Japanese (2015) | 10
Japanese (2015) | 11
Japanese (2015) | 12
Japanese (2015) | 12,1
Japanese (2015) | 13
Japanese (2015) | 14
Japanese (2015) | 15
Japanese (2015) | 16
Japanese (2015) | 17
Japanese (2015) | 18
Japanese (2015) | 19
Japanese (2015) | 20
Japanese (2015) | 21
Japanese (2015) | 22
Japanese (2015) | 23
Japanese (2015) | 24
Japanese (2015) | 25
Japanese (2015) | 26
Japanese (2015) | 27
Japanese (2015) | 28
Japanese (2015) | 29
Japanese (2015) | 30
Japanese (2015) | 81
Mexican American - White (NHANES, 1997) | 0
Mexican American - White (NHANES, 1997) | 1
Mexican American - White (NHANES, 1997) | 2
Mexican American - White (NHANES, 1997) | 3
Mexican American - White (NHANES, 1997) | 4
Mexican American - White (NHANES, 1997) | 5
Mexican American - White (NHANES, 1997) | 6,9
Mexican American - White (NHANES, 1997) | 7
Mexican American - White (NHANES, 1997) | 10
Mexican American - White (NHANES, 1997) | 13
Mexican American - White (NHANES, 1997) | 15
Mexican American - White (NHANES, 1997) | 18
Mexican American - White (NHANES, 1997) | 20
Mexican American - White (NHANES, 1997) | 30
Mexican American - White (NHANES, 1997) | 40
Mexican American - White (NHANES, 1997) | 50
Mexican American - White (NHANES, 1997) | 60
Mexican American - White (NHANES, 1997) | 70
Mexican American - White (NHANES, 1997) | 81
Pregnant (Dallmann et al. 2017) | 30
Pregnant (Dallmann et al. 2017) | 30,002737907007
Pregnant (Dallmann et al. 2017) | 30,005475814014
Pregnant (Dallmann et al. 2017) | 30,008213721021
Pregnant (Dallmann et al. 2017) | 30,010951628028
Pregnant (Dallmann et al. 2017) | 30,0136895350349
Pregnant (Dallmann et al. 2017) | 30,0164274420419
Pregnant (Dallmann et al. 2017) | 30,0191653490489
Pregnant (Dallmann et al. 2017) | 30,0219032560559
Pregnant (Dallmann et al. 2017) | 30,0246411630629
Pregnant (Dallmann et al. 2017) | 30,0273790700699
Pregnant (Dallmann et al. 2017) | 30,0301169770769
Pregnant (Dallmann et al. 2017) | 30,0328548840839
Pregnant (Dallmann et al. 2017) | 30,0355927910908
Pregnant (Dallmann et al. 2017) | 30,0383306980978
Pregnant (Dallmann et al. 2017) | 30,0410686051048
Pregnant (Dallmann et al. 2017) | 30,0438065121118
Pregnant (Dallmann et al. 2017) | 30,0465444191188
Pregnant (Dallmann et al. 2017) | 30,0492823261258
Pregnant (Dallmann et al. 2017) | 30,0520202331328
Pregnant (Dallmann et al. 2017) | 30,0547581401398
Pregnant (Dallmann et al. 2017) | 30,0574960471468
Pregnant (Dallmann et al. 2017) | 30,0602339541537
Pregnant (Dallmann et al. 2017) | 30,0629718611607
Pregnant (Dallmann et al. 2017) | 30,0657097681677
Pregnant (Dallmann et al. 2017) | 30,0684476751747
Pregnant (Dallmann et al. 2017) | 30,0711855821817
Pregnant (Dallmann et al. 2017) | 30,0739234891887
Pregnant (Dallmann et al. 2017) | 30,0766613961957
Pregnant (Dallmann et al. 2017) | 30,0793993032027
Pregnant (Dallmann et al. 2017) | 30,0821372102097
Pregnant (Dallmann et al. 2017) | 30,0848751172166
Pregnant (Dallmann et al. 2017) | 30,0876130242236
Pregnant (Dallmann et al. 2017) | 30,0903509312306
Pregnant (Dallmann et al. 2017) | 30,0930888382376
Pregnant (Dallmann et al. 2017) | 30,0958267452446
Pregnant (Dallmann et al. 2017) | 30,0985646522516
Pregnant (Dallmann et al. 2017) | 30,1013025592586
Pregnant (Dallmann et al. 2017) | 30,1040404662656
Pregnant (Dallmann et al. 2017) | 30,1067783732726
Pregnant (Dallmann et al. 2017) | 30,1095162802795
Pregnant (Dallmann et al. 2017) | 30,1122541872865
Pregnant (Dallmann et al. 2017) | 30,1149920942935
Pregnant (Dallmann et al. 2017) | 30,1177300013005
Pregnant (Dallmann et al. 2017) | 30,1204679083075
Pregnant (Dallmann et al. 2017) | 30,1232058153145
Pregnant (Dallmann et al. 2017) | 30,1259437223215
Pregnant (Dallmann et al. 2017) | 30,1286816293285
Pregnant (Dallmann et al. 2017) | 30,1314195363355
Pregnant (Dallmann et al. 2017) | 30,1341574433424
Pregnant (Dallmann et al. 2017) | 30,1368953503494
Pregnant (Dallmann et al. 2017) | 30,1396332573564
Pregnant (Dallmann et al. 2017) | 30,1423711643634
Pregnant (Dallmann et al. 2017) | 30,1451090713704
Pregnant (Dallmann et al. 2017) | 30,1478469783774
Pregnant (Dallmann et al. 2017) | 30,1505848853844
Pregnant (Dallmann et al. 2017) | 30,1533227923914
Pregnant (Dallmann et al. 2017) | 30,1560606993983
Pregnant (Dallmann et al. 2017) | 30,1587986064053
Pregnant (Dallmann et al. 2017) | 30,1615365134123
Pregnant (Dallmann et al. 2017) | 30,1642744204193
Pregnant (Dallmann et al. 2017) | 30,1670123274263
Pregnant (Dallmann et al. 2017) | 30,1697502344333
Pregnant (Dallmann et al. 2017) | 30,1724881414403
Pregnant (Dallmann et al. 2017) | 30,1752260484473
Pregnant (Dallmann et al. 2017) | 30,1779639554543
Pregnant (Dallmann et al. 2017) | 30,1807018624612
Pregnant (Dallmann et al. 2017) | 30,1834397694682
Pregnant (Dallmann et al. 2017) | 30,1861776764752
Pregnant (Dallmann et al. 2017) | 30,1889155834822
Pregnant (Dallmann et al. 2017) | 30,1916534904892
Pregnant (Dallmann et al. 2017) | 30,1943913974962
Pregnant (Dallmann et al. 2017) | 30,1971293045032
Pregnant (Dallmann et al. 2017) | 30,1998672115102
Pregnant (Dallmann et al. 2017) | 30,2026051185171
Pregnant (Dallmann et al. 2017) | 30,2053430255241
Pregnant (Dallmann et al. 2017) | 30,2080809325311
Pregnant (Dallmann et al. 2017) | 30,2108188395381
Pregnant (Dallmann et al. 2017) | 30,2135567465451
Pregnant (Dallmann et al. 2017) | 30,2162946535521
Pregnant (Dallmann et al. 2017) | 30,2190325605591
Pregnant (Dallmann et al. 2017) | 30,2217704675661
Pregnant (Dallmann et al. 2017) | 30,2245083745731
Pregnant (Dallmann et al. 2017) | 30,22724628158
Pregnant (Dallmann et al. 2017) | 30,229984188587
Pregnant (Dallmann et al. 2017) | 30,232722095594
Pregnant (Dallmann et al. 2017) | 30,235460002601
Pregnant (Dallmann et al. 2017) | 30,238197909608
Pregnant (Dallmann et al. 2017) | 30,240935816615
Pregnant (Dallmann et al. 2017) | 30,243673723622
Pregnant (Dallmann et al. 2017) | 30,246411630629
Pregnant (Dallmann et al. 2017) | 30,249149537636
Pregnant (Dallmann et al. 2017) | 30,2518874446429
Pregnant (Dallmann et al. 2017) | 30,2546253516499
Pregnant (Dallmann et al. 2017) | 30,2573632586569
Pregnant (Dallmann et al. 2017) | 30,2601011656639
Pregnant (Dallmann et al. 2017) | 30,2628390726709
Pregnant (Dallmann et al. 2017) | 30,2655769796779
Pregnant (Dallmann et al. 2017) | 30,2683148866849
Pregnant (Dallmann et al. 2017) | 30,2710527936919
Pregnant (Dallmann et al. 2017) | 30,2737907006989
Pregnant (Dallmann et al. 2017) | 30,2765286077058
Pregnant (Dallmann et al. 2017) | 30,2792665147128
Pregnant (Dallmann et al. 2017) | 30,2820044217198
Pregnant (Dallmann et al. 2017) | 30,2847423287268
Pregnant (Dallmann et al. 2017) | 30,2874802357338
Pregnant (Dallmann et al. 2017) | 30,2902181427408
Pregnant (Dallmann et al. 2017) | 30,2929560497478
Pregnant (Dallmann et al. 2017) | 30,2956939567548
Pregnant (Dallmann et al. 2017) | 30,2984318637617
Pregnant (Dallmann et al. 2017) | 30,3011697707687
Pregnant (Dallmann et al. 2017) | 30,3039076777757
Pregnant (Dallmann et al. 2017) | 30,3066455847827
Pregnant (Dallmann et al. 2017) | 30,3093834917897
Pregnant (Dallmann et al. 2017) | 30,3121213987967
Pregnant (Dallmann et al. 2017) | 30,3148593058037
Pregnant (Dallmann et al. 2017) | 30,3175972128107
Pregnant (Dallmann et al. 2017) | 30,3203351198177
Pregnant (Dallmann et al. 2017) | 30,3230730268246
Pregnant (Dallmann et al. 2017) | 30,3258109338316
Pregnant (Dallmann et al. 2017) | 30,3285488408386
Pregnant (Dallmann et al. 2017) | 30,3312867478456
Pregnant (Dallmann et al. 2017) | 30,3340246548526
Pregnant (Dallmann et al. 2017) | 30,3367625618596
Pregnant (Dallmann et al. 2017) | 30,3395004688666
Pregnant (Dallmann et al. 2017) | 30,3422383758736
Pregnant (Dallmann et al. 2017) | 30,3449762828806
Pregnant (Dallmann et al. 2017) | 30,3477141898875
Pregnant (Dallmann et al. 2017) | 30,3504520968945
Pregnant (Dallmann et al. 2017) | 30,3531900039015
Pregnant (Dallmann et al. 2017) | 30,3559279109085
Pregnant (Dallmann et al. 2017) | 30,3586658179155
Pregnant (Dallmann et al. 2017) | 30,3614037249225
Pregnant (Dallmann et al. 2017) | 30,3641416319295
Pregnant (Dallmann et al. 2017) | 30,3668795389365
Pregnant (Dallmann et al. 2017) | 30,3696174459434
Pregnant (Dallmann et al. 2017) | 30,3723553529504
Pregnant (Dallmann et al. 2017) | 30,3750932599574
Pregnant (Dallmann et al. 2017) | 30,3778311669644
Pregnant (Dallmann et al. 2017) | 30,3805690739714
Pregnant (Dallmann et al. 2017) | 30,3833069809784
Pregnant (Dallmann et al. 2017) | 30,3860448879854
Pregnant (Dallmann et al. 2017) | 30,3887827949924
Pregnant (Dallmann et al. 2017) | 30,3915207019994
Pregnant (Dallmann et al. 2017) | 30,3942586090063
Pregnant (Dallmann et al. 2017) | 30,3969965160133
Pregnant (Dallmann et al. 2017) | 30,3997344230203
Pregnant (Dallmann et al. 2017) | 30,4024723300273
Pregnant (Dallmann et al. 2017) | 30,4052102370343
Pregnant (Dallmann et al. 2017) | 30,4079481440413
Pregnant (Dallmann et al. 2017) | 30,4106860510483
Pregnant (Dallmann et al. 2017) | 30,4134239580553
Pregnant (Dallmann et al. 2017) | 30,4161618650623
Pregnant (Dallmann et al. 2017) | 30,4188997720692
Pregnant (Dallmann et al. 2017) | 30,4216376790762
Pregnant (Dallmann et al. 2017) | 30,4243755860832
Pregnant (Dallmann et al. 2017) | 30,4271134930902
Pregnant (Dallmann et al. 2017) | 30,4298514000972
Pregnant (Dallmann et al. 2017) | 30,4325893071042
Pregnant (Dallmann et al. 2017) | 30,4353272141112
Pregnant (Dallmann et al. 2017) | 30,4380651211182
Pregnant (Dallmann et al. 2017) | 30,4408030281251
Pregnant (Dallmann et al. 2017) | 30,4435409351321
Pregnant (Dallmann et al. 2017) | 30,4462788421391
Pregnant (Dallmann et al. 2017) | 30,4490167491461
Pregnant (Dallmann et al. 2017) | 30,4517546561531
Pregnant (Dallmann et al. 2017) | 30,4544925631601
Pregnant (Dallmann et al. 2017) | 30,4572304701671
Pregnant (Dallmann et al. 2017) | 30,4599683771741
Pregnant (Dallmann et al. 2017) | 30,4627062841811
Pregnant (Dallmann et al. 2017) | 30,465444191188
Pregnant (Dallmann et al. 2017) | 30,468182098195
Pregnant (Dallmann et al. 2017) | 30,470920005202
Pregnant (Dallmann et al. 2017) | 30,473657912209
Pregnant (Dallmann et al. 2017) | 30,476395819216
Pregnant (Dallmann et al. 2017) | 30,479133726223
Pregnant (Dallmann et al. 2017) | 30,48187163323
Pregnant (Dallmann et al. 2017) | 30,484609540237
Pregnant (Dallmann et al. 2017) | 30,487347447244
Pregnant (Dallmann et al. 2017) | 30,4900853542509
Pregnant (Dallmann et al. 2017) | 30,4928232612579
Pregnant (Dallmann et al. 2017) | 30,4955611682649
Pregnant (Dallmann et al. 2017) | 30,4982990752719
Pregnant (Dallmann et al. 2017) | 30,5010369822789
Pregnant (Dallmann et al. 2017) | 30,5037748892859
Pregnant (Dallmann et al. 2017) | 30,5065127962929
Pregnant (Dallmann et al. 2017) | 30,5092507032999
Pregnant (Dallmann et al. 2017) | 30,5119886103069
Pregnant (Dallmann et al. 2017) | 30,5147265173138
Pregnant (Dallmann et al. 2017) | 30,5174644243208
Pregnant (Dallmann et al. 2017) | 30,5202023313278
Pregnant (Dallmann et al. 2017) | 30,5229402383348
Pregnant (Dallmann et al. 2017) | 30,5256781453418
Pregnant (Dallmann et al. 2017) | 30,5284160523488
Pregnant (Dallmann et al. 2017) | 30,5311539593558
Pregnant (Dallmann et al. 2017) | 30,5338918663628
Pregnant (Dallmann et al. 2017) | 30,5366297733697
Pregnant (Dallmann et al. 2017) | 30,5393676803767
Pregnant (Dallmann et al. 2017) | 30,5421055873837
Pregnant (Dallmann et al. 2017) | 30,5448434943907
Pregnant (Dallmann et al. 2017) | 30,5475814013977
Pregnant (Dallmann et al. 2017) | 30,5503193084047
Pregnant (Dallmann et al. 2017) | 30,5530572154117
Pregnant (Dallmann et al. 2017) | 30,5557951224187
Pregnant (Dallmann et al. 2017) | 30,5585330294257
Pregnant (Dallmann et al. 2017) | 30,5612709364326
Pregnant (Dallmann et al. 2017) | 30,5640088434396
Pregnant (Dallmann et al. 2017) | 30,5667467504466
Pregnant (Dallmann et al. 2017) | 30,5694846574536
Pregnant (Dallmann et al. 2017) | 30,5722225644606
Pregnant (Dallmann et al. 2017) | 30,5749604714676
Pregnant (Dallmann et al. 2017) | 30,5776983784746
Pregnant (Dallmann et al. 2017) | 30,5804362854816
Pregnant (Dallmann et al. 2017) | 30,5831741924886
Pregnant (Dallmann et al. 2017) | 30,5859120994955
Pregnant (Dallmann et al. 2017) | 30,5886500065025
Pregnant (Dallmann et al. 2017) | 30,5913879135095
Pregnant (Dallmann et al. 2017) | 30,5941258205165
Pregnant (Dallmann et al. 2017) | 30,5968637275235
Pregnant (Dallmann et al. 2017) | 30,5996016345305
Pregnant (Dallmann et al. 2017) | 30,6023395415375
Pregnant (Dallmann et al. 2017) | 30,6050774485445
Pregnant (Dallmann et al. 2017) | 30,6078153555514
Pregnant (Dallmann et al. 2017) | 30,6105532625584
Pregnant (Dallmann et al. 2017) | 30,6132911695654
Pregnant (Dallmann et al. 2017) | 30,6160290765724
Pregnant (Dallmann et al. 2017) | 30,6187669835794
Pregnant (Dallmann et al. 2017) | 30,6215048905864
Pregnant (Dallmann et al. 2017) | 30,6242427975934
Pregnant (Dallmann et al. 2017) | 30,6269807046004
Pregnant (Dallmann et al. 2017) | 30,6297186116074
Pregnant (Dallmann et al. 2017) | 30,6324565186143
Pregnant (Dallmann et al. 2017) | 30,6351944256213
Pregnant (Dallmann et al. 2017) | 30,6379323326283
Pregnant (Dallmann et al. 2017) | 30,6406702396353
Pregnant (Dallmann et al. 2017) | 30,6434081466423
Pregnant (Dallmann et al. 2017) | 30,6461460536493
Pregnant (Dallmann et al. 2017) | 30,6488839606563
Pregnant (Dallmann et al. 2017) | 30,6516218676633
Pregnant (Dallmann et al. 2017) | 30,6543597746703
Pregnant (Dallmann et al. 2017) | 30,6570976816772
Pregnant (Dallmann et al. 2017) | 30,6598355886842
Pregnant (Dallmann et al. 2017) | 30,6625734956912
Pregnant (Dallmann et al. 2017) | 30,6653114026982
Pregnant (Dallmann et al. 2017) | 30,6680493097052
Pregnant (Dallmann et al. 2017) | 30,6707872167122
Pregnant (Dallmann et al. 2017) | 30,6735251237192
Pregnant (Dallmann et al. 2017) | 30,6762630307262
Pregnant (Dallmann et al. 2017) | 30,6790009377332
Pregnant (Dallmann et al. 2017) | 30,6817388447401
Pregnant (Dallmann et al. 2017) | 30,6844767517471
Pregnant (Dallmann et al. 2017) | 30,6872146587541
Pregnant (Dallmann et al. 2017) | 30,6899525657611
Pregnant (Dallmann et al. 2017) | 30,6926904727681
Pregnant (Dallmann et al. 2017) | 30,6954283797751
Pregnant (Dallmann et al. 2017) | 30,6981662867821
Pregnant (Dallmann et al. 2017) | 30,7009041937891
Pregnant (Dallmann et al. 2017) | 30,703642100796
Pregnant (Dallmann et al. 2017) | 30,706380007803
Pregnant (Dallmann et al. 2017) | 30,70911791481
Pregnant (Dallmann et al. 2017) | 30,711855821817
Pregnant (Dallmann et al. 2017) | 30,714593728824
Pregnant (Dallmann et al. 2017) | 30,717331635831
Pregnant (Dallmann et al. 2017) | 30,720069542838
Pregnant (Dallmann et al. 2017) | 30,722807449845
Pregnant (Dallmann et al. 2017) | 30,725545356852
Pregnant (Dallmann et al. 2017) | 30,7282832638589
Preterm | 0
Preterm | 0,0027379
Preterm | 0,0054757
Preterm | 0,0082136
Preterm | 0,0109514
Preterm | 0,0136893
Preterm | 0,0164271
Preterm | 0,019165
Preterm | 0,0219028
Preterm | 0,0246407
Preterm | 0,0273785
Preterm | 0,0301164
Preterm | 0,0328542
Preterm | 0,0355921
Preterm | 0,0383299
Preterm | 0,0410678
Preterm | 0,0438056
Preterm | 0,0465435
Preterm | 0,0492813
Preterm | 0,0520192
Preterm | 0,054757
Preterm | 0,0574949
Preterm | 0,0602327
Preterm | 0,0629706
Preterm | 0,0657084
Preterm | 0,0684463
Preterm | 0,0711841
Preterm | 0,073922
Preterm | 0,0766598
Preterm | 0,0793977
Preterm | 0,0821355
Preterm | 0,1667
Preterm | 0,5
Preterm | 1
Preterm | 2
Preterm | 2,1
Preterm | 3
Preterm | 4
Preterm | 5
Preterm | 6
Preterm | 6,1
Preterm | 10
Preterm | 12
Preterm | 12,1
Preterm | 13
Preterm | 15
Preterm | 18
Preterm | 30
Preterm | 45
Preterm | 60
Preterm | 81
White American (NHANES, 1997) | 0
White American (NHANES, 1997) | 1
White American (NHANES, 1997) | 2
White American (NHANES, 1997) | 3
White American (NHANES, 1997) | 4
White American (NHANES, 1997) | 5
White American (NHANES, 1997) | 6,9
White American (NHANES, 1997) | 7
White American (NHANES, 1997) | 10
White American (NHANES, 1997) | 13
White American (NHANES, 1997) | 15
White American (NHANES, 1997) | 18
White American (NHANES, 1997) | 20
White American (NHANES, 1997) | 30
White American (NHANES, 1997) | 40
White American (NHANES, 1997) | 50
White American (NHANES, 1997) | 60
White American (NHANES, 1997) | 70
White American (NHANES, 1997) | 80
White American (NHANES, 1997) | 81
</details>

**Comment by msevestre** [comment]
Like @Yuri05 said

**Comment by a2mahara** [comment]
Great!!!
Thanks @prvmalik. 
Also Thanks @Yuri05 for the comprehensive explanation. That pretty much covers everything I asked from #1-4

However, one last follow-up. I noted that  models edited in MoBi and exported back to PK-Sim to conduct population simulations will NOT permit for aging during the simulation (even if the original simulation that was first exported to MoBi from PK-Sim included the 'allow aging' option).  Is this something that is being consider for future releases?

**Comment by Yuri05** [comment]
>Is this something that is being considered for future releases?

You might give a like here: https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/1458 😉

**Comment by a2mahara** [comment]
Thanks again for info, @Yuri05!!
