### ISSUE TITLE
Simulations with pregnancy population

### ISSUE THREAD

**Issue by mmalsmadi** [Open-Systems-Pharmacology/Forum#523]
Hello

I walked with the steps of creating a pregnancy population published in ""

A) I created a non pregnant female simulation in PKSim

B) I exported this simulation to MoBi

C) In MoBi, I did the following steps:
(i) the import of the pregnancy model structure; (ii) the import of the passive transports building block and linkage of drug molecule to passive transport clearance processes; (iii) the update of the molecule start values building block; (iv) the creation of a new parameter start values building block; (v) I created a simulation that had all of the necessary elements (Spatial structure: PregnantWoman, Molecules: S1, Reactions: S1, Passive transports: PregnantWoman, Observers: S1, Events: S1, Simulation settings: S1, Molecule start values: S1, Parameter start values: S1);  and (vi) I saved the simulation as .PKML file

D) (i) In pksim, I imported the simulation.PKML file as individual simulation; (ii) I created a pregnant individual with age of 30.75 years; (iii) I tried to run MoBi simulation along with PK-Sim created pregnancy individual, but it I could not follow the needed steps

What should I do else, what am I missing in step D above to run pregnancy simulation properly?

**Comment by AndreDlm** [comment]
Hi @mmalsmadi,

it seems everything you did in step A) - C) is correct, but please note that currently PK-Sim does not support individual simulations for a pregnant woman, only population simulations.
So instead of importing the simulation.PKML file as *individual* simulation, try importing it as *population* simulation and then run the simulation in PK-Sim: 

![Picture1](https://user-images.githubusercontent.com/26541603/81534788-e8cf4100-9368-11ea-9b6b-547d598afa8e.png)

This should work!
André

**Comment by billymackes09** [comment]
Nicely done. You should add some [certified doula near me North York](https://brightpathhealth.ca/services/pregnancy-care/) for the simulation.

**Comment by StephanSchaller** [comment]
> Nicely done. You should add some certified doula near me North York for the simulation.

Spam

**Comment by mmalsmadi** [comment]
Hello,

I tried these steps, and the simulation ran but no profiles were generated

please find attached the PK-Sim file 

[Ritonavir & Lopinavir_Pregnancy.zip](https://github.com/Open-Systems-Pharmacology/Forum/files/5049941/Ritonavir.Lopinavir_Pregnancy.zip)
