### ISSUE TITLE
How to make an intraperitoneal administration

### ISSUE THREAD

**Issue by HenrikCordes** [Open-Systems-Pharmacology/Forum#531]
Dear Community, 

As far as I know, this wasn't discussed before and there is no pre-defined way to do this in PK-Sim, so I'm wondering if you think simulating IP administration is possible at the moment or if there is a reasonable way to do this.

My current (biological) understanding of IP administration is that you inject a bolus into the body cavity. From there the compound is absorbed by the vascular system / different organs.

What I did so far is using the "user defined" administration protocol setting and select the interstitial space of the intestine (should have the largest surface --> highest absorption):
![image](https://user-images.githubusercontent.com/4817133/82197478-5ba56280-98fb-11ea-8473-8f224c78d0c0.png)
As formulation I choose a "First Order" process to account for the observed delay from body cavity into the system.

Okay, that's how I did i so far. However, intraperitoneal organs would include liver, spleen, small / large intestine, stomach.

What do you think about the outline approach? 
Am I overthinking this, or would also a first order bolus into the artery / vein be do the job here?

Looking forward to you suggestions
Henrik

**Comment by prvmalik** [comment]
For a small molecule, I agree that this approach would represent reality. To take it one step further: In your administration protocol, you could make multiple administrations at time 0 (or staggered near zero), dividing the dose into the various IP organs according to their volume or blood flow. 
![IP](https://user-images.githubusercontent.com/29066045/82241499-4421a600-990a-11ea-83b9-9219d0334786.JPG)

**Comment by HenrikCordes** [comment]
Hi @prvmalik ,

thank you for the response! I like your idea with splitting the dose and I will try this. 

You mentioned this would work for small molecules. 

Would you do this differently for a "large" molecules like an antibody or peptide? 

Kind regards,
Henrik

**Comment by PavelBal** [comment]
I would think that this approach should also work for peptides. The main route of peptide absorption is via the lymph flow, but this should be couvered, too, as you are administering into interstitial space.

But would like to hear @prvmalik thoughts on that.

**Comment by prvmalik** [comment]
**Regarding avenues of absorption and the lymphatic delay**: Yes the main route of IP/IM/SC absorption of a peptide or macromolecule is through lymph, but a portion (up to 20%, dependent on hydrodynamic radius) is absorbed directly into the vasculature through fluid recirculation in the capillary beds. These two different routes of absorption - one fast and one delayed - can give rise to a double peak in the venous concentrations if the plasma half-life is sufficiently fast. From my experience the plasma half-life thresholds are < 2 hours in mice/rats, < 4 hours in monkeys and < 6 hours in humans. These thresholds reflect the transit time from the local injection compartment, through the lymph and into the venous blood. In literature, this profile is observed for rhEPO and lysosomal proteins, for instance. The base model in PKSim can approximate this effect but the delay in lymphatic transit has to be added. In the present parameterization, drugs begin to enter the venous blood from the interstitial space of organs immediately after time = 0..

**Regarding pre-systemic elimination**: The large molecule model in PK-Sim does not describe cellular uptake and elimination of IP/IM/SC proteins before reaching the venous blood, yet we can observe that the bioavailabilities of some proteins can be quite low when given via these routes. Cellular uptake and subsequent degradation (particularly by phagocytosis) is the key driver of this pre-systemic elimination. It happens locally in the injection compartment and during transit through the macrophage-dense lymph nodes to varying degrees. From my experience these processes are saturable, particularly in the injection compartment if the injection volume is small. 

**Regarding the local IP injection volume**: The volume of the local injection compartment is also important. Higher IP injection volume for monoclonal antibodies lowers Cmax, delays Tmax and decreases bioavailability (ref: JS Barrett et al., 1991, PMID: 1905196). I don't have a solid theory as to why this occurs yet. It could be because the concentrations flowing from the injection compartment to the lymph are more dilute.

**Regarding transcytotic absorption**: Of unknown consequence, there is no transcytosis from the interstitial space to the vascular endothelium in the existing large molecule model.

**An additional note unrelated to peptides**: For big particles (e.g. gold nanoparticles > 10 nm radius), a significant portion become stuck in the membranes of the peritoneum for extended periods of time, up to 21 days (ref. Aborig, Malik et al., 2019, Pharmaceutics).

**Comment by HenrikCordes** [comment]
Thank you @PavelBal and @prvmalik for your sophisticated answers and you time to write and post them here I really appriciate your thoughts!

So IP allows to circumvent the absorbtion and potential gut metaboilsm, while still having a first pass metabolism in the liver. For small molecules, the IP administration should put most of the drug into the portal vein, for larger modeluces this should be the lymph.

The vascular permeability would than be the determinant of the fraction of compound entering the lymphatic system. Can you give a range or ballpark of MW and radius where this becomes the significant route?
I'm not  familiar with the lymph implementation in PK-Sim. Is the lymph like a seperate compartment connected to the interstitial space / organ blood in PK-Sim?
How would I determine the lymphatic transit time? 

Best,
Henrik

**Comment by PavelBal** [comment]
> I'm not familiar with the lymph implementation in PK-Sim. Is the lymph like a seperate compartment connected to the interstitial space / organ blood in PK-Sim?

There is no lymph compartment in PK-Sim. Lymph flow is implemented as a passive transport form the interstitial space of each organ directly into the venous blood plasma, the rate is given by the molecule's concentration in the interstitial space multiplied by the parameter `Lymph flow rate` of the organ.
