### ISSUE TITLE
PKSim: Study simulation and export urine data related questions

### ISSUE THREAD

**Issue by vbalbas** [Open-Systems-Pharmacology/Forum#54]
Dear all, 

I have just started working with PK-Sim 7.1. I was wondering if someone could help me with some questions I have: 

1.  Does someone could explain me **how the population is built** when you **create a specific population**? From the manual I understood that the population is randomly generated based on the database information, is it correct? Any more specific information?

2. I also would like to know if it would be possible to **simulate 100 times a studio of 10 individuals** with specific Age, Weight and Height range **instead of simulating 1000 individuals** with the same Age, Weight and Height range. 

3. Is it possible to **create a population** to simulate a studio which indicates **the mean (± standard deviation)** for Age, Weight and Height **instead of the ranges**? How could it be done?

4. I am trying to simulate a studio which has available data of **cumulative urinary excretion (mg)**. Once I performed the simulation, I want to compare the results with the data, but I am not able to import the data (.csv). There is an error which says that “**_There is no mapping for required table column concentration_**”. How I can solve it?

Thank you in advance,

Violeta

**Comment by msevestre** [comment]
Hi @vbalbas ,

>1.  how the population is built

PK-Sim uses the selected population to retrieve age/gender specific parameter distributions (e.g. for volume parameters, HCT etc..). In a nutshell, to create one individual in the population, random parameters are indeed generated along those distributions. Then the algorithm tests the created individual and verifies that it  belongs in the weight range defined in the population. if yes, it is added to the population otherwise another individual will be generated.

For reference, the code can be found [here](https://github.com/Open-Systems-Pharmacology/PK-Sim/blob/1cf59d1afd67b1b04a6f0b21994842de002f8d03/src/PKSim.Core/Services/CreateIndividualAlgorithm.cs#L69). You will notice that some height dependent scaling of the distributions are also done before generating the individual. If you need more info than that, let me know

>2.  simulate 100 times a studio of 10 individuals 

Once a population has been created, simulating the population will always lead to the same results. That means that simulation 100 times the same group of 10 individuals will not bring you any new information. What are you trying to achieve exactly?

>3. Is it possible to create a population to simulate a studio which indicates the mean (± standard deviation) for Age, Weight and Height instead of the ranges? 

No this is not possible at the moment. This is an interesting feature. I would suggest to create a feature request in the PKSim repository this time. If there is enough interest, this could be implemented

>4. There is no mapping for required table column concentration”

You need to import those data as Fraction and not as concentration
Right click on Observed Data => Add Fraction Data
![image](https://user-images.githubusercontent.com/1041237/28739480-3f51a472-73c9-11e7-847b-811dad7fd0e4.png)

Hope that helps,

Cheers,
Michael

**Comment by vbalbas** [comment]
Hi @msevestre ,

Thank you for your answers and comments. 

2. I just wanted to know if the population simulation results would be comparable to the study I wanted to replicate. Thank you!

3. I think indeed that it would be very good have the possibility to create a population to from the mean (± standard deviation) of height weight and age, because is how the study population characteristics is summarized in many of the manuscripts I found on the literature.

4. Thank you very much. I managed to simulate and import the data for the fraction excreted. I just thought that it was also possible to import amount data as it is possible to simulate it (mg vs time). 

Thank you very much your answers. They have been very helpful indeed.

Regards,

Violeta

**Comment by msevestre** [comment]
@vbalbas 
You can achieve more variability in your population by defining some `User Defined Variability`. This is a way for you to define in your population (or in your simulation) a distribution for parameters that are by default constant -typically parameters for which no data is available in our database-. 

for 3., could you create a new feature request [here](https://github.com/Open-Systems-Pharmacology/PK-Sim/issues). At least this is documented.

Bests,

**Comment by vbalbas** [comment]
@msevestre 

That´s great. Thank you again. New Feature already created for 3. 

Regards,
Violeta
