### ISSUE TITLE
Distribution parameters are different using individuals or population

### ISSUE THREAD

**Issue by Nathalie06** [Open-Systems-Pharmacology/Forum#542]
Hi, 

I am a new PK-sim user.

I don't understand why some distribution parameters are different using Individuals or Population, even if I use White american in both cases.
For individuals I have the following distribution parameters:
![Individuals](https://user-images.githubusercontent.com/65408543/84036214-36a58c00-a99d-11ea-9438-d66c17b6a39b.PNG)

For population I have these distribution parameters:
![population](https://user-images.githubusercontent.com/65408543/84036306-56d54b00-a99d-11ea-9982-7debcb29bc1b.PNG)

To have the same median trend I have to change Ka (acidic phospholipids). Is it normal ?

thanks in advance for your answer
Nathalie

**Comment by msevestre** [comment]
@Nathalie06 Can you share that project with us (or reproduce the behavior with another project you  can share)
It is very hard for me to tell what's happening at the moment just with a screenshot. Especially, it looks like you have modified a few parameters by hand (the one with the 
![image](https://user-images.githubusercontent.com/1041237/84152461-ac0f6c00-aa32-11ea-89e5-8a6f305f5400.png))  

In fact, some were changed in one case but not in the other (for example Part Coeff (blood cells/plasma unbound was set to 1 in your pop but is left to default 1.43 in your individual))

![image](https://user-images.githubusercontent.com/1041237/84152633-ee38ad80-aa32-11ea-8b78-867aec66ddd0.png)

vs

![image](https://user-images.githubusercontent.com/1041237/84152656-f4c72500-aa32-11ea-9ee3-c5a81e63f4e8.png)

**Comment by Nathalie06** [comment]
[Venlafaxine_forum.zip](https://github.com/Open-Systems-Pharmacology/Forum/files/4753151/Venlafaxine_forum.zip)
This is my project with individuals and population.

Thanks
Nathalie

**Comment by msevestre** [comment]
@Nathalie06 as mentioned earlier, you have a bunch of parameters that have changed in the population but not in the individual

If I reset everything (e.g. click on the Refresh icon) I see the following

![image](https://user-images.githubusercontent.com/1041237/84175112-7fb51900-aa4d-11ea-9057-c6092ddcaab4.png)



and 

![image](https://user-images.githubusercontent.com/1041237/84175140-89d71780-aa4d-11ea-97a9-16f51e1af21f.png)


The value of Partition Coeff (blood cells/plasma unbound) is a function of HCT and therefore should not be shown in the population (as it will change with each individual)

So aside from this small discrepancy, I do not understand what your problem is. If you overwrite parameters, parameters depending on those changed parameters will also change.

**Comment by Nathalie06** [comment]
Thanks I understand but I want to fix the blood to plasma ratio to published values (1), I see I changed Partition coefficient (blood cells/plasma unbound) and not Blood/Plasma concentration ratio but this parameter is not available in population. 
Is it possible to fix Blood/Plasma concentration ratio in population ?

Thanks
Best,
Nathalie

**Comment by msevestre** [comment]
Blood/Plasma concentration ratio is a formula parameter that is defined as a function of Hematocrit. It is, therefore, a parameter that does not have a fixed value by default.

If you want to fix it however, you can do so by going to the user defined variability tab and selecting the parameter for each molecule
![image](https://user-images.githubusercontent.com/1041237/84190270-a9c60580-aa64-11ea-8c42-1e9965a8dd17.png)

Then simply set a normal deviation with a MEan of 1 and std of 0
Or a constant deviation with a Mean of 0 (equivalent). In this case, all individual of your simulation will have a value for B/P ratio of 1

![image](https://user-images.githubusercontent.com/1041237/84190433-eeea3780-aa64-11ea-858d-6c4b804cb818.png)
