### ISSUE TITLE
Rat Database Required

### ISSUE THREAD

**Issue by thPrabhath** [Open-Systems-Pharmacology/Forum#551]
I have been trying to build a PBPK model for asenapine in rats, since there are no readily available databases for rats as there are for humans, can you please suggest me ways to obtain relative expressions of enzymes in rats.

**Comment by prvmalik** [comment]
I recommend to use the Gene database in PubMed.

Rat CYP1A2: https://www.ncbi.nlm.nih.gov/gene/24297

I will leave it up to you to decide which UGT isoform you want to use to describe the direct glucuronidation of asenapine in rats. You will have to be careful with UGT1A4 because it is only a pseudogene.
