### ISSUE TITLE
Kp Sclar value

### ISSUE THREAD

**Issue by humblewarrior** [Open-Systems-Pharmacology/Forum#596]
![image](https://user-images.githubusercontent.com/44484877/91345572-96961c80-e7ad-11ea-9a4e-851118dcf5d8.png)

Hi!

So, after creating simulation for my drug, I looked Kp values for various organs. If you notice in upper right corner there is a scale option, but it looks like its not functioning. No matter what value I change my scale to (e.g. from 1 to 2), it doesn't change corresponding Kp values for organs. Changing scale doesn't change anything. I am wondering what I am missing or what is the purpose of that scale function if its not doing anything?

**Comment by prvmalik** [comment]
After changing the value in the scale box, you have to press the "Scale" button.

I don't recommend overwriting these, however.

**Comment by humblewarrior** [comment]
That was so stupid me. Thank you @prvmalik. Why don't you recommend overwriting these, any particular reason?

**Comment by prvmalik** [comment]
The Kp scalar values are calculated based on organ composition and the physchem properties of the molecule, depending on the calculation method (e.g. Rodgers and Rowland, PK-Sim Standard, Schmitt). It is better to scale them by adjusting the logP value so that the integrity of the calculation methods and organ composition metrics are conserved. Then it is still possible to scale to other populations with other organ compositions (e.g. in the case of pediatrics or geriatrics, obesity and so on).
