### ISSUE TITLE
Virtual population database/generator?

### ISSUE THREAD

**Issue by DanielMoj** [Open-Systems-Pharmacology/Forum#60]
Hi everyone!

I have two questions on the virtual population database/generator in PK-Sim:

1.) I wonder if someone could provide the community with a description of the virtual population generator in PK-Sim comparable to the ontogeny database which we can already download?

2.) Can one somehow change the equations and algorithms that are implemented in the population generator? I have in vivo measurements of organ volumes from one of our cooperation partners and I would like to update or exchange the algorithms based on these in vivo measurements. 

Thanks in advance and best regards,
Daniel

**Comment by msevestre** [comment]
Hi @DanielMoj ,

1. There was a discussion in the forum a few days ago
https://github.com/Open-Systems-Pharmacology/Forum/issues/54
I would love to see a page where the algorithm could be explained as well. I would suggest to create a feature request in PK-Sim for example so that this can be taken into consideration for future releases and milestones. There is nothing like that at the moment as far as I know

2. The code is open source so you can change everything. That being said, this will be in your case quite complicated as you will need to understand how PK-Sim is working at a very deep level. My suggestion would be to do something drastically different, that would result however in the same results:
   - Create a population using PK-Sim
   - Export the population to csv file (one individual per line, one parameter per column)
   - Using excel, or matlab or whatever tool you are comfortable with, edit the volumes using your own logic based on the in vivo measurements
   - Reimport the population in PK-Sim using your edited csv


Of course, if these data could be used to create another population such as ICRP etc, this would be a great contribution to the software

Does it make sense?

**Comment by DanielMoj** [comment]
Dear msevestre,

i could not find the other discussion before starting this one, sorry!

@1.) I totally agree! If such a document could be considered for future releases that would be great!

@2.) It makes sense. However, here I have another question: Are any of the other values in the pop file (other than the organ volumes I want to "update") somehow scaled using the organ volumes in standard pop generation? If so, this approach (export->change->reimport) does not work i think. If the other values are scaled independently of the organ volumes, yes that'll work!! :) 

best regards,
Daniel

**Comment by msevestre** [comment]
Hi @DanielMoj ,

Good news. A document explaining the algorithm in details will be made available to the community shortly, hopefully in the next few weeks.

>Are any of the other values in the pop file (other than the organ volumes I want to "update") somehow scaled using the organ volumes

As far as I know, there should not be any values depending on volume values.  There might be a few parameters that are clearly a function of volume values such as Body weight for example, but those parameters are not used when re-importing the data. The document that will be published soon (see above) will list those parameters explicitly.

As long as you create volume values corresponding to the actual age of the individual, (parameter Age) , you should be fine. The whole process could be scripted nicely in Matlab, R, Excel so that you would only have to export, run your script and import again.

Don't hesitate to share your script with the community as this could help others.

Cheers,

**Comment by msevestre** [comment]
Let us know if you need more help here. Please do not hesitate to let is know how it worked out
