### ISSUE TITLE
How to use PKSim.BatchToo.exe?

### ISSUE THREAD

**Issue by TuringsFlow** [Open-Systems-Pharmacology/Forum#64]
I am a Computer Science student and I would like to automate running and postprocessing  of PKSim models. Installation Validator tool was added after version 7.1 and I think it uses PKSim.BatchToo.exe for similar aims. Unfortunately I was not able to find any documentation about that tool. I will be glad if I could use it because I think it would be very useful for what I need to do. Any help welcome!

**Comment by msevestre** [comment]
Could you describe what you are trying to do in more details? Once I understand the context, I should be able to give you pointers and also assess if the functionality you need is supported by the batch tool. Thanks

**Comment by TuringsFlow** [comment]
I have some PK-Sim's project file, I would like to execute automatically every simulation, both individual and population, and obtain xml (Export for MatLab) and csv (Export result, Export PKAnalysis, Export Population) files. In addition I would compare results, saved in csv.

**Comment by msevestre** [comment]
Hey @TuringsFlow 

This is not supported out of the box by `PKSim.BatchTool`. This would not be too hard to implement however since most of the code is already available in the tool. That being said, there is no support at the moment for population simulation, but this would not be too hard to implement either.

Now the good news is that as part of the 7.3 release, this functionality and much more will be implemented in PK-Sim. This release will hopefully happen before the end of the year. We will also launch an EAP (Early Access Program) in the next few weeks. That means that you could have access to this functionality as soon as it is implemented. 

Hope that helps,
Cheers,

**Comment by TuringsFlow** [comment]
Thank you @msevestre , I appreciate your answer. 
I have another question. If I run PKSim.BatchTool.exe normally, it generates some files, among which csv files. On the other hand, if I run it on command-line, using --input and --output options, it generates files like before, but without csv. How could I obtain those files?

**Comment by msevestre** [comment]
@TuringsFlow 

First off, the `PKSim.BatchTool` CLI api needs to be looked at and checked for consistency. Until previous version, the tool was not part of the release and was only used for internal purposes only. Not all functionalities of the UI are available from the command line. In particular, csv export from the command line is not available because it was not required for our use cases. 

I have created [CLI for PKSim.BatchTool #256](https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/256). Please check it out. Your inputs here would be valuable

That being said, the information that is available in the csv can be found entirely (and much more) in the corresponding json file. With any json parser, you should be able to retrieve the output of a given simulation.

**BEWARE**: This will not run project files. Instead it runs a json representation that only support a subset of all PK-Sim functionalities (in particular, no population simulation nor advanced protocol can be simulated at that stage). This will be changed with the upcoming 7.3 version.

**Comment by TuringsFlow** [comment]
In that thread there is all I need, thank you very much. I'll wait for next release!
