### ISSUE TITLE
Modifying Parameter Start Values in MoBi

### ISSUE THREAD

**Issue by watt0005** [Open-Systems-Pharmacology/Forum#65]
![parameter start values screen shot](https://user-images.githubusercontent.com/31321213/29682279-786c51fc-88d8-11e7-96c6-9851bd879a06.png)
I want to modify parameter start values in MoBi for fraction interstitial, fraction intracellular, and fraction vascular. I have two questions:

1. Fraction intracellular is not listed as an option under Parameter Name or any of the Path Elements. By default is it always equal to 1 - Fraction Interstitial - Fraction Vascular? i.e., if I modify Fraction Interstitial and Fraction Vascular, will Fraction Intracellular automatically change?
2. Nomenclature appears different based on the organ (see screen shot above). For example, 

Fat Fraction Interstitial
Container Path: Organism
Parameter Name: Mean | Fat | Fraction interstitial
Value: 0.49

Liver Fraction Interstitial
Container Path: Organism
Parameter Name: Fraction interstitial | Liver
Value: 0.16

Is there a reason that the Parameter Name for Fraction interstitial is different for Fat and Liver?"
Thanks,
Kevin

**Comment by msevestre** [comment]
Hi @watt0005,

> if I modify Fraction Interstitial and Fraction Vascular, will Fraction Intracellular automatically change?

This is absolutely correct. We want to ensure that the sum of all those fractions is always 1. We decided to arbitrary have two value editable (vascular and interstitial) and derive intracellular automatically. You can override that behavior if you wish (by defining a value for fraction intracellular in the PSV for example) but **you** are then responsible for the sum consistency

>Nomenclature appears different based on the organ (see screen shot above)

This is a very good question. For some very few fraction parameters (in Fat and Muscle for interstitial and Lung for vascular I believe), there are some age dependent information defined in the PK-Sim database. Those parameters are thus defined slightly differently in PK-Sim and looks different when exporter to MoBi. 

Instead of simple constant value, a distribution is saved underneath the hood with a Mean and sometime STD if variability is also available. 

This is the case for the`Fat| Fraction interstitial` in your example. On the other hand, the parameter `Liver|Fraction interstitial` has **NO** age dependency in the underlying population and was just defined as a simple constant value. 

This is where the apparent discrepancy is coming from. Note that the name of the parameter is in both case the same `Fraction interstitial` but the type of the formula used is not the same (constant vs distribution). That means that in order to change the value for `Fat| Fraction interstitial`, you can either update the Mean value OR probably better so that your changes are the same for all organs, you could create a new entry in the PSV table for `Fat|Fraction interstitial` (same line as for Liver replacing Liver with Fat). That way you would not have to deal with the structure difference.  In the later case, the entry in the PSV would override the distribution value.

Let me know if you need more help,

Cheers,
Michael
