### ISSUE TITLE
Adding captions to plots in a qualification report?

### ISSUE THREAD

**Issue by jsmirob** [Open-Systems-Pharmacology/Forum#656]
I am writing a qualification report, and would like to be able to add captions to the plots, both to provide additional information about the plot, and to have a way to reference them within the rest of the text (e.g. see figure 7).

Is there a way to do this? Alternatively, is there a way to change the titles of the AllPlots?

**Comment by msevestre** [comment]
@jsmirob I believe that the "AllPlots" directive is taking the information directly from your PK-Sim project. 
So if you update the title in the PK-Sim project file, then update your snapshot file, you should have updated captions for your plots

Let me know if this works out for you

**Comment by Yuri05** [comment]
As @msevestre said, "AllPlots" takes the caption information from the plot settings in PK-Sim:
* If the plot **Title** is not empty, it is used as a caption in qualification reports
* Otherwise: plot **Name** will be used as caption

![grafik](https://user-images.githubusercontent.com/25061876/102266434-b7c77800-3f18-11eb-96b6-a51664f88bbb.png)

For all other kinds of plots plot caption can be set directly in the qualification plan via the "Title" property, e.g:

https://github.com/Open-Systems-Pharmacology/Qualification-DDI-CYP3A4/blob/6860c30c11901c68e539e44c106980cc27477b72/Qualification/Input/qualification_plan.json#L9323-L9326

**Comment by jsmirob** [comment]
Thanks.
