### ISSUE TITLE
How to simulate in PK-Sim if a drug has colonic absorption?

### ISSUE THREAD

**Issue by Dieter08** [Open-Systems-Pharmacology/Forum#67]
Some drugs have colonic absorption, eg diclofenac, metoprolol etc. This  is specifically of paramount importance if a modified release form should be developed.
Can the permeability of the colon be adjusted by PK-Sim? Or is any other adjustment possible?

**Comment by JanSchlender** [comment]
Dear Dieter08,

To account for an altered sectional absorption along the GI tract you should adjust the "Effective surface area enhancement factor", which is a multiplier of the intestinal permeability. By changing the factor, you can consider unknown uptake (increase of the factor) or efflux (decrease).

Please switch to advanced view in the respective tab in order to display the parameter.

![enhancement factor](https://user-images.githubusercontent.com/26056951/29712972-ba28e1ea-899c-11e7-9ef0-a193521f2a47.JPG)

**Comment by msevestre** [comment]
@Dieter08 Let us know if you need more help. Thanks
