### ISSUE TITLE
Whole organ observer

### ISSUE THREAD

**Issue by Ricardo-DO** [Open-Systems-Pharmacology/Forum#709]
Dear OSP community

I have seen in different posts that the "Whole Organ" observer is mentioned as something different as the "Tissue" observer.
I been having problems finding it.
These are captures from PK v9.1

In the "Define settings and run" window, it only appears the "Tissue" observer.
![no whole organ1](https://user-images.githubusercontent.com/59565610/113509313-cc259400-954c-11eb-90c7-8ce5aeccc743.png)

I tried to create an observer with that name and then tried to "Load it from a template", but I got this message.
![no whole organ observer](https://user-images.githubusercontent.com/59565610/113509366-0e4ed580-954d-11eb-8c66-bdf6207fa47b.png)

Is the Whole Organ observer need to be created in MoBi first?

Many thanks in advance,
Ricardo

**Comment by Christoph27** [comment]
Dear Ricardo,

The „Whole Organ“ Observer represents the whole organ including blood. Per default the complete blood volume of an organ is taken into account but you can change that via the parameter „Fraction of blood for sampling“ which is present in each organ. This is useful to take into account residual blood in experimentally measured tissue concentrations. Since this is especially relevant for large molecules (e.g. antibodies) this Observer was introduced in PK-Sim for the model for large molecules and is only available if you use this model (which can nevertheless be used also for small molecules!) . 
The „Tissue“ Observer gives the concentration without residual blood.

Best, Christoph

**Comment by Ricardo-DO** [comment]
Dear Christoph,

Many thanks for your reply!

Thanks,
Ricardo
