### ISSUE TITLE
Parameter Identification stops with "Faulted"

### ISSUE THREAD

**Issue by DanielMoj** [Open-Systems-Pharmacology/Forum#74]
Dear Community,

I have set up a MoBi File with Pk-Sim Version 6.3.2. At the moment I am using Version 7.0.0. In the MoBi File there are several simulations. To compare the parameter optimization results using MoBi (7.0.0.) with the results of the MoBi optimization toolbox for Matlab that I used before (with version 6.3.2) I chose several simulations.
For two of the simulations, MoBi is not able to even get to the first optimization evaluation. The optimzation stops with the error message shown in the attached picture.
![image](https://user-images.githubusercontent.com/30256131/30852948-a51f6fa6-a2ad-11e7-9a12-2574db419617.png)

What does that mean? How can I get it to start the optimization?

Thank you in advance and best regards,
Daniel

**Comment by Yuri05** [comment]
Do you have observed data points with `time>=simulation time`? If so, please increase your simulation time, so that it becomes **strictly** greater than all observed data times.

As far as I remember we fixed this issue in 7.1 or 7.2. 
In any case I would recommend you an upgrade to the latest version (7.1) ;-)

**Comment by DanielMoj** [comment]
Hi Yuri05,

ok thank you very much and good to know!

Best regards
Daniel

**Comment by PavelBal** [comment]
> As far as I remember we fixed this issue in 7.1 or 7.2.

Yes, fixed in 7.1.
