### ISSUE TITLE
Expression data

### ISSUE THREAD

**Issue by vaimun** [Open-Systems-Pharmacology/Forum#8]
I do not see any expression of CYP enzymes in the lower panel ( shows 0 percent in front of liver periportal and liver pericentral) even upon adding the various enzymes under metabolizing enzymes  in expression tab.  I do see expression of enzymes when I upload the template individual (standard european male for DDI).  My question is do I need to manually enter the expression percentage for liver and other GIT parts.  If yes, what is good source for reference values of these enzymes in different parts of GIT. 

Thanks

**Comment by msevestre** [comment]
There are two different ways to add expressions for an enzyme:
* using default values (all 0)
* using the gene expression database 
![image](https://cloud.githubusercontent.com/assets/1041237/26009834/80c958de-3718-11e7-8011-d7eb3e155281.png)

In order to use the Gene Expression database, you need to: 
1. [download the database](https://github.com/Open-Systems-Pharmacology/Suite/releases/download/v7.0.0/GENEDB_human.mdb)  
2. Set the database in your application settings. This can be set under **Utilities->Options->Application**
![image](https://cloud.githubusercontent.com/assets/1041237/26009930/ef518ae2-3718-11e7-9c5e-a53347d818d7.png).
 You need to select the location where the Gene Expression DB was downloaded

After that, you should be able to use the **Add Metabolizing Enzyme... (Database query)** option.

Hope that helps :)

**Comment by vaimun** [comment]
Thanks Michael for your help.  I was able to import the enzyme expression data from database and it worked !!.  Just extension of this questions, is there is also database for other species or need to do manual entry for the other species. 

Thanks

**Comment by msevestre** [comment]
@vaimun I think there is only one database for human available at this time but I might be mistaken. @Yuri05 ?

**Comment by Yuri05** [comment]
Further gene expression databases (mouse, rat) are in development. 
Currently only human gene expression database is available.

**Comment by vaimun** [comment]
Thanks Michael and Yuri for sharing the information.

**Comment by Keyur-UTHSC** [comment]
Hi Michael and Yuri,
I am working of preclinical PBPK modeling and was wondering if there is a GENEDB for mouse and rat. Looking forward hearing from you, really appreciate it.

Thanks,
Keyur
