### ISSUE TITLE
meropenam pbpk model

### ISSUE THREAD

**Issue by moulirc** [Open-Systems-Pharmacology/Forum#91]
I am trying to build a PBPK model for Meropenem. I was following the example (Ciprofloxacin) to develop this model.
I do not know how to implement the 70% renal clearance factor into the compound.
Potential transporter - OAT1, OAT3, % drug metabolized 30,
Metabolism (enzyme - DHP1), metabolites - two isomers of β-lactam ring-opened metabolites
Blood plasma partition - 0.55, Additional systemic clearance 3.6 l/h, Volume at steady state 0.29.

Please let me know if you need the project file.

Thank you.
Mouil

**Comment by Aedginto** [comment]
To implement renal clearance you can just add a renal plasma clearance and ensure, in the end, that the fraction excreted unchanged in urine is as reported (use the graphing function to select this output). To mechanistically model renal clearance you first need to determine the responsible processes. Is there tubular secretion or reabsorption and to what extent? It seems like you have some understanding of transporters responsible for secretion. In this case, set GFR fraction to 1 (this will calculate maximal clearance due to GF and is GFR*fu). Then add transporters on the apical side of the kidney. It is unlikely that you will be able to uniquely identify the clearance of more than one influx transporter so I would just add a generic one. If you have additional data, you of course can add as many as you like. The intrinsic clearance (or MM kinetics) of the transporter can then be optimized (manually or numerically) to reach the 70%. If you are doing this numerically, you need both observed plasma data as well as observed fraction excreted unchanged in urine (over time is great but one point will do); fraction excreted unchanged in urine is not 'optimizable' from a plasma profile. 
Let me know if you have questions,
Andrea

**Comment by moulirc** [comment]
I have attached the image file is the way to do it. I am pretty much new to this and this is the first time i am trying to add a compound for a pbpk simulation. please advise.

kind regards
Mouli


![image](https://user-images.githubusercontent.com/27323536/32517734-09c5eacc-c453-11e7-8b53-63ce13ed743c.png)
