### ISSUE TITLE
Double peak

### ISSUE THREAD

**Issue by moulirc** [Open-Systems-Pharmacology/Forum#92]
Hi ,

Could some one suggest how I can address this double peak.

The drug used is paracetamol .

Let me know if you need the project file for further clarification.

![image](https://user-images.githubusercontent.com/27323536/32471576-cb2cd0b8-c3a9-11e7-80f4-d05a50f69220.png)

**Comment by moulirc** [comment]
Please find attached the project file.
Thanks
Mouli

[Paracetamol_L3.zip](https://github.com/Open-Systems-Pharmacology/Forum/files/1449974/Paracetamol_L3.zip)

**Comment by Aedginto** [comment]
I opened the file. Do you have in vitro data to support your dissolution profile? It seems to be set as an extended release. 
Andrea

**Comment by moulirc** [comment]
You can see the in vitro data under observed data (_FDS_L3).

Kind regards
Mouli

**Comment by tobiasK2001** [comment]
Dear Mouli,
looking in your Simulation it looks like the splitted peaks are results of the fraction absorbed from your extended release formulation along the way trough the intestine
![grafik](https://user-images.githubusercontent.com/25585248/32537401-c50f07dc-c462-11e7-93f2-c88424403c9e.png)
However by defualt PK-sim thinks that your formulation is a solid tablet, which is obviously not the case as you tablets are crushed. Therefore you should enable "use as suspension" in your formulation. 
![grafik](https://user-images.githubusercontent.com/25585248/32537501-2e18694e-c463-11e7-8310-fe118da7fa55.png)
I also cked it as favorite paramter in the attached project so that it is easier to find. This will result in a more realtistic simulation of the passage through the intestine and smothes the peaks
![grafik](https://user-images.githubusercontent.com/25585248/32537599-758d6b1c-c463-11e7-8833-7cf0b740b5d5.png)

Btw. You have a very nice example here how extended release and metabolism have to be carefully balanced and informed to explain measured data. It is not possible (as you have probably tried already) to fit the metabolism if you use an immediate release. I have added a IR simulation in the attached project. Only extended release (as suspension) and adapted CYP metabolism can explain the data. Really nice!
[Paracetamol_L3_suspension.zip](https://github.com/Open-Systems-Pharmacology/Forum/files/1453030/Paracetamol_L3_suspension.zip)
Best, Tobias

**Comment by moulirc** [comment]
Dear Tobiask2001,

really appreciate your help on this issue. 

kind regards
Chandramouli
