### ISSUE TITLE
Drug dosing predictions in an obese patient

### ISSUE THREAD

**Issue by msrinivasan1** [Open-Systems-Pharmacology/Forum#94]
Dear OSP forum,

Let me explain the clinical scenario here. 
We came across an obese patient with a certain infection. We're trying to understand how to dose this patient. The patient is around 140 kgs. The antibiotic is an old drug and therefore dosing information in the obese is not available. We do not have TDM data from him as well. But what we do have is some healthy volunteer plasma conc-time data from the literature. 

Question is How do I use this information, to understand if the current dosing recommendations (recommended for an average body weight person) is adequate for this patient who is morbidly obese?

I did the following-

I created a virtual patient population 100 patients weighting between 90- 165 kgs in weight.
I put in all the drug related information (which I got from drugbank.ca, administration information (dosing what is usually given to patients)and simulated the conc-time profile

However, I'm getting a Cmax of the drug at 0.02 umol/L. It is really small as compared to the data in the literature and therefore not clinically meaningful. 

Any idea what I am missing here?

Thank you for your help in advance!

**Comment by msrinivasan1** [comment]
In addition to the above, say, if I have limited clinical data on this situation, such as from a case report of dosing one obese patient, can I incorporate the conc-time profiles from that here? And the available healthy volunteer data as well? The lower predictions could be due to the higher volume of distribtion in the obese patient, but I'm unable to find a way to input this parameter into the model

**Comment by Aedginto** [comment]
Hi there,
In order to answer the question that you have, the drug-specific model needs to be created first. Since this is an old drug, model building with IV data first to understand the drivers of systemic disposition is required. This would be done in non-obese individuals and potentially obese individuals if the in vivo PK data is available. If the drug is given extravascularly, a route-specific model needs to be created as well. Only then will you have an understanding of the expected predictive value of your model. Once this is all done, then you can create an obese population and see what happens. 

A general model development workflow (these are for predicting in kids but the workflow concepts are the same as extrapolation to other sub-groups) can be found in: Maharaj et al 2014. A workflow example of PBPK modeling to support pediatric research and development: case study with lorazepam. or Maharaj and Edginton 2014. Physiologically Based Pharmacokinetic Modeling and Simulation in Pediatric Drug Development. 

All the best!
Andrea

**Comment by msrinivasan1** [comment]
Thank you Andrea, will follow the workflow! I'll keep the OSP group posted :)

Kind regards,

**Comment by msrinivasan1** [comment]
Hello,

With regards to the above example, I wanted to know if we can manually adjust the volume of distribution in the simulation once the simulation has run? My Vd from the simulation is very unreasonable, Actual measured clearance is around 0.4L/kg but PK SIM shows around 66 L/kg, is there any way I can correct for this while simulating?

**Comment by msevestre** [comment]
@msrinivasan1 Volume of distribution (Vd) is an **output parameter** of PK-Sim calculated using the output data (predicted concentration time profile) of your model. As such it is not possible to adjust Vd for your simulation. 

It seems that you have way too much clearance in your model. As @Aedginto suggested, try to build an IV Model which should help you understand the clearance processes involved with your compound.

Hope that helps,

**Comment by msevestre** [comment]
@msrinivasan1 Please let us know if you need more help. Thanks
